---

foreman_content_credentials_debian9: []

foreman_products_defaults: &foreman_products_defaults
  content_type: deb
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy
  deb_components: "{{ foreman_products_debian9_default_deb_components | default( foreman_products_debian_default_deb_components | default( foreman_products_deb_default_deb_components | default('main') ) ) }}"
  deb_architectures: amd64

foreman_products_debian9:
  - name: Debian
    label: Debian
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: Debian 9 (Stretch)
        label: debian-9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_debian9 }}/"
        deb_releases: stretch
        organization: "{{ foreman_organization_debian9 }}"
      - name: Debian 9 (Stretch) - Updates
        label: debian-9-updates
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_debian9 }}/"
        deb_releases: stretch-updates
        organization: "{{ foreman_organization_debian9 }}"
      # - name: Debian 9 (Stretch) - Proposed Updates
      #   label: debian-9-proposed-updates
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_debian9 }}/"
      #   deb_releases: stretch-proposed-updates
      #   organization: "{{ foreman_organization_debian9 }}"
      - name: Debian 9 (Stretch) - Backports
        label: debian-9-backports
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_debian9 }}/"
        deb_releases: stretch-backports
        organization: "{{ foreman_organization_debian9 }}"
      # - name: Debian 9 (Stretch) - Backports - Sloppy
      #   label: debian-9-backports-sloppy
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_debian9 }}/"
      #   deb_releases: stretch-backports-sloppy
      #   organization: "{{ foreman_organization_debian9 }}"
      - name: Debian 9 (Stretch) - Security updates
        label: debian-9-security
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_debian9 }}-security/"
        deb_releases: stretch/updates
        organization: "{{ foreman_organization_debian9 }}"

foreman_content_views_debian9:
  - name: cv_debian9
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: Debian 9 (Stretch)
        product: Debian
    allow_promote: False
  - name: cv_debian9_updates
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: Debian 9 (Stretch) - Updates
        product: Debian
    allow_promote: False
  # - name: cv_debian9_proposed_updates
  #   organization: "{{ foreman_organization_debian9 }}"
  #   repositories:
  #     - name: Debian 9 (Stretch) - Proposed Updates
  #       product: Debian
  #   allow_promote: False
  - name: cv_debian9_backports
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: Debian 9 (Stretch) - Backports
        product: Debian
    allow_promote: False
  # - name: cv_debian9_backports_sloppy
  #   organization: "{{ foreman_organization_debian9 }}"
  #   repositories:
  #     - name: Debian 9 (Stretch) - Backports - Sloppy
  #       product: Debian
  #   allow_promote: False
  - name: cv_debian9_security
    organization: "{{ foreman_organization_debian9 }}"
    repositories:
      - name: Debian 9 (Stretch) - Security updates
        product: Debian
    allow_promote: False

  - name: ccv_debian9
    organization: "{{ foreman_organization_debian9 }}"
    composite: True
    auto_publish: True
    components:
      - content_view: cv_debian9
        latest: true
      - content_view: cv_debian9_updates
        latest: true
      # - content_view: cv_debian9_proposed_updates
      #   latest: true
      - content_view: cv_debian9_backports
        latest: true
      # - content_view: cv_debian9_backports_sloppy
      #   latest: true
      - content_view: cv_debian9_security
        latest: true

foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Debian"
  password_hash: "SHA512"
  architectures:
    - amd64
  # ptables:
  #   - Preseed default
  #   - Preseed default LVM
  ptables: "{{
    [ 'Preseed default',
      'Preseed default LVM' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Debian') | map(attribute='name') | list )
    }}"

foreman_operatingsystems_debian9:
  - name: "Debian"
    major: "9"
    release_name: stretch
    description: "Debian 9 (Stretch)"
    default_templates: "{{ foreman_operatingsystems_debian9_default_templates | default( foreman_operatingsystems_debian_default_templates | default( foreman_operatingsystems_deb_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults

foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Debian
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"
  operatingsystems:
    - Debian 9 (Stretch)

foreman_installation_media_debian9:
  - name: Debian 9 (Stretch)
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Debian/debian-9/"
    <<: *foreman_installation_media_defaults

foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Debian"
  auto_attach: False

foreman_activation_keys_debian9:
  - name: ak_debian9
    organization: "{{ foreman_organization_debian9 }}"
    content_view: ccv_debian9
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_Debian_debian-9"
        override: default
      - label: "{{ foreman_organization }}_Debian_debian-9-updates"
        override: default
      # - label: "{{ foreman_organization }}_Debian_debian-9-proposed-updates"
      #   override: default
      - label: "{{ foreman_organization }}_Debian_debian-9-backports"
        override: disabled
      # - label: "{{ foreman_organization }}_Debian_debian-9-backports-sloppy"
      #   override: disabled
      - label: "{{ foreman_organization }}_Debian_debian-9-security"
        override: disabled

