---

foreman_content_credentials_debian10: []

foreman_products_defaults: &foreman_products_defaults
  content_type: deb
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy
  deb_components: "{{ foreman_products_debian10_default_deb_components | default( foreman_products_debian_default_deb_components | default( foreman_products_deb_default_deb_components | default('main') ) ) }}"
  deb_architectures: amd64

foreman_products_debian10:
  - name: Debian
    label: Debian
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: Debian 10 (Buster)
        label: debian-10
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_debian10 }}/"
        deb_releases: buster
        organization: "{{ foreman_organization_debian10 }}"
      - name: Debian 10 (Buster) - Updates
        label: debian-10-updates
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_debian10 }}/"
        deb_releases: buster-updates
        organization: "{{ foreman_organization_debian10 }}"
      # - name: Debian 10 (Buster) - Proposed Updates
      #   label: debian-10-proposed-updates
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_debian10 }}/"
      #   deb_releases: buster-proposed-updates
      #   organization: "{{ foreman_organization_debian10 }}"
      - name: Debian 10 (Buster) - Backports
        label: debian-10-backports
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_debian10 }}/"
        deb_releases: buster-backports
        organization: "{{ foreman_organization_debian10 }}"
      # - name: Debian 10 (Buster) - Backports - Sloppy
      #   label: debian-10-backports-sloppy
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_debian10 }}/"
      #   deb_releases: buster-backports-sloppy
      #   organization: "{{ foreman_organization_debian10 }}"
      - name: Debian 10 (Buster) - Security updates
        label: debian-10-security
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_debian10 }}-security/"
        deb_releases: buster/updates
        organization: "{{ foreman_organization_debian10 }}"

foreman_content_views_debian10:
  - name: "{{ foreman_cv_prefix | default('cv_') }}debian10"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: Debian 10 (Buster)
        product: Debian
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}debian10_updates"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: Debian 10 (Buster) - Updates
        product: Debian
    allow_promote: False
  # - name: "{{ foreman_cv_prefix | default('cv_') }}debian10_proposed_updates"
  #   organization: "{{ foreman_organization_debian10 }}"
  #   repositories:
  #     - name: Debian 10 (Buster) - Proposed Updates
  #       product: Debian
  #   allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}debian10_backports"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: Debian 10 (Buster) - Backports
        product: Debian
    allow_promote: False
  # - name: "{{ foreman_cv_prefix | default('cv_') }}debian10_backports_sloppy"
  #   organization: "{{ foreman_organization_debian10 }}"
  #   repositories:
  #     - name: Debian 10 (Buster) - Backports - Sloppy
  #       product: Debian
  #   allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}debian10_security"
    organization: "{{ foreman_organization_debian10 }}"
    repositories:
      - name: Debian 10 (Buster) - Security updates
        product: Debian
    allow_promote: False

  - name: "{{ foreman_ccv_prefix | default('ccv_') }}debian10"
    organization: "{{ foreman_organization_debian10 }}"
    composite: True
    auto_publish: True
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian10"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian10_updates"
        latest: true
      # - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian10_proposed_updates"
      #   latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian10_backports"
        latest: true
      # - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian10_backports_sloppy"
      #   latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}debian10_security"
        latest: true

foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Debian"
  password_hash: "SHA512"
  architectures:
    - amd64
  # ptables:
  #   - Preseed default
  #   - Preseed default LVM
  ptables: "{{
    [ 'Preseed default',
      'Preseed default LVM' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Debian') | map(attribute='name') | list )
    }}"

foreman_operatingsystems_debian10:
  - name: "Debian"
    major: "10"
    release_name: buster
    description: "Debian 10 (Buster)"
    default_templates: "{{ foreman_operatingsystems_debian10_default_templates | default( foreman_operatingsystems_debian_default_templates | default( foreman_operatingsystems_deb_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults

foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Debian
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"
  operatingsystems:
    - Debian 10 (Buster)

foreman_installation_media_debian10:
  - name: Debian 10 (Buster)
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Debian/debian-10/"
    <<: *foreman_installation_media_defaults

foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Debian"
  auto_attach: False

foreman_activation_keys_debian10:
  - name: ak_debian10
    organization: "{{ foreman_organization_debian10 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}debian10"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_Debian_debian-10"
        override: default
      - label: "{{ foreman_organization }}_Debian_debian-10-updates"
        override: default
      # - label: "{{ foreman_organization }}_Debian_debian-10-proposed-updates"
      #   override: default
      - label: "{{ foreman_organization }}_Debian_debian-10-backports"
        override: disabled
      # - label: "{{ foreman_organization }}_Debian_debian-10-backports-sloppy"
      #   override: disabled
      - label: "{{ foreman_organization }}_Debian_debian-10-security"
        override: disabled

