---
# defaults file for foreman_content_kubernetes

foreman_enable_kubernetes: false


# foreman_repo_baseurl_kubernetes: https://packages.cloud.google.com/yum

foreman_default_repo_baseurl_kubernetes: https://packages.cloud.google.com/yum


foreman_content_credentials_kubernetes:
  - name: RPM-GPG-KEY-kubernetes-pkg
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_kubernetes | default(foreman_default_repo_baseurl_kubernetes) ~ '/doc/rpm-package-key.gpg', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-kubernetes-pkg') }}"
  - name: RPM-GPG-KEY-kubernetes-yum
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_kubernetes | default(foreman_default_repo_baseurl_kubernetes) ~ '/doc/yum-key.gpg', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-kubernetes-yum') }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-kubernetes-pkg
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_kubernetes:
  - name: Kubernetes
    label: Kubernetes
    repositories:
      - name: Kubernetes - EL7
        label: kubernetes-el7
        url: "{{ foreman_repo_baseurl_kubernetes | default(foreman_default_repo_baseurl_kubernetes) }}/repos/kubernetes-el7-x86_64"
        <<: *foreman_products_defaults
      - name: Kubernetes Unstable - EL7
        label: kubernetes-unstable-el7
        url: "{{ foreman_repo_baseurl_kubernetes | default(foreman_default_repo_baseurl_kubernetes) }}/repos/kubernetes-el7-x86_64-unstable"
        <<: *foreman_products_defaults

foreman_content_views_kubernetes:
  - name: cv_kubernetes_el7
    repositories:
      - name: Kubernetes - EL7
        product: Kubernetes
    allow_promote: False
  - name: cv_kubernetes_unstable_el7
    repositories:
      - name: Kubernetes Unstable - EL7
        product: Kubernetes
    allow_promote: False

foreman_activation_keys_kubernetes: []

foreman_sync_plan_products_kubernetes:
  - Kubernetes

