---
# noqa: var-naming[no-role-prefix]

###############################################################################
### Connection details
###############################################################################
# foreman_username: admin
# foreman_password: password
# foreman_server_url: https://foreman.mycompany.com
# foreman_validate_certs: yes

###############################################################################
### Foreman Administer section
###############################################################################
foreman_organizations: []
foreman_locations: []
foreman_settings: []
foreman_auth_sources_ldap: []
foreman_roles: []
foreman_usergroups: []
foreman_users: []

# Additional vars that should be set
# foreman_all_organizations_namelist: "{{ foreman_organizations | map(attribute='name') | list }}"
# foreman_all_locations_namelist: "{{ foreman_locations | map(attribute='name') | list }}"


###############################################################################
### Foreman Infrastructure section
###############################################################################
foreman_domains: []
foreman_subnets: []
foreman_smart_proxies: []
foreman_compute_resources: []
foreman_compute_profiles: []

###############################################################################
### Foreman Content section
###############################################################################

### ======================================
### Content include selection
### ======================================

# Foreman content roles to include
foreman_content_roles: []
  # Package only content
  # - kangaroot.foreman_content_atix.foreman_content_atix
  # - kangaroot.foreman_content_ceph.foreman_content_ceph
  # - kangaroot.foreman_content_datadog.foreman_content_datadog
  # - kangaroot.foreman_content_docker.foreman_content_docker
  # - kangaroot.foreman_content_elrepo.foreman_content_elrepo
  # - kangaroot.foreman_content_epel.foreman_content_epel
  # - kangaroot.foreman_content_fedora_copr.foreman_content_fedora_copr
  # - kangaroot.foreman_content_foreman.foreman_content_foreman
  # - kangaroot.foreman_content_hashicorp.foreman_content_hashicorp
  # - kangaroot.foreman_content_kubernetes.foreman_content_kubernetes
  # - kangaroot.foreman_content_microsoft.foreman_content_microsoft
  # - kangaroot.foreman_content_nginx.foreman_content_nginx
  # - kangaroot.foreman_content_puppet.foreman_content_puppet
  # - kangaroot.foreman_content_remi.foreman_content_remi
  # OS content
  # - kangaroot.foreman_content_centos.foreman_content_centos
  # - kangaroot.foreman_content_debian.foreman_content_debian
  # - kangaroot.foreman_content_ol.foreman_content_ol
  # - kangaroot.foreman_content_redhat.foreman_content_redhat
  # - kangaroot.foreman_content_rocky.foreman_content_rocky
  # - kangaroot.foreman_content_ubuntu.foreman_content_ubuntu
  # Builtin content
  # - kangaroot.foreman_content_builtin.foreman_content_builtin

### ======================================
### Content publish, promote and cleanup
### ======================================

### Content publishing
foreman_publish_content: false
foreman_publish_content_view: ""
foreman_publish_content_views: []

### Content promoting
foreman_promote_content: false
foreman_promote_content_view: ""
foreman_promote_content_views: []
foreman_promote_lifecycle_environments: []

### Content Cleanup
foreman_cleanup_content: false
# Foreman convent view versions to keep at cleanup
foreman_content_view_version_cleanup_keep: 5

### ======================================
### Main content vars
### ======================================

# foreman_manifest_download: false
foreman_manifest_uuid: ""
foreman_rhsm_username: ""
foreman_rhsm_password: ""
foreman_manifest_path: ""
# foreman_manifest_state: present

foreman_lifecycle_environments: []
foreman_content_credentials: []
foreman_products: []
foreman_content_views: []
foreman_activation_keys: []
foreman_sync_plans: []

# foreman_cred_name_prefix: "{{ foreman_organization }}-"
# foreman_product_name_prefix: "{{ foreman_organization }} - "
# foreman_product_label_prefix: "{{ foreman_organization }}_"
# foreman_repo_name_prefix: "{{ foreman_organization }} - "
# foreman_repo_label_prefix: "{{ foreman_organization }}-"
# foreman_media_name_prefix: "{{ foreman_organization }} - "
# foreman_media_label_prefix: "{{ foreman_organization }}_"
# foreman_os_name_prefix: "{{ foreman_organization }} - "
# foreman_os_label_prefix: "{{ foreman_organization }}_"
# foreman_ak_name_prefix: "{{ foreman_organization }}_"
# foreman_cv_name_prefix: "{{ foreman_organization }}_"
# foreman_ccv_name_prefix: "{{ foreman_organization }}_"
# foreman_ptable_name_prefix: "{{ foreman_organization }} - "
# foreman_ptable_label_prefix: "{{ foreman_organization }}_"
# foreman_template_name_prefix: "{{ foreman_organization }} - "
# foreman_template_label_prefix: "{{ foreman_organization }}_"

### ======================================
### Product Defaults
### ======================================

foreman_products_defaults_download_policy: on_demand
foreman_products_defaults_mirroring_policy: mirror_complete
foreman_products_defaults_verify_ssl_on_sync: false
foreman_products_defaults_http_proxy_policy: global_default_http_proxy
foreman_products_defaults_unprotected: false
# foreman_products_defaults_deb_components: main contrib non-free
foreman_products_defaults_deb_components: main
foreman_products_defaults_deb_architectures: amd64

### ======================================
### Content View Defaults
### ======================================

foreman_cv_prefix: cv_
foreman_cv_allow_promote: false

foreman_ccv_prefix: ccv_
foreman_ccv_allow_promote: true
foreman_ccv_auto_publish: true

###############################################################################
### Hosts / Provisioning section
###############################################################################
foreman_hardware_models: []
foreman_architectures:
  - x86_64
  - i386
  - amd64
  - i686
foreman_installation_media: []
foreman_operatingsystems: []

### =====================================
### EL installation media defaults
### =====================================

foreman_installation_media_el_organizations: "{{ foreman_all_organizations_namelist | default([]) }}"
foreman_installation_media_el_locations: "{{ foreman_all_locations_namelist | default([]) }}"
foreman_installation_media_el_operatingsystems: "{{ foreman_operatingsystems | default([]) |
                                                    selectattr('os_family', 'defined') |
                                                    selectattr('os_family', '==', 'Redhat') |
                                                    map(attribute='description') |
                                                    list
                                                 }}"

### =====================================
### DEB installation media defaults
### =====================================

foreman_installation_media_deb_organizations: "{{ foreman_all_organizations_namelist | default([]) }}"
foreman_installation_media_deb_locations: "{{ foreman_all_locations_namelist | default([]) }}"
foreman_installation_media_deb_operatingsystems: "{{ foreman_operatingsystems | default([]) |
                                                     selectattr('os_family', 'defined') |
                                                     selectattr('os_family', '==', 'Debian') |
                                                     map(attribute='description') |
                                                     list
                                                  }}"

### =====================================
### EL operating system defaults
### =====================================

foreman_operatingsystems_el_architectures:
  - x86_64
foreman_operatingsystems_el_ptables: "{{
  [ 'Kickstart default',
    'Kickstart custom' ] |
    union(foreman_partition_tables | default([]) |
          selectattr('os_family', 'defined') |
          selectattr('os_family', '==', 'Redhat') |
          map(attribute='name') |
          list)
  }}"

### =====================================
### DEB operating system defaults
### =====================================

foreman_operatingsystems_deb_architectures:
  - amd64
foreman_operatingsystems_deb_ptables: "{{
  [ 'Preseed default',
    'Preseed default LVM',
    'Preseed default autoinstall' ] |
    union(foreman_partition_tables | default([]) |
          selectattr('os_family', 'defined') |
          selectattr('os_family', '==', 'Debian') |
          map(attribute='name') |
          list)
  }}"

### =====================================
### EL operating system default templates
### =====================================

foreman_operatingsystems_el_template_cloud_init: CloudInit default
foreman_operatingsystems_el_template_finish: Kickstart default finish
foreman_operatingsystems_el_template_host_init_config: Linux host_init_config default
foreman_operatingsystems_el_template_ipxe: Kickstart default iPXE
foreman_operatingsystems_el_template_provision: Kickstart default
foreman_operatingsystems_el_template_pxegrub: Kickstart default PXEGrub
foreman_operatingsystems_el_template_pxegrub2: Kickstart default PXEGrub2
foreman_operatingsystems_el_template_pxelinux: Kickstart default PXELinux
foreman_operatingsystems_el_template_user_data: Kickstart default user data

foreman_operatingsystems_el_default_templates:
  - template_kind: "cloud-init"
    provisioning_template: "{{ foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') }}"
  - template_kind: "finish"
    provisioning_template: "{{ foreman_operatingsystems_el_template_finish | default('Kickstart default finish') }}"
  - template_kind: "host_init_config"
    provisioning_template: "{{ foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') }}"
  - template_kind: "iPXE"
    provisioning_template: "{{ foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') }}"
  - template_kind: "provision"
    provisioning_template: "{{ foreman_operatingsystems_el_template_provision | default('Kickstart default') }}"
  - template_kind: "PXEGrub"
    provisioning_template: "{{ foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') }}"
  - template_kind: "PXEGrub2"
    provisioning_template: "{{ foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') }}"
  - template_kind: "PXELinux"
    provisioning_template: "{{ foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') }}"
  - template_kind: "user_data"
    provisioning_template: "{{ foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') }}"

### ======================================
### DEB operating system default templates
### ======================================

foreman_operatingsystems_deb_template_cloud_init: CloudInit default
foreman_operatingsystems_deb_template_finish: Preseed default finish
foreman_operatingsystems_deb_template_host_init_config: Linux host_init_config default
foreman_operatingsystems_deb_template_ipxe: Preseed default iPXE
foreman_operatingsystems_deb_template_provision: Preseed default
foreman_operatingsystems_deb_template_pxegrub2: Preseed default PXEGrub2
foreman_operatingsystems_deb_template_pxelinux: Preseed default PXELinux
foreman_operatingsystems_deb_template_user_data: Preseed default user data

foreman_operatingsystems_deb_default_templates:
  # - template_kind: "cloud-init"
  #   provisioning_template: "{{ foreman_operatingsystems_deb_template_cloud_init | default('CloudInit default') }}"
  - template_kind: "finish"
    provisioning_template: "{{ foreman_operatingsystems_deb_template_finish | default('Preseed default finish') }}"
  - template_kind: "host_init_config"
    provisioning_template: "{{ foreman_operatingsystems_deb_template_host_init_config | default('Linux host_init_config default') }}"
  # - template_kind: "iPXE"
  #   provisioning_template: "{{ foreman_operatingsystems_deb_template_ipxe | default('Preseed default iPXE') }}"
  - template_kind: "provision"
    provisioning_template: "{{ foreman_operatingsystems_deb_template_provision | default('Preseed default') }}"
  - template_kind: "PXEGrub2"
    provisioning_template: "{{ foreman_operatingsystems_deb_template_pxegrub2 | default('Preseed default PXEGrub2') }}"
  - template_kind: "PXELinux"
    provisioning_template: "{{ foreman_operatingsystems_deb_template_pxelinux | default('Preseed default PXELinux') }}"
  - template_kind: "user_data"
    provisioning_template: "{{ foreman_operatingsystems_deb_template_user_data | default('Preseed default user data') }}"

###############################################################################
### Foreman Configuration section
###############################################################################
foreman_global_parameters: []
foreman_hostgroups: []
