---
# defaults file for foreman

###############################################################################
### Connection details
###############################################################################
# foreman_username: admin
# foreman_password: password
# foreman_server_url: https://foreman.mycompany.com
# foreman_validate_certs: yes

###############################################################################
### Foreman Administer section
###############################################################################
foreman_organizations: []
foreman_locations: []
foreman_settings: []
foreman_auth_sources_ldap: []
foreman_roles: []
foreman_usergroups: []
foreman_users: []

###############################################################################
### Foreman Infrastructure section
###############################################################################
foreman_domains: []
foreman_subnets: []
foreman_smart_proxies: []
foreman_compute_resources: []
foreman_compute_profiles: []

###############################################################################
### Foreman Content section
###############################################################################
# foreman_manifest_download: false
foreman_manifest_uuid: ''
foreman_rhsm_username: ''
foreman_rhsm_password: ''
foreman_manifest_path: ''
# foreman_manifest_state: present
foreman_lifecycle_environments: []
foreman_content_credentials: []
foreman_products: []
foreman_content_views: []
foreman_activation_keys: []
foreman_sync_plans: []

# Foreman convent view versions to keep at cleanup
foreman_content_view_version_cleanup_keep: 5


###############################################################################
### Hosts / Provisioning section
###############################################################################
foreman_hardware_models: []
foreman_architectures: []
foreman_installation_media: []
foreman_operatingsystems: []

### =====================================
### EL operating system default templates
### =====================================

foreman_operatingsystems_el_template_cloud_init: CloudInit default
foreman_operatingsystems_el_template_host_init_config: Linux host_init_config default
foreman_operatingsystems_el_template_finish: Kickstart default finish
foreman_operatingsystems_el_template_ipxe: Kickstart default iPXE
foreman_operatingsystems_el_template_provision: Kickstart default
foreman_operatingsystems_el_template_pxegrub: Kickstart default PXEGrub
foreman_operatingsystems_el_template_pxegrub2: Kickstart default PXEGrub2
foreman_operatingsystems_el_template_pxelinux: Kickstart default PXELinux
foreman_operatingsystems_el_template_user_data: Kickstart default user data

### ======================================
### DEB operating system default templates
### ======================================

# foreman_operatingsystems_deb_template_cloud_init: CloudInit default
# foreman_operatingsystems_deb_template_host_init_config: Linux host_init_config default
foreman_operatingsystems_deb_template_finish: Preseed default finish
# foreman_operatingsystems_deb_template_ipxe: Preseed default iPXE
foreman_operatingsystems_deb_template_provision: Preseed default
# foreman_operatingsystems_deb_template_pxegrub: Preseed default PXEGrub
foreman_operatingsystems_deb_template_pxegrub2: Preseed default PXEGrub2
foreman_operatingsystems_deb_template_pxelinux: Preseed default PXELinux
foreman_operatingsystems_deb_template_user_data: Preseed default user data

###############################################################################
### Foreman Configuration section
###############################################################################
foreman_global_parameters: []

