---
# foreman docker ce content vars file for foreman_content_docker

foreman_content_credentials_docker_ce_el7: []

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-docker-ce
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: false
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_docker_ce_el7:
  - name: Docker
    label: Docker
    repositories:
      - name: Docker CE Stable - x86_64 - EL7
        label: docker-ce-stable-el7
        url: "{{ foreman_repo_baseurl_docker_ce }}/7/x86_64/stable"
        <<: *foreman_products_defaults

foreman_content_views_docker_ce_el7:
  - name: cv_docker_ce_stable_el7
    repositories:
      - name: Docker CE Stable - x86_64 - EL7
        product: Docker
    allow_promote: False

foreman_activation_keys_docker_ce_el7: []

foreman_sync_plan_products_docker_ce_el7: []

