---

foreman_content_credentials_docker_ce_main:
  - name: RPM-GPG-KEY-docker-ce
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_docker_ce ~ '/gpg', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-docker-ce') }}"

foreman_content_credentials_docker_ce: "{{ ( foreman_content_credentials_docker_ce_main | default([]) if foreman_enable_docker_ce | bool else [] ) |
  union( foreman_content_credentials_docker_ce_el7 | default([]) if foreman_enable_docker_ce_el7 | bool else [] ) |
  union( foreman_content_credentials_docker_ce_el8 | default([]) if foreman_enable_docker_ce_el8 | bool else [] ) |
  union( foreman_content_credentials_docker_ce_el9 | default([]) if foreman_enable_docker_ce_el9 | bool else [] )
  }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-docker-ce
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: false
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_docker_ce_el7:
  - name: Docker
    label: Docker
    organization: "{{ foreman_organization_docker_ce_el7 }}"
    repositories:
      - name: Docker CE Stable - x86_64 - EL7
        label: docker-ce-stable-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_docker_ce }}/7/x86_64/stable"
        organization: "{{ foreman_organization_docker_ce_el7 }}"

foreman_products_docker_ce_el8:
  - name: Docker
    label: Docker
    organization: "{{ foreman_organization_docker_ce_el8 }}"
    repositories:
      - name: Docker CE Stable - x86_64 - EL8
        label: docker-ce-stable-el8
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_docker_ce }}/8/x86_64/stable"
        organization: "{{ foreman_organization_docker_ce_el8 }}"

foreman_products_docker_ce_el9:
  - name: Docker
    label: Docker
    organization: "{{ foreman_organization_docker_ce_el9 }}"
    repositories:
      - name: Docker CE Stable - x86_64 - EL9
        label: docker-ce-stable-el9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_docker_ce }}/9/x86_64/stable"
        organization: "{{ foreman_organization_docker_ce_el9 }}"

foreman_products_docker_ce_main: []
foreman_products_docker_ce: "{{ ( foreman_products_docker_ce_main | default([]) if foreman_enable_docker_ce | bool else [] ) |
  union( foreman_products_docker_ce_el7 | default([]) if foreman_enable_docker_ce_el7 | bool else [] ) |
  union( foreman_products_docker_ce_el8 | default([]) if foreman_enable_docker_ce_el8 | bool else [] ) |
  union( foreman_products_docker_ce_el9 | default([]) if foreman_enable_docker_ce_el9 | bool else [] )
  }}"

foreman_content_views_docker_ce_el7:
  - name: cv_docker_ce_stable_el7
    organization: "{{ foreman_organization_docker_ce_el7 }}"
    repositories:
      - name: Docker CE Stable - x86_64 - EL7
        product: Docker
    allow_promote: False

foreman_content_views_docker_ce_el8:
  - name: cv_docker_ce_stable_el8
    organization: "{{ foreman_organization_docker_ce_el8 }}"
    repositories:
      - name: Docker CE Stable - x86_64 - EL8
        product: Docker
    allow_promote: False

foreman_content_views_docker_ce_el9:
  - name: cv_docker_ce_stable_el9
    organization: "{{ foreman_organization_docker_ce_el9 }}"
    repositories:
      - name: Docker CE Stable - x86_64 - EL9
        product: Docker
    allow_promote: False

foreman_content_views_docker_ce_main: []
foreman_content_views_docker_ce: "{{ ( foreman_content_views_docker_ce_main | default([]) if foreman_enable_docker_ce | bool else [] ) |
  union( foreman_content_views_docker_ce_el7 | default([]) if foreman_enable_docker_ce_el7 | bool else [] ) |
  union( foreman_content_views_docker_ce_el8 | default([]) if foreman_enable_docker_ce_el8 | bool else [] ) |
  union( foreman_content_views_docker_ce_el9 | default([]) if foreman_enable_docker_ce_el9 | bool else [] )
  }}"

foreman_activation_keys_docker_ce_main: []
foreman_activation_keys_docker_ce: "{{ ( foreman_activation_keys_docker_ce_main | default([]) if foreman_enable_docker_ce | bool else [] ) |
  union( foreman_activation_keys_docker_ce_el7 | default([]) if foreman_enable_docker_ce_el7 | bool else [] ) |
  union( foreman_activation_keys_docker_ce_el8 | default([]) if foreman_enable_docker_ce_el8 | bool else [] ) |
  union( foreman_activation_keys_docker_ce_el9 | default([]) if foreman_enable_docker_ce_el9 | bool else [] )
  }}"

foreman_sync_plan_products_docker_ce_main: []
foreman_sync_plan_products_docker_ce: "{{ ( foreman_sync_plan_products_docker_ce_main | default([]) if foreman_enable_docker_ce | bool else [] ) |
  union( foreman_sync_plan_products_docker_ce_el7 | default([]) if foreman_enable_docker_ce_el7 | bool else [] ) |
  union( foreman_sync_plan_products_docker_ce_el8 | default([]) if foreman_enable_docker_ce_el8 | bool else [] ) |
  union( foreman_sync_plan_products_docker_ce_el9 | default([]) if foreman_enable_docker_ce_el9 | bool else [] )
  }}"

