---
# defaults file for foreman_content_epel

foreman_enable_epel: false
foreman_enable_epel_el7: false
foreman_enable_epel_el8: "{{ foreman_enable_epel | bool }}"
foreman_enable_epel_el9: "{{ foreman_enable_epel | bool }}"


foreman_repo_baseurl_epel: https://dl.fedoraproject.org/pub/epel


foreman_content_credentials_epel_main: []
foreman_content_credentials_epel: "{{ foreman_content_credentials_epel_main | default([]) if foreman_enable_epel | bool else [] |
  union( foreman_content_credentials_epel_el7 | default([]) if foreman_enable_epel_el7 | bool else [] ) |
  union( foreman_content_credentials_epel_el8 | default([]) if foreman_enable_epel_el8 | bool else [] ) |
  union( foreman_content_credentials_epel_el9 | default([]) if foreman_enable_epel_el9 | bool else [] )
  }}"

foreman_products_epel_main: []
foreman_products_epel: "{{ foreman_products_epel_main | default([]) if foreman_enable_epel | bool else [] |
  union( foreman_products_epel_el7 | default([]) if foreman_enable_epel_el7 | bool else [] ) |
  union( foreman_products_epel_el8 | default([]) if foreman_enable_epel_el8 | bool else [] ) |
  union( foreman_products_epel_el9 | default([]) if foreman_enable_epel_el9 | bool else [] )
  }}"

foreman_content_views_epel_main: []
foreman_content_views_epel: "{{ foreman_content_views_epel_main | default([]) if foreman_enable_epel | bool else [] |
  union( foreman_content_views_epel_el7 | default([]) if foreman_enable_epel_el7 | bool else [] ) |
  union( foreman_content_views_epel_el8 | default([]) if foreman_enable_epel_el8 | bool else [] ) |
  union( foreman_content_views_epel_el9 | default([]) if foreman_enable_epel_el9 | bool else [] )
  }}"

foreman_operatingsystems_epel_main: []
foreman_operatingsystems_epel: "{{ foreman_operatingsystems_epel_main | default([]) if foreman_enable_epel | bool else [] |
  union( foreman_operatingsystems_epel_el7 | default([]) if foreman_enable_epel_el7 | bool else [] ) |
  union( foreman_operatingsystems_epel_el8 | default([]) if foreman_enable_epel_el8 | bool else [] ) |
  union( foreman_operatingsystems_epel_el9 | default([]) if foreman_enable_epel_el9 | bool else [] )
  }}"

foreman_installation_media_epel_main: []
foreman_installation_media_epel: "{{ foreman_installation_media_epel_main | default([]) if foreman_enable_epel | bool else [] |
  union( foreman_installation_media_epel_el7 | default([]) if foreman_enable_epel_el7 | bool else [] ) |
  union( foreman_installation_media_epel_el8 | default([]) if foreman_enable_epel_el8 | bool else [] ) |
  union( foreman_installation_media_epel_el9 | default([]) if foreman_enable_epel_el9 | bool else [] )
  }}"

foreman_activation_keys_epel_main: []
foreman_activation_keys_epel: "{{ foreman_activation_keys_epel_main | default([]) if foreman_enable_epel | bool else [] |
  union( foreman_activation_keys_epel_el7 | default([]) if foreman_enable_epel_el7 | bool else [] ) |
  union( foreman_activation_keys_epel_el8 | default([]) if foreman_enable_epel_el8 | bool else [] ) |
  union( foreman_activation_keys_epel_el9 | default([]) if foreman_enable_epel_el9 | bool else [] )
  }}"

foreman_sync_plan_products_epel_main:
  - Extra Packages for Enterprise Linux

foreman_sync_plan_products_epel: "{{ foreman_sync_plan_products_epel_main | default([]) if foreman_enable_epel | bool else [] |
  union( foreman_sync_plan_products_epel_el7 | default([]) if foreman_enable_epel_el7 | bool else [] ) |
  union( foreman_sync_plan_products_epel_el8 | default([]) if foreman_enable_epel_el8 | bool else [] ) |
  union( foreman_sync_plan_products_epel_el9 | default([]) if foreman_enable_epel_el9 | bool else [] )
  }}"

