---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Datadog
  download_policy: "{{ foreman_products_defaults_download_policy_datadog }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_datadog }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_datadog | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_datadog }}"
  unprotected: "{{ foreman_products_defaults_unprotected_datadog | bool }}"


foreman_products_datadog_v6:
  - name: Datadog
    label: Datadog
    organization: "{{ foreman_organization_datadog_v6 }}"
    repositories:
      - name: Datadog Agent v6
        label: datadog-v6
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_datadog }}/stable/6/x86_64/"
        organization: "{{ foreman_organization_datadog_v6 }}"

foreman_products_datadog_v7:
  - name: Datadog
    label: Datadog
    organization: "{{ foreman_organization_datadog_v7 }}"
    repositories:
      - name: Datadog Agent v7
        label: datadog-v7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_datadog }}/stable/7/x86_64/"
        organization: "{{ foreman_organization_datadog_v7 }}"

foreman_content_views_datadog_v6:
  - name: "{{ foreman_cv_prefix | default('cv_') }}datadog_v6"
    organization: "{{ foreman_organization_datadog_v6 }}"
    repositories:
      - name: Datadog Agent v6
        product: Datadog
    allow_promote: "{{ foreman_cv_allow_promote_datadog_v6 }}"

foreman_content_views_datadog_v7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}datadog_v7"
    organization: "{{ foreman_organization_datadog_v7 }}"
    repositories:
      - name: Datadog Agent v7
        product: Datadog
    allow_promote: "{{ foreman_cv_allow_promote_datadog_v7 }}"

