---
# foreman docker ee content group vars file for katello-main

foreman_content_credentials_docker_ee_el7: []

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-docker-ee
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_docker_ee_el7:
  - name: Docker
    label: Docker
    repositories:
      - name: Docker EE Stable - x86_64 - RHEL7
        label: docker-ee-stable-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable/"
        <<: *foreman_products_defaults

      - name: Docker EE Stable 17.03 - x86_64 - RHEL7
        label: docker-ee-stable-17_03-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-17.03/"
        <<: *foreman_products_defaults

      - name: Docker EE Stable 17.06 - x86_64 - RHEL7
        label: docker-ee-stable-17_06-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-17.06/"
        <<: *foreman_products_defaults

      - name: Docker EE Stable 18.03 - x86_64 - RHEL7
        label: docker-ee-stable-18_03-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-18.03/"
        <<: *foreman_products_defaults

      - name: Docker EE Stable 18.09 - x86_64 - RHEL7
        label: docker-ee-stable-18_09-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-18.09/"
        <<: *foreman_products_defaults

      - name: Docker EE Stable 19.03 - x86_64 - RHEL7
        label: docker-ee-stable-19_03-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-19.03/"
        <<: *foreman_products_defaults

      - name: Docker EE Stable 20.10 - x86_64 - RHEL7
        label: docker-ee-stable-20_10-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-20.10/"
        <<: *foreman_products_defaults

      - name: Docker EE Stable 23.0 - x86_64 - RHEL7
        label: docker-ee-stable-23_0-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-23.0/"
        <<: *foreman_products_defaults

foreman_content_views_docker_ee_el7:
  - name: cv_docker_ee_stable_rhel7
    repositories:
      - name: Docker EE Stable - x86_64 - RHEL7
        product: Docker
    allow_promote: False

  - name: cv_docker_ee_stable_17_03_rhel7
    repositories:
      - name: Docker EE Stable 17.03 - x86_64 - RHEL7
        product: Docker
    allow_promote: False

  - name: cv_docker_ee_stable_17_06_rhel7
    repositories:
      - name: Docker EE Stable 17.06 - x86_64 - RHEL7
        product: Docker
    allow_promote: False

  - name: cv_docker_ee_stable_18_03_rhel7
    repositories:
      - name: Docker EE Stable 18.03 - x86_64 - RHEL7
        product: Docker
    allow_promote: False

  - name: cv_docker_ee_stable_18_09_rhel7
    repositories:
      - name: Docker EE Stable 18.09 - x86_64 - RHEL7
        product: Docker
    allow_promote: False

  - name: cv_docker_ee_stable_19_03_rhel7
    repositories:
      - name: Docker EE Stable 19.03 - x86_64 - RHEL7
        product: Docker
    allow_promote: False

  - name: cv_docker_ee_stable_20_10_rhel7
    repositories:
      - name: Docker EE Stable 20.10 - x86_64 - RHEL7
        product: Docker
    allow_promote: False

  - name: cv_docker_ee_stable_23_0_rhel7
    repositories:
      - name: Docker EE Stable 23.0 - x86_64 - RHEL7
        product: Docker
    allow_promote: False

foreman_activation_keys_docker_ee_el7: []

foreman_sync_plan_products_docker_ee_el7: []

