---
# foreman docker ee content group vars file for katello-main

foreman_content_credentials_docker_ee:
  - name: RPM-GPG-KEY-docker-ee
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) ~ '/rhel/gpg', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', ansible_parent_role_paths[0] | default(role_path) ~ '/files/RPM-GPG-KEY-docker-ee') }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-docker-ee
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_docker_ee:
  - name: Docker
    label: Docker
    repositories:
      - name: Docker EE Stable - x86_64 - RHEL7
        label: docker-ee-stable-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable/"
        <<: *foreman_products_defaults
      # - name: Docker EE Stable - Debuginfo x86_64 - RHEL7
      #   label: docker-ee-stable-debuginfo-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/debug-x86_64/stable/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Stable - Sources - RHEL7
      #   label: docker-ee-stable-source-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/source/stable/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test - x86_64 - RHEL7
      #   label: docker-ee-test-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/test/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test - Debuginfo x86_64 - RHEL7
      #   label: docker-ee-test-debuginfo-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/debug-x86_64/test/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test - Sources - RHEL7
      #   label: docker-ee-test-source-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/source/test/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 17.03 - x86_64 - RHEL7
        label: docker-ee-stable-17_03-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-17.03/"
        <<: *foreman_products_defaults
      # - name: Docker EE Stable 17.03 - Debuginfo x86_64 - RHEL7
      #   label: docker-ee-stable-17_03-debuginfo-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/debug-x86_64/stable-17.03/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Stable 17.03 - Sources - RHEL7
      #   label: docker-ee-stable-17_03-source-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/source/stable-17.03/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test 17.03 - x86_64 - RHEL7
      #   label: docker-ee-test-17_03-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/test-17.03/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test 17.03 - Debuginfo x86_64 - RHEL7
      #   label: docker-ee-test-17_03-debuginfo-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/debug-x86_64/test-17.03/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test 17.03 - Sources - RHEL7
      #   label: docker-ee-test-17_03-source-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/source/test-17.03/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 17.06 - x86_64 - RHEL7
        label: docker-ee-stable-17_06-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-17.06/"
        <<: *foreman_products_defaults
      # - name: Docker EE Stable 17.06 - Debuginfo x86_64 - RHEL7
      #   label: docker-ee-stable-17_06-debuginfo-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/debug-x86_64/stable-17.06/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Stable 17.06 - Sources - RHEL7
      #   label: docker-ee-stable-17_06-source-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/source/stable-17.06/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test 17.06 - x86_64 - RHEL7
      #   label: docker-ee-test-17_06-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/test-17.06/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test 17.06 - Debuginfo x86_64 - RHEL7
      #   label: docker-ee-test-17_06-debuginfo-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/debug-x86_64/test-17.06/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test 17.06 - Sources - RHEL7
      #   label: docker-ee-test-17_06-source-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/source/test-17.06/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 18.03 - x86_64 - RHEL7
        label: docker-ee-stable-18_03-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-18.03/"
        <<: *foreman_products_defaults
      # - name: Docker EE Test 18.03 - x86_64 - RHEL7
      #   label: docker-ee-test-18_03-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/test-18.03/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 18.09 - x86_64 - RHEL7
        label: docker-ee-stable-18_09-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-18.09/"
        <<: *foreman_products_defaults
      # - name: Docker EE Test 18.09 - x86_64 - RHEL7
      #   label: docker-ee-test-18_09-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/test-18.09/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 19.03 - x86_64 - RHEL7
        label: docker-ee-stable-19_03-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-19.03/"
        <<: *foreman_products_defaults
      # - name: Docker EE Test 19.03 - x86_64 - RHEL7
      #   label: docker-ee-test-19_03-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/test-19.03/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 20.10 - x86_64 - RHEL7
        label: docker-ee-stable-20_10-rhel7
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/stable-20.10/"
        <<: *foreman_products_defaults
      # - name: Docker EE Test 20.10 - x86_64 - RHEL7
      #   label: docker-ee-test-20_10-rhel7
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/7/x86_64/test-20.10/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable - x86_64 - RHEL8
        label: docker-ee-stable-rhel8
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/x86_64/stable/"
        <<: *foreman_products_defaults
      # - name: Docker EE Stable - Debuginfo x86_64 - RHEL8
      #   label: docker-ee-stable-debuginfo-rhel8
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/debug-x86_64/stable/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Stable - Sources - RHEL8
      #   label: docker-ee-stable-source-rhel8
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/source/stable/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test - x86_64 - RHEL8
      #   label: docker-ee-test-rhel8
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/x86_64/test/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test - Debuginfo x86_64 - RHEL8
      #   label: docker-ee-test-debuginfo-rhel8
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/debug-x86_64/test/"
      #   <<: *foreman_products_defaults
      # - name: Docker EE Test - Sources - RHEL8
      #   label: docker-ee-test-source-rhel8
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/source/test/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 18.09 - x86_64 - RHEL8
        label: docker-ee-stable-18_09-rhel8
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/x86_64/stable-18.09/"
        <<: *foreman_products_defaults
      # - name: Docker EE Test 18.09 - x86_64 - RHEL8
      #   label: docker-ee-test-18_09-rhel8
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/x86_64/test-18.09/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 19.03 - x86_64 - RHEL8
        label: docker-ee-stable-19_03-rhel8
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/x86_64/stable-19.03/"
        <<: *foreman_products_defaults
      # - name: Docker EE Test 19.03 - x86_64 - RHEL8
      #   label: docker-ee-test-19_03-rhel8
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/x86_64/test-19.03/"
      #   <<: *foreman_products_defaults

      - name: Docker EE Stable 20.10 - x86_64 - RHEL8
        label: docker-ee-stable-20_10-rhel8
        url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/x86_64/stable-20.10/"
        <<: *foreman_products_defaults
      # - name: Docker EE Test 20.10 - x86_64 - RHEL8
      #   label: docker-ee-test-20_10-rhel8
      #   url: "{{ foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) }}/rhel/8/x86_64/test-20.10/"
      #   <<: *foreman_products_defaults

foreman_content_views_docker_ee:
  - name: cv_docker_ee_stable_rhel7
    repositories:
      - name: Docker EE Stable - x86_64 - RHEL7
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_stable_debuginfo_rhel7
  #   repositories:
  #     - name: Docker EE Stable - Debuginfo x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_stable_source_rhel7
  #   repositories:
  #     - name: Docker EE Stable - Sources - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_rhel7
  #   repositories:
  #     - name: Docker EE Test - x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_debuginfo_rhel7
  #   repositories:
  #     - name: Docker EE Test - Debuginfo x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_source_rhel7
  #   repositories:
  #     - name: Docker EE Test - Sources - RHEL7
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_17_03_rhel7
    repositories:
      - name: Docker EE Stable 17.03 - x86_64 - RHEL7
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_stable_17_03_debuginfo_rhel7
  #   repositories:
  #     - name: Docker EE Stable 17.03 - Debuginfo x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_stable_17_03_source_rhel7
  #   repositories:
  #     - name: Docker EE Stable 17.03 - Sources - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_17_03_rhel7
  #   repositories:
  #     - name: Docker EE Test 17.03 - x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_17_03_debuginfo_rhel7
  #   repositories:
  #     - name: Docker EE Test 17.03 - Debuginfo x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_17_03_source_rhel7
  #   repositories:
  #     - name: Docker EE Test 17.03 - Sources - RHEL7
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_17_06_rhel7
    repositories:
      - name: Docker EE Stable 17.06 - x86_64 - RHEL7
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_stable_17_06_debuginfo_rhel7
  #   repositories:
  #     - name: Docker EE Stable 17.06 - Debuginfo x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_stable_17_06_source_rhel7
  #   repositories:
  #     - name: Docker EE Stable 17.06 - Sources - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_17_06_rhel7
  #   repositories:
  #     - name: Docker EE Test 17.06 - x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_17_06_debuginfo_rhel7
  #   repositories:
  #     - name: Docker EE Test 17.06 - Debuginfo x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_17_06_source_rhel7
  #   repositories:
  #     - name: Docker EE Test 17.06 - Sources - RHEL7
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_18_03_rhel7
    repositories:
      - name: Docker EE Stable 18.03 - x86_64 - RHEL7
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_test_18_03_rhel7
  #   repositories:
  #     - name: Docker EE Test 18.03 - x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_18_09_rhel7
    repositories:
      - name: Docker EE Stable 18.09 - x86_64 - RHEL7
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_test_18_09_rhel7
  #   repositories:
  #     - name: Docker EE Test 18.09 - x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_19_03_rhel7
    repositories:
      - name: Docker EE Stable 19.03 - x86_64 - RHEL7
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_test_19_03_rhel7
  #   repositories:
  #     - name: Docker EE Test 19.03 - x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_20_10_rhel7
    repositories:
      - name: Docker EE Stable 20.10 - x86_64 - RHEL7
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_test_20_10_rhel7
  #   repositories:
  #     - name: Docker EE Test 20.10 - x86_64 - RHEL7
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_rhel8
    repositories:
      - name: Docker EE Stable - x86_64 - RHEL8
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_stable_debuginfo_rhel8
  #   repositories:
  #     - name: Docker EE Stable - Debuginfo x86_64 - RHEL8
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_stable_source_rhel8
  #   repositories:
  #     - name: Docker EE Stable - Sources - RHEL8
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_rhel8
  #   repositories:
  #     - name: Docker EE Test - x86_64 - RHEL8
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_debuginfo_rhel8
  #   repositories:
  #     - name: Docker EE Test - Debuginfo x86_64 - RHEL8
  #       product: Docker
  #   allow_promote: False
  # - name: cv_docker_ee_test_source_rhel8
  #   repositories:
  #     - name: Docker EE Test - Sources - RHEL8
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_18_09_rhel8
    repositories:
      - name: Docker EE Stable 18.09 - x86_64 - RHEL8
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_test_18_09_rhel8
  #   repositories:
  #     - name: Docker EE Test 18.09 - x86_64 - RHEL8
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_19_03_rhel8
    repositories:
      - name: Docker EE Stable 19.03 - x86_64 - RHEL8
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_test_19_03_rhel8
  #   repositories:
  #     - name: Docker EE Test 19.03 - x86_64 - RHEL8
  #       product: Docker
  #   allow_promote: False

  - name: cv_docker_ee_stable_20_10_rhel8
    repositories:
      - name: Docker EE Stable 20.10 - x86_64 - RHEL8
        product: Docker
    allow_promote: False
  # - name: cv_docker_ee_test_20_10_rhel8
  #   repositories:
  #     - name: Docker EE Test 20.10 - x86_64 - RHEL8
  #       product: Docker
  #   allow_promote: False

foreman_activation_keys_docker_ee: []

foreman_sync_plan_products_docker_ee:
  - Docker

