---
# foreman docker ee content group vars file for katello-main

foreman_content_credentials_docker_ee_main:
  - name: RPM-GPG-KEY-docker-ee
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_docker_ee | default(foreman_default_repo_baseurl_docker_ee) ~ '/rhel/gpg', split_lines=False, validate_eerts=False) }}"
    # content: "{{ lookup('ansible.builtin.file', ansible_parent_role_paths[0] | default(role_path) ~ '/files/RPM-GPG-KEY-docker-ee') }}"

foreman_content_credentials_docker_ee: "{{ ( foreman_content_credentials_docker_ee_main | default([]) if foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool else [] ) |
  union( foreman_content_credentials_docker_ee_el7 | default([]) if foreman_enable_docker_ee_el7 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_content_credentials_docker_ee_el8 | default([]) if foreman_enable_docker_ee_el8 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_content_credentials_docker_ee_el9 | default([]) if foreman_enable_docker_ee_el9 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] )
  }}"

foreman_products_docker_ee_main: []
foreman_products_docker_ee: "{{ ( foreman_products_docker_ee_main | default([]) if foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool else [] ) |
  union( foreman_products_docker_ee_el7 | default([]) if foreman_enable_docker_ee_el7 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_products_docker_ee_el8 | default([]) if foreman_enable_docker_ee_el8 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_products_docker_ee_el9 | default([]) if foreman_enable_docker_ee_el9 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] )
  }}"

foreman_content_views_docker_ee_main: []
foreman_content_views_docker_ee: "{{ ( foreman_content_views_docker_ee_main | default([]) if foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool else [] ) |
  union( foreman_content_views_docker_ee_el7 | default([]) if foreman_enable_docker_ee_el7 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_content_views_docker_ee_el8 | default([]) if foreman_enable_docker_ee_el8 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_content_views_docker_ee_el9 | default([]) if foreman_enable_docker_ee_el9 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] )
  }}"

foreman_activation_keys_docker_ee_main: []
foreman_activation_keys_docker_ee: "{{ ( foreman_activation_keys_docker_ee_main | default([]) if foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool else [] ) |
  union( foreman_activation_keys_docker_ee_el7 | default([]) if foreman_enable_docker_ee_el7 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_activation_keys_docker_ee_el8 | default([]) if foreman_enable_docker_ee_el8 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_activation_keys_docker_ee_el9 | default([]) if foreman_enable_docker_ee_el9 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] )
  }}"

foreman_sync_plan_products_docker_ee_main:
  - Docker

foreman_sync_plan_products_docker_ee: "{{ ( foreman_sync_plan_products_docker_ee_main | default([]) if foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool else [] ) |
  union( foreman_sync_plan_products_docker_ee_el7 | default([]) if foreman_enable_docker_ee_el7 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_sync_plan_products_docker_ee_el8 | default([]) if foreman_enable_docker_ee_el8 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] ) |
  union( foreman_sync_plan_products_docker_ee_el9 | default([]) if foreman_enable_docker_ee_el9 | default( foreman_enable_docker_ee | default( foreman_enable_docker | default(false) | bool ) | bool ) | bool else [] )
  }}"

