---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Hashicorp
  download_policy: "{{ foreman_products_defaults_download_policy_hashicorp }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_hashicorp }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_hashicorp | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_hashicorp }}"
  unprotected: "{{ foreman_products_defaults_unprotected_hashicorp | bool }}"


foreman_products_hashicorp_el8:
  - name: Hashicorp
    label: Hashicorp
    organization: "{{ foreman_organization_hashicorp_el8 }}"
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 8
        label: hashicorp-el8
        url: "{{ foreman_repo_baseurl_hashicorp }}/RHEL/8/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_el8 }}"

foreman_products_hashicorp_el7:
  - name: Hashicorp
    label: Hashicorp
    organization: "{{ foreman_organization_hashicorp_el7 }}"
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 7
        label: hashicorp-el7
        url: "{{ foreman_repo_baseurl_hashicorp }}/RHEL/7/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_el7 }}"

foreman_products_hashicorp_el9:
  - name: Hashicorp
    label: Hashicorp
    organization: "{{ foreman_organization_hashicorp_el9 }}"
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 9
        label: hashicorp-el9
        url: "{{ foreman_repo_baseurl_hashicorp }}/RHEL/9/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_el9 }}"


foreman_content_views_hashicorp_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}hashicorp_el7"
    organization: "{{ foreman_organization_hashicorp_el7 }}"
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 7
        product: Hashicorp
    allow_promote: False

foreman_content_views_hashicorp_el8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}hashicorp_el8"
    organization: "{{ foreman_organization_hashicorp_el8 }}"
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 8
        product: Hashicorp
    allow_promote: False

foreman_content_views_hashicorp_el9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}hashicorp_el9"
    organization: "{{ foreman_organization_hashicorp_el9 }}"
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 9
        product: Hashicorp
    allow_promote: False


