---
# foreman hashicorp vars file for foreman_content_hashicorp

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Hashicorp
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_hashicorp_el8:
  - name: Hashicorp
    label: Hashicorp
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 8
        label: hashicorp-el8
        url: "{{ foreman_repo_baseurl_hashicorp | default(foreman_default_repo_baseurl_hashicorp) }}/RHEL/8/x86_64/stable"
        <<: *foreman_products_defaults

foreman_products_hashicorp_el7:
  - name: Hashicorp
    label: Hashicorp
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 7
        label: hashicorp-el7
        url: "{{ foreman_repo_baseurl_hashicorp | default(foreman_default_repo_baseurl_hashicorp) }}/RHEL/7/x86_64/stable"
        <<: *foreman_products_defaults

foreman_products_hashicorp_el9:
  - name: Hashicorp
    label: Hashicorp
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 9
        label: hashicorp-el9
        url: "{{ foreman_repo_baseurl_hashicorp | default(foreman_default_repo_baseurl_hashicorp) }}/RHEL/9/x86_64/stable"
        <<: *foreman_products_defaults


foreman_content_views_hashicorp_el7:
  - name: cv_hashicorp_el7
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 7
        product: Hashicorp
    allow_promote: False

foreman_content_views_hashicorp_el8:
  - name: cv_hashicorp_el8
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 8
        product: Hashicorp
    allow_promote: False

foreman_content_views_hashicorp_el9:
  - name: cv_hashicorp_el9
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 9
        product: Hashicorp
    allow_promote: False


