---
# foreman nginx content vars file for foreman_content_nginx

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-nginx
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_nginx_el7:
  - name: Nginx
    label: Nginx
    repositories:
      - name: nginx stable repo - EL7
        label: nginx-stable-el7
        url: "{{ foreman_repo_baseurl_nginx | default(foreman_default_repo_baseurl_nginx) }}/rhel/7/x86_64/"
        <<: *foreman_products_defaults
      - name: nginx mainline repo - EL7
        label: nginx-mainline-el7
        url: "{{ foreman_repo_baseurl_nginx | default(foreman_default_repo_baseurl_nginx) }}/mainline/rhel/7/x86_64/"
        <<: *foreman_products_defaults

foreman_products_nginx_el8:
  - name: Nginx
    label: Nginx
    repositories:
      - name: nginx stable repo - EL8
        label: nginx-stable-el8
        url: "{{ foreman_repo_baseurl_nginx | default(foreman_default_repo_baseurl_nginx) }}/rhel/8/x86_64/"
        <<: *foreman_products_defaults
      - name: nginx mainline repo - EL8
        label: nginx-mainline-el8
        url: "{{ foreman_repo_baseurl_nginx | default(foreman_default_repo_baseurl_nginx) }}/mainline/rhel/8/x86_64/"
        <<: *foreman_products_defaults

foreman_products_nginx_el9:
  - name: Nginx
    label: Nginx
    repositories:
      - name: nginx stable repo - EL9
        label: nginx-stable-el9
        url: "{{ foreman_repo_baseurl_nginx | default(foreman_default_repo_baseurl_nginx) }}/rhel/9/x86_64/"
        <<: *foreman_products_defaults
      - name: nginx mainline repo - EL9
        label: nginx-mainline-el9
        url: "{{ foreman_repo_baseurl_nginx | default(foreman_default_repo_baseurl_nginx) }}/mainline/rhel/9/x86_64/"
        <<: *foreman_products_defaults

foreman_content_views_nginx_el7:
  - name: cv_nginx_stable_el7
    repositories:
      - name: nginx stable repo - EL7
        product: Nginx
    allow_promote: False
  - name: cv_nginx_mainline_el7
    repositories:
      - name: nginx mainline repo - EL7
        product: Nginx
    allow_promote: False

foreman_content_views_nginx_el8:
  - name: cv_nginx_stable_el8
    repositories:
      - name: nginx stable repo - EL8
        product: Nginx
    allow_promote: False
  - name: cv_nginx_mainline_el8
    repositories:
      - name: nginx mainline repo - EL8
        product: Nginx
    allow_promote: False

foreman_content_views_nginx_el9:
  - name: cv_nginx_stable_el9
    repositories:
      - name: nginx stable repo - EL9
        product: Nginx
    allow_promote: False
  - name: cv_nginx_mainline_el9
    repositories:
      - name: nginx mainline repo - EL9
        product: Nginx
    allow_promote: False

