---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol8_olm:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol8_olm }}"
    repositories:
      ### Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 8 (x86_64) | ol8_x86_64_oraclelinuxmanager210_client ###
      - name: Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 8 (x86_64)
        description: All Oracle Linux Manager (formerly Spacewalk) Client 2.10 packages released for Oracle Linux 8 (x86_64).
        label: ol8_x86_64_oraclelinuxmanager210_client
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/oraclelinuxmanager210/client/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol8_olm }}"


foreman_content_views_ol8_olm:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_oraclelinuxmanager210_client"
    organization: "{{ foreman_organization_ol8_olm }}"
    repositories:
      - name: Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False

