---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol7_uln_leapp:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol7_uln_leapp }}"
    repositories:
      ### Leapp Upgrade Utilities for Oracle Linux 7 (x86_64) | ol7_x86_64_leapp ###
      - name: Leapp Upgrade Utilities for Oracle Linux 7 (x86_64)
        description: Latest packages for in-place upgrade from Oracle Linux 7 to Oracle Linux 8 (x86_64) .
        label: ol7_uln_x86_64_leapp
        url: uln://ol7_x86_64_leapp
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_leapp }}"


foreman_content_views_ol7_uln_leapp:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_leapp"
    organization: "{{ foreman_organization_ol7_uln_leapp }}"
    repositories:
      - name: Leapp Upgrade Utilities for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

