---

foreman_content_credentials_ol7: []

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_ol7:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Latest (x86_64) | ol7_x86_64_latest ###
      - name: Oracle Linux 7 Latest (x86_64)
        description: All packages released for Oracle Linux 7 (x86_64) including the latest errata packages. (x86_64)
        label: ol7_x86_64_latest
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/latest/x86_64/"
        <<: *foreman_products_defaults

      ### Oracle Linux 7 Latest Optional Packages (x86_64) | ol7_x86_64_optional_latest ###
      - name: Oracle Linux 7 Latest Optional Packages (x86_64)
        description: All optional packages released for Oracle Linux 7 (x86_64) including the latest errata packages. (x86_64)
        label: ol7_x86_64_optional_latest
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/optional/latest/x86_64/"
        <<: *foreman_products_defaults

      ### Oracle Linux 7 Addons (x86_64) | ol7_x86_64_addons ###
      - name: Oracle Linux 7 Addons (x86_64)
        description: Oracle Linux 7 Addons (x86_64).
        label: ol7_x86_64_addons
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/addons/x86_64/"
        <<: *foreman_products_defaults
      ### Oracle Linux 7 (x86_64) Development | ol7_x86_64_developer ###
      - name: Oracle Linux 7 (x86_64) Development
        description: Latest packages for creating test and development environments - Oracle LInux 7 (x86_64)
        label: ol7_x86_64_developer
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/developer/x86_64/"
        <<: *foreman_products_defaults
      ### EPEL Packages for creating test and development environments for Oracle Linux 7 (x86_64) | ol7_x86_64_developer_EPEL ###
      - name: EPEL Packages for creating test and development environments for Oracle Linux 7 (x86_64)
        description: Latest EPEL packages for creating test and development environments - Oracle LInux 7 (x86_64)
        label: ol7_x86_64_developer_EPEL
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/developer_EPEL/x86_64/"
        <<: *foreman_products_defaults
      ### Oracle Software Collections for Oracle Linux 7 (x86_64) | ol7_x86_64_SoftwareCollections ###
      - name: Oracle Software Collections for Oracle Linux 7 (x86_64)
        description: Latest Oracle Software Collections 3.0 packages for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_SoftwareCollections
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/SoftwareCollections/x86_64/"
        <<: *foreman_products_defaults

      # - name: Oracle Linux 7 Debuginfo (x86_64)
      #   label: ol7_debuginfo
      #   url: https://oss.oracle.com/ol7/debuginfo/
      #   <<: *foreman_products_defaults


foreman_content_views_ol7:
  - name: cv_ol7_x86_64_latest
    repositories:
      - name: Oracle Linux 7 Latest (x86_64)
        product: Oracle Linux
    allow_promote: False

  - name: cv_ol7_x86_64_optional_latest
    repositories:
      - name: Oracle Linux 7 Latest Optional Packages (x86_64)
        product: Oracle Linux
    allow_promote: False

  - name: cv_ol7_x86_64_addons
    repositories:
      - name: Oracle Linux 7 Addons (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_developer
    repositories:
      - name: Oracle Linux 7 (x86_64) Development
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_developer_EPEL
    repositories:
      - name: EPEL Packages for creating test and development environments for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_SoftwareCollections
    repositories:
      - name: Oracle Software Collections for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

  # - name: cv_ol7_debuginfo
  #   repositories:
  #     - name: Oracle Linux 7 Debuginfo (x86_64)
  #       product: Oracle Linux
  #   allow_promote: False

  - name: ccv_ol7
    composite: True
    auto_publish: True
    components:
      - content_view: cv_ol7_x86_64_latest
        latest: true
      - content_view: cv_ol7_x86_64_optional_latest
        latest: true
      - content_view: cv_ol7_x86_64_addons
        latest: true
      - content_view: cv_ol7_x86_64_developer
        latest: true
      - content_view: cv_ol7_x86_64_developer_EPEL
        latest: true
      - content_view: cv_ol7_x86_64_SoftwareCollections
        latest: true
      # - content_view: cv_ol7_debuginfo
      #   latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"


foreman_operatingsystems_ol7:
  - name: "OracleLinux"
    major: "7"
    minor: ""
    description: "Oracle Linux 7"
    default_templates: "{{ foreman_operatingsystems_ol7_default_templates | default( foreman_operatingsystems_ol_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_ol7:
  - name: Oracle Linux 7
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u9_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Oracle Linux"
  auto_attach: False
  # release_version: 7Server
  # service_level: Standard


foreman_activation_keys_ol7:
  - name: ak_ol7
    content_view: ccv_ol7
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_OL_ol7_x86_64_latest"
        override: default
      - label: "{{ foreman_organization }}_OL_ol7_x86_64_optional_latest"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_x86_64_addons"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_x86_64_developer"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_x86_64_developer_EPEL"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_x86_64_SoftwareCollections"
        override: disabled
      # - label: "{{ foreman_organization }}_OL_ol7_debuginfo"
      #   override: disabled


foreman_sync_plan_products_ol7: []

