---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol9_uekr7:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol9_uekr7 }}"
    repositories:
      ### Oracle Linux 9 UEK Release 7 (x86_64) | ol9_x86_64_UEKR7 ###
      - name: Oracle Linux 9 UEK Release 7 (x86_64)
        description: Unbreakable Enterprise Kernel Release 7 packages for Oracle Linux 9 (x86_64)
        label: ol9_x86_64_UEKR7
        url: "{{ foreman_repo_baseurl_oracle9 }}/OL9/UEKR7/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol9_uekr7 }}"

foreman_products_ol9_uekr7_developer:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol9_uekr7_developer }}"
    repositories:
      ### Developer preview of Unbreakable Enterprise Kernel Release 7 for Oracle Linux 9 (x86_64) | ol9_x86_64_developer_UEKR7 ###
      - name: Developer preview of Unbreakable Enterprise Kernel Release 7 for Oracle Linux 9 (x86_64)
        description: Developer preview of Unbreakable Enterprise Kernel Release 7 packages for Oracle Linux 9 (x86_64) - (not for production use)
        label: ol9_x86_64_developer_UEKR7
        url: "{{ foreman_repo_baseurl_oracle9 }}/OL9/developer/UEKR7/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol9_uekr7_developer }}"

foreman_products_ol9_rdma:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol9_rdma }}"
    repositories:
      ### Oracle Linux 9 RDMA (x86_64) | ol9_x86_64_RDMA ###
      - name: Oracle Linux 9 RDMA (x86_64)
        description: Latest RDMA packages for Oracle Linux 9 (x86_64)
        label: ol9_x86_64_RDMA
        url: "{{ foreman_repo_baseurl_oracle9 }}/OL9/RDMA/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol9_rdma }}"

foreman_products_ol9_modrhck:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol9_modrhck }}"
    repositories:
      ### Red Hat compatible kernel with Oracle provided fixes for Oracle Linux 9 (x86_64) | ol9_x86_64_MODRHCK ###
      - name: Red Hat compatible kernel with Oracle provided fixes for Oracle Linux 9 (x86_64)
        description: Latest Red Hat compatible kernel with Oracle provided fixes for Oracle Linux 9 (x86_64).
        label: ol9_x86_64_MODRHCK
        url: "{{ foreman_repo_baseurl_oracle9 }}/OL9/MODRHCK/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol9_modrhck }}"

foreman_products_ol9_uek: "{{ [] |
  union( foreman_products_ol9_uekr7 | default([]) if foreman_enable_ol9_uekr7 else [] ) |
  union( foreman_products_ol9_uekr7_developer | default([]) if foreman_enable_ol9_uekr7_developer else [] ) |
  union( foreman_products_ol9_rdma | default([]) if foreman_enable_ol9_rdma else [] ) |
  union( foreman_products_ol9_modrhck | default([]) if foreman_enable_ol9_modrhck else [] )
  }}"


foreman_content_views_ol9_uekr7:
  - name: cv_ol9_x86_64_UEKR7
    organization: "{{ foreman_organization_ol9_uekr7 }}"
    repositories:
      - name: Oracle Linux 9 UEK Release 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol9_uekr7_developer:
  - name: cv_ol9_x86_64_developer_UEKR7
    organization: "{{ foreman_organization_ol9_uekr7_developer }}"
    repositories:
      - name: Developer preview of Unbreakable Enterprise Kernel Release 7 for Oracle Linux 9 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol9_rdma:
  - name: cv_ol9_x86_64_RDMA
    organization: "{{ foreman_organization_ol9_rdma }}"
    repositories:
      - name: Oracle Linux 9 RDMA (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol9_modrhck:
  - name: cv_ol9_x86_64_MODRHCK
    organization: "{{ foreman_organization_ol9_modrhck }}"
    repositories:
      - name: Red Hat compatible kernel with Oracle provided fixes for Oracle Linux 9 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol9_uek: "{{ [] |
  union( foreman_content_views_ol9_uekr7 | default([]) if foreman_enable_ol9_uekr7 else [] ) |
  union( foreman_content_views_ol9_uekr7_developer | default([]) if foreman_enable_ol9_uekr7_developer else [] ) |
  union( foreman_content_views_ol9_rdma | default([]) if foreman_enable_ol9_rdma else [] ) |
  union( foreman_content_views_ol9_modrhck | default([]) if foreman_enable_ol9_modrhck else [] )
  }}"

