---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: "{{ foreman_products_defaults_download_policy_ol7_uln }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol7_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol7_uln | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol7_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol7_uln | bool }}"
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"


foreman_products_defaults_ol90_uln: &foreman_products_defaults_ol90_uln
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol90_uln }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol90_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol90_uln | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol90_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol90_uln | bool }}"

foreman_products_defaults_ol91_uln: &foreman_products_defaults_ol91_uln
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol91_uln }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol91_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol91_uln | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol91_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol91_uln | bool }}"

foreman_products_defaults_ol92_uln: &foreman_products_defaults_ol92_uln
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol92_uln }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol92_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol92_uln | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol92_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol92_uln | bool }}"


foreman_products_defaults_ol90_patch_uln: &foreman_products_defaults_ol90_patch_uln
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol90_patch_uln }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol90_patch_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol90_patch_uln | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol90_patch_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol90_patch_uln | bool }}"

foreman_products_defaults_ol91_patch_uln: &foreman_products_defaults_ol91_patch_uln
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol91_patch_uln }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol91_patch_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol91_patch_uln | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol91_patch_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol91_patch_uln | bool }}"

foreman_products_defaults_ol92_patch_uln: &foreman_products_defaults_ol92_patch_uln
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ol92_patch_uln }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ol92_patch_uln }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ol92_patch_uln | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ol92_patch_uln }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ol92_patch_uln | bool }}"


foreman_products_ol90_uln:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol90_uln }}"
    repositories:
      ### Oracle Linux 9 BaseOS GA (x86_64) | ol9_x86_64_u0_baseos_base ###
      - name: Oracle Linux 9 BaseOS GA (x86_64)
        description: Base operating system packages released for Oracle Linux 9 (x86_64). No errata included
        label: ol9_uln_x86_64_u0_baseos_base
        url: uln://ol9_x86_64_u0_baseos_base
        <<: *foreman_products_defaults_ol90_uln
        organization: "{{ foreman_organization_ol90_uln }}"

foreman_products_ol91_uln:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol91_uln }}"
    repositories:
      ### Oracle Linux 9.1 BaseOS (x86_64) | ol9_x86_64_u1_baseos_base ###
      - name: Oracle Linux 9.1 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 9.1 (x86_64). No errata included
        label: ol9_uln_x86_64_u1_baseos_base
        url: uln://ol9_x86_64_u1_baseos_base
        <<: *foreman_products_defaults_ol91_uln
        organization: "{{ foreman_organization_ol91_uln }}"

foreman_products_ol92_uln:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol92_uln }}"
    repositories:
      ### Oracle Linux 9.2 BaseOS (x86_64) | ol9_x86_64_u2_baseos_base ###
      - name: Oracle Linux 9.2 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 9.2 (x86_64). No errata included
        label: ol9_uln_x86_64_u2_baseos_base
        url: uln://ol9_x86_64_u2_baseos_base
        <<: *foreman_products_defaults_ol92_uln
        organization: "{{ foreman_organization_ol92_uln }}"

foreman_products_ol90_patch_uln:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol90_patch_uln }}"
    repositories:
      ### Oracle Linux 9 BaseOS GA Patch (x86_64) | ol9_x86_64_u0_baseos_patch ###
      - name: Oracle Linux 9 BaseOS GA Patch (x86_64)
        description: Updated packages published after release of Oracle Linux 9 BaseOS GA (x86_64).
        label: ol9_uln_x86_64_u0_baseos_patch
        url: uln://ol9_x86_64_u0_baseos_patch
        <<: *foreman_products_defaults_ol90_patch_uln
        organization: "{{ foreman_organization_ol90_patch_uln }}"

foreman_products_ol91_patch_uln:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol91_patch_uln }}"
    repositories:
      ### Oracle Linux 9.1 BaseOS Patch (x86_64) | ol9_x86_64_u1_baseos_patch ###
      - name: Oracle Linux 9.1 BaseOS Patch (x86_64)
        description: Updated packages published after release of Oracle Linux 9.1 BaseOS GA (x86_64).
        label: ol9_uln_x86_64_u1_baseos_patch
        url: uln://ol9_x86_64_u1_baseos_patch
        <<: *foreman_products_defaults_ol91_patch_uln
        organization: "{{ foreman_organization_ol91_patch_uln }}"

foreman_products_ol92_patch_uln:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol92_patch_uln }}"
    repositories:
      ### Oracle Linux 9.2 BaseOS Patch (x86_64) | ol9_x86_64_u2_baseos_patch ###
      - name: Oracle Linux 9.2 BaseOS Patch (x86_64)
        description: Updated packages published after release of Oracle Linux 9.2 BaseOS GA (x86_64).
        label: ol9_uln_x86_64_u2_baseos_patch
        url: uln://ol9_x86_64_u2_baseos_patch
        <<: *foreman_products_defaults_ol92_patch_uln
        organization: "{{ foreman_organization_ol92_patch_uln }}"

foreman_products_ol9_uln_versions: "{{ [] |
  union( foreman_products_ol90_uln | default([]) if foreman_enable_ol90_uln else [] ) |
  union( foreman_products_ol91_uln | default([]) if foreman_enable_ol91_uln else [] ) |
  union( foreman_products_ol92_uln | default([]) if foreman_enable_ol92_uln else [] ) |

  union( foreman_products_ol90_patch_uln | default([]) if foreman_enable_ol90_patch_uln else [] ) |
  union( foreman_products_ol91_patch_uln | default([]) if foreman_enable_ol91_patch_uln else [] ) |
  union( foreman_products_ol92_patch_uln | default([]) if foreman_enable_ol92_patch_uln else [] )
  }}"


foreman_content_views_ol90_uln:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_uln_x86_64_u0_baseos_base"
    organization: "{{ foreman_organization_ol90_uln }}"
    repositories:
      - name: Oracle Linux 9 BaseOS GA (x86_64)
        product: Oracle Linux
    allow_promote: "{{ foreman_cv_allow_promote_ol90_uln }}"

foreman_content_views_ol91_uln:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_uln_x86_64_u1_baseos_base"
    organization: "{{ foreman_organization_ol91_uln }}"
    repositories:
      - name: Oracle Linux 9.1 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: "{{ foreman_cv_allow_promote_ol91_uln }}"

foreman_content_views_ol92_uln:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_uln_x86_64_u2_baseos_base"
    organization: "{{ foreman_organization_ol92_uln }}"
    repositories:
      - name: Oracle Linux 9.2 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: "{{ foreman_cv_allow_promote_ol92_uln }}"

foreman_content_views_ol90_patch_uln:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_uln_x86_64_u0_baseos_patch"
    organization: "{{ foreman_organization_ol90_patch_uln }}"
    repositories:
      - name: Oracle Linux 9 BaseOS GA Patch (x86_64)
        product: Oracle Linux
    allow_promote: "{{ foreman_cv_allow_promote_ol90_patch_uln }}"

foreman_content_views_ol91_patch_uln:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_uln_x86_64_u1_baseos_patch"
    organization: "{{ foreman_organization_ol91_patch_uln }}"
    repositories:
      - name: Oracle Linux 9.1 BaseOS Patch (x86_64)
        product: Oracle Linux
    allow_promote: "{{ foreman_cv_allow_promote_ol91_patch_uln }}"

foreman_content_views_ol92_patch_uln:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_uln_x86_64_u2_baseos_patch"
    organization: "{{ foreman_organization_ol92_patch_uln }}"
    repositories:
      - name: Oracle Linux 9.2 BaseOS Patch (x86_64)
        product: Oracle Linux
    allow_promote: "{{ foreman_cv_allow_promote_ol92_patch_uln }}"

foreman_content_views_ol9_uln_versions: "{{ [] |
  union( foreman_content_views_ol90_uln | default([]) if foreman_enable_ol90_uln else [] ) |
  union( foreman_content_views_ol91_uln | default([]) if foreman_enable_ol91_uln else [] ) |
  union( foreman_content_views_ol92_uln | default([]) if foreman_enable_ol92_uln else [] ) |

  union( foreman_content_views_ol90_patch_uln | default([]) if foreman_enable_ol90_patch_uln else [] ) |
  union( foreman_content_views_ol91_patch_uln | default([]) if foreman_enable_ol91_patch_uln else [] ) |
  union( foreman_content_views_ol92_patch_uln | default([]) if foreman_enable_ol92_patch_uln else [] )
  }}"


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_cloud_init | default( foreman_operatingsystems_ol_template_cloud_init | default( foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_finish | default( foreman_operatingsystems_ol_template_finish | default( foreman_operatingsystems_el_template_finish | default('Kickstart default finish') ) ) }}"
    - template_kind: "host_init_config"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_host_init_config | default( foreman_operatingsystems_ol_template_host_init_config | default( foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    - template_kind: "iPXE"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_ipxe | default( foreman_operatingsystems_ol_template_ipxe | default( foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_provision | default( foreman_operatingsystems_ol_template_provision | default( foreman_operatingsystems_el_template_provision | default('Kickstart default') ) ) }}"
    - template_kind: "PXEGrub"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_pxegrub | default( foreman_operatingsystems_ol_template_pxegrub | default( foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_pxegrub2 | default( foreman_operatingsystems_ol_template_pxegrub2 | default( foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_pxelinux | default( foreman_operatingsystems_ol_template_pxelinux | default( foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_user_data | default( foreman_operatingsystems_ol_template_user_data | default( foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') ) ) }}"


foreman_operatingsystems_ol90_uln:
  - name: "OracleLinux"
    major: "9"
    minor: "0"
    description: "Oracle Linux 9.0"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol91_uln:
  - name: "OracleLinux"
    major: "9"
    minor: "1"
    description: "Oracle Linux 9.1"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol92_uln:
  - name: "OracleLinux"
    major: "9"
    minor: "2"
    description: "Oracle Linux 9.2"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol9_uln_versions: "{{ [] |
  union( foreman_operatingsystems_ol90_uln | default([]) if foreman_enable_ol90_uln else [] ) |
  union( foreman_operatingsystems_ol91_uln | default([]) if foreman_enable_ol91_uln else [] ) |
  union( foreman_operatingsystems_ol92_uln | default([]) if foreman_enable_ol92_uln else [] )
  }}"


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_ol90_uln:
  - name: Oracle Linux 9.0 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/OL/ol9_uln_x86_64_u0_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 9.0

foreman_installation_media_ol91_uln:
  - name: Oracle Linux 9.1 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/OL/ol9_uln_x86_64_u1_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 9.1

foreman_installation_media_ol92_uln:
  - name: Oracle Linux 9.2 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/OL/ol9_uln_x86_64_u2_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 9.2

foreman_installation_media_ol9_uln_versions: "{{ [] |
  union( foreman_installation_media_ol90_uln | default([]) if foreman_enable_ol90_uln else [] ) |
  union( foreman_installation_media_ol91_uln | default([]) if foreman_enable_ol91_uln else [] ) |
  union( foreman_installation_media_ol92_uln | default([]) if foreman_enable_ol92_uln else [] )
  }}"

