---

foreman_content_credentials_ol7_uln: []


foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol7_uln:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Latest (x86_64) | ol7_x86_64_latest ###
      - name: Oracle Linux 7 Latest (x86_64)
        description: All packages released for Oracle Linux 7 (x86_64) including the latest errata packages. (x86_64)
        label: ol7_uln_x86_64_latest
        url: uln://ol7_x86_64_latest
        <<: *foreman_products_defaults
      # ### Oracle Linux 7 Archive (x86_64) | ol7_x86_64_latest_archive ###
      # - name: Oracle Linux 7 Archive (x86_64)
      #   description: Archived packages for Oracle Linux 7 (x86_64)
      #   label: ol7_uln_x86_64_latest_archive
      #   url: uln://ol7_x86_64_latest_archive
      #   <<: *foreman_products_defaults

      ### Oracle Linux 7 Latest Optional Packages (x86_64) | ol7_x86_64_optional_latest ###
      - name: Oracle Linux 7 Latest Optional Packages (x86_64)
        description: All optional packages released for Oracle Linux 7 (x86_64) including the latest errata packages. (x86_64)
        label: ol7_uln_x86_64_optional_latest
        url: uln://ol7_x86_64_optional_latest
        <<: *foreman_products_defaults
      # ### Oracle Linux 7 Latest Optional Packages (x86_64) - Archive | ol7_x86_64_optional_archive ###
      # - name: Oracle Linux 7 Latest Optional Packages (x86_64) - Archive
      #   description: Archived optional packages released for Oracle Linux 7 (x86_64) including the latest errata packages. (x86_64)
      #   label: ol7_uln_x86_64_optional_archive
      #   url: uln://ol7_x86_64_optional_archive
      #   <<: *foreman_products_defaults

      ### Oracle Linux 7 Addons (x86_64) | ol7_x86_64_addons ###
      - name: Oracle Linux 7 Addons (x86_64)
        description: Oracle Linux 7 Addons (x86_64).
        label: ol7_uln_x86_64_addons
        url: uln://ol7_x86_64_addons
        <<: *foreman_products_defaults
      ### Oracle Linux 7 (x86_64) Development | ol7_x86_64_developer ###
      - name: Oracle Linux 7 (x86_64) Development
        description: Latest packages for creating test and development environments - Oracle LInux 7 (x86_64)
        label: ol7_uln_x86_64_developer
        url: uln://ol7_x86_64_developer
        <<: *foreman_products_defaults
      ### EPEL Packages for creating test and development environments for Oracle Linux 7 (x86_64) | ol7_x86_64_developer_EPEL ###
      - name: EPEL Packages for creating test and development environments for Oracle Linux 7 (x86_64)
        description: Latest EPEL packages for creating test and development environments - Oracle LInux 7 (x86_64)
        label: ol7_uln_x86_64_developer_EPEL
        url: uln://ol7_x86_64_developer_EPEL
        <<: *foreman_products_defaults
      ### Oracle Software Collections for Oracle Linux 7 (x86_64) | ol7_x86_64_SoftwareCollections ###
      - name: Oracle Software Collections for Oracle Linux 7 (x86_64)
        description: Latest Oracle Software Collections 3.0 packages for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_SoftwareCollections
        url: uln://ol7_x86_64_SoftwareCollections
        <<: *foreman_products_defaults

      # ### Packages considered as preview for test and development environments for Oracle Linux 7 (x86_64) | ol7_x86_64_preview ###
      # - name: Packages considered as preview for test and development environments for Oracle Linux 7 (x86_64)
      #   description: Technology preview packages for testing and development on Oracle Linux 7.  Not for use in production.
      #   label: ol7_uln_x86_64_preview
      #   url: uln://ol7_x86_64_preview
      #   <<: *foreman_products_defaults

      # ### Developer Preview of Oracle Linux 7 Update 5 (x86_64) - (not for production use) | ol7_x86_64_u5_developer ###
      # - name: Developer Preview of Oracle Linux 7 Update 5 (x86_64) - (not for production use)
      #   description: Developer Preview of Oracle Linux 7 Update 5 (x86_64) - (not for production use)
      #   label: ol7_uln_x86_64_u5_developer
      #   url: uln://ol7_x86_64_u5_developer
      #   <<: *foreman_products_defaults
      # ### Developer Preview of Oracle Linux 7 Update 5 (x86_64) Optional Packages (not for production use) | ol7_x86_64_optional_developer ###
      # - name: Developer Preview of Oracle Linux 7 Update 5 (x86_64) Optional Packages (not for production use)
      #   description: Developer Preview of Oracle Linux 7 Update 5 (x86_64) Optional Packages (not for production use)
      #   label: ol7_uln_x86_64_optional_developer
      #   url: uln://ol7_x86_64_optional_developer
      #   <<: *foreman_products_defaults
      # ### Oracle Linux 7 Update 9 Beta (x86_64) Optional | ol7_x86_64_optional_beta ###
      # - name: Oracle Linux 7 Update 9 Beta (x86_64) Optional
      #   description: Optional beta packages for Oracle Linux 7 Update 9 (x86_64). Not for production use.
      #   label: ol7_uln_x86_64_optional_beta
      #   url: uln://ol7_x86_64_optional_beta
      #   <<: *foreman_products_defaults
      # ### Oracle Linux 7 Update 9 Beta (x86_64) | ol7_x86_64_beta ###
      # - name: Oracle Linux 7 Update 9 Beta (x86_64)
      #   description: All beta packages for Oracle Linux 7 Update 9 (x86_64). Not for production use.
      #   label: ol7_uln_x86_64_beta
      #   url: uln://ol7_x86_64_beta
      #   <<: *foreman_products_defaults


foreman_content_views_ol7_uln:
  - name: cv_ol7_uln_x86_64_latest
    repositories:
      - name: Oracle Linux 7 Latest (x86_64)
        product: Oracle Linux
    allow_promote: False
  # - name: cv_ol7_uln_x86_64_latest_archive
  #   repositories:
  #     - name: Oracle Linux 7 Archive (x86_64)
  #       product: Oracle Linux
  #   allow_promote: False

  - name: cv_ol7_uln_x86_64_optional_latest
    repositories:
      - name: Oracle Linux 7 Latest Optional Packages (x86_64)
        product: Oracle Linux
    allow_promote: False
  # - name: cv_ol7_uln_x86_64_optional_archive
  #   repositories:
  #     - name: Oracle Linux 7 Latest Optional Packages (x86_64) - Archive
  #       product: Oracle Linux
  #   allow_promote: False

  - name: cv_ol7_uln_x86_64_addons
    repositories:
      - name: Oracle Linux 7 Addons (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_uln_x86_64_developer
    repositories:
      - name: Oracle Linux 7 (x86_64) Development
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_uln_x86_64_developer_EPEL
    repositories:
      - name: EPEL Packages for creating test and development environments for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_uln_x86_64_SoftwareCollections
    repositories:
      - name: Oracle Software Collections for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

  # - name: cv_ol7_uln_x86_64_preview
  #   repositories:
  #     - name: Packages considered as preview for test and development environments for Oracle Linux 7 (x86_64)
  #       product: Oracle Linux
  #   allow_promote: False

  # - name: cv_ol7_uln_x86_64_u5_developer
  #   repositories:
  #     - name: Developer Preview of Oracle Linux 7 Update 5 (x86_64) - (not for production use)
  #       product: Oracle Linux
  #   allow_promote: False
  # - name: cv_ol7_uln_x86_64_optional_developer
  #   repositories:
  #     - name: Developer Preview of Oracle Linux 7 Update 5 (x86_64) Optional Packages (not for production use)
  #       product: Oracle Linux
  #   allow_promote: False
  # - name: cv_ol7_uln_x86_64_beta
  #   repositories:
  #     - name: Oracle Linux 7 Update 9 Beta (x86_64)
  #       product: Oracle Linux
  #   allow_promote: False
  # - name: cv_ol7_uln_x86_64_optional_beta
  #   repositories:
  #     - name: Oracle Linux 7 Update 9 Beta (x86_64) Optional
  #       product: Oracle Linux
  #   allow_promote: False

  - name: ccv_ol7
    composite: True
    auto_publish: True
    components:
      - content_view: cv_ol7_uln_x86_64_latest
        latest: true
      # - content_view: cv_ol7_uln_x86_64_latest_archive
      #   latest: true
      - content_view: cv_ol7_uln_x86_64_optional_latest
        latest: true
      # - content_view: cv_ol7_uln_x86_64_optional_archive
      #   latest: true
      - content_view: cv_ol7_uln_x86_64_addons
        latest: true
      - content_view: cv_ol7_uln_x86_64_developer
        latest: true
      - content_view: cv_ol7_uln_x86_64_developer_EPEL
        latest: true
      - content_view: cv_ol7_uln_x86_64_SoftwareCollections
        latest: true
      # - content_view: cv_ol7_uln_x86_64_preview
      #   latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_cloud_init | default( foreman_operatingsystems_ol_template_cloud_init | default( foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_finish | default( foreman_operatingsystems_ol_template_finish | default( foreman_operatingsystems_el_template_finish | default('Kickstart default finish') ) ) }}"
    - template_kind: "host_init_config"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_host_init_config | default( foreman_operatingsystems_ol_template_host_init_config | default( foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    - template_kind: "iPXE"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_ipxe | default( foreman_operatingsystems_ol_template_ipxe | default( foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_provision | default( foreman_operatingsystems_ol_template_provision | default( foreman_operatingsystems_el_template_provision | default('Kickstart default') ) ) }}"
    - template_kind: "PXEGrub"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_pxegrub | default( foreman_operatingsystems_ol_template_pxegrub | default( foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_pxegrub2 | default( foreman_operatingsystems_ol_template_pxegrub2 | default( foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_pxelinux | default( foreman_operatingsystems_ol_template_pxelinux | default( foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_user_data | default( foreman_operatingsystems_ol_template_user_data | default( foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') ) ) }}"


foreman_operatingsystems_ol7_uln:
  - name: "OracleLinux"
    major: "7"
    minor: ""
    description: "Oracle Linux 7"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_ol7_uln:
  - name: Oracle Linux 7
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/OL/ol7_uln_x86_64_u9_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Oracle Linux"
  auto_attach: False
  # release_version: 7Server
  # service_level: Standard


foreman_activation_keys_ol7_uln:
  - name: ak_ol7
    content_view: ccv_ol7
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_latest"
        override: default
      # - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_latest_archive"
      #   override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_optional_latest"
        override: disabled
      # - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_optional_archive"
      #   override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_addons"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_developer"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_developer_EPEL"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_SoftwareCollections"
        override: disabled
      # - label: "{{ foreman_organization }}_OL_ol7_uln_x86_64_preview"
      #   override: disabled


foreman_sync_plan_products_ol7_uln: []

