---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol7_uln_virtualization_kvm_utils:
  - name: Oracle Linux
    label: OL
    repositories:
      ### KVM Utilities for Oracle Linux 7 (x86_64) | ol7_x86_64_kvm_utils ###
      - name: KVM Utilities for Oracle Linux 7 (x86_64)
        description: Latest packages for KVM Utilities for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_kvm_utils
        url: uln://ol7_x86_64_kvm_utils
        <<: *foreman_products_defaults
      ### Developer Preview of KVM Utilities for Oracle Linux 7 (x86_64) | ol7_x86_64_developer_kvm_utils ###
      - name: Developer Preview of KVM Utilities for Oracle Linux 7 (x86_64)
        description: Latest KVM Utility packages for test and development for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_developer_kvm_utils
        url: uln://ol7_x86_64_developer_kvm_utils
        <<: *foreman_products_defaults

foreman_products_ol7_uln_virtualization_ovirt42:
  - name: Oracle Linux
    label: OL
    repositories:
      ### oVirt Release 4.2 on Oracle Linux 7 (x86_64) | ol7_x86_64_ovirt42 ###
      - name: oVirt Release 4.2 on Oracle Linux 7 (x86_64)
        description: Latest packages for oVirt Release 4.2 on Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_ovirt42
        url: uln://ol7_x86_64_ovirt42
        <<: *foreman_products_defaults
      ### oVirt Release 4.2 on Oracle Linux 7 (x86_64) - Extra | ol7_x86_64_ovirt42_extras ###
      - name: oVirt Release 4.2 on Oracle Linux 7 (x86_64) - Extra
        description: Latest extra packages for oVirt Release 4.2 on Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_ovirt42_extras
        url: uln://ol7_x86_64_ovirt42_extras
        <<: *foreman_products_defaults

foreman_products_ol7_uln_virtualization_ovirt43:
  - name: Oracle Linux
    label: OL
    repositories:
      ### oVirt Release 4.3 on Oracle Linux 7 (x86_64) | ol7_x86_64_ovirt43 ###
      - name: oVirt Release 4.3 on Oracle Linux 7 (x86_64)
        description: Latest packages for oVirt Release 4.3 on Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_ovirt43
        url: uln://ol7_x86_64_ovirt43
        <<: *foreman_products_defaults
      ### oVirt Release 4.3 on Oracle Linux 7 (x86_64) - Extra | ol7_x86_64_ovirt43_extras ###
      - name: oVirt Release 4.3 on Oracle Linux 7 (x86_64) - Extra
        description: Latest extra packages for oVirt Release 4.3 on Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_ovirt43_extras
        url: uln://ol7_x86_64_ovirt43_extras
        <<: *foreman_products_defaults

foreman_products_ol7_uln_virtualization: "{{ [] |
  union( foreman_products_ol7_uln_virtualization_kvm_utils | default([]) if foreman_enable_ol7_uln_virtualization_kvm_utils else [] ) |
  union( foreman_products_ol7_uln_virtualization_ovirt42 | default([]) if foreman_enable_ol7_uln_virtualization_ovirt42 else [] ) |
  union( foreman_products_ol7_uln_virtualization_ovirt43 | default([]) if foreman_enable_ol7_uln_virtualization_ovirt43 else [] )
  }}"


foreman_content_views_ol7_uln_virtualization_kvm_utils:
  - name: cv_ol7_uln_x86_64_kvm_utils
    repositories:
      - name: KVM Utilities for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_uln_x86_64_developer_kvm_utils
    repositories:
      - name: Developer Preview of KVM Utilities for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_uln_virtualization_ovirt42:
  - name: cv_ol7_uln_x86_64_ovirt42
    repositories:
      - name: oVirt Release 4.2 on Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_uln_x86_64_ovirt42_extras
    repositories:
      - name: oVirt Release 4.2 on Oracle Linux 7 (x86_64) - Extra
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_uln_virtualization_ovirt43:
  - name: cv_ol7_uln_x86_64_ovirt43
    repositories:
      - name: oVirt Release 4.3 on Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_uln_x86_64_ovirt43_extras
    repositories:
      - name: oVirt Release 4.3 on Oracle Linux 7 (x86_64) - Extra
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_uln_virtualization: "{{ [] |
  union( foreman_content_views_ol7_uln_virtualization_kvm_utils | default([]) if foreman_enable_ol7_uln_virtualization_kvm_utils else [] ) |
  union( foreman_content_views_ol7_uln_virtualization_ovirt42 | default([]) if foreman_enable_ol7_uln_virtualization_ovirt42 else [] ) |
  union( foreman_content_views_ol7_uln_virtualization_ovirt43 | default([]) if foreman_enable_ol7_uln_virtualization_ovirt43 else [] )
  }}"

