---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol80:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol80 }}"
    repositories:
      ### Oracle Linux 8 BaseOS GA (x86_64) | ol8_x86_64_u0_baseos_base ###
      - name: Oracle Linux 8 BaseOS GA (x86_64)
        description: Base operating system packages released for Oracle Linux 8 GA (x86_64). No errata included
        label: ol8_x86_64_u0_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/0/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol80 }}"

foreman_products_ol81:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol81 }}"
    repositories:
      ### Oracle Linux 8.1 BaseOS (x86_64) | ol8_x86_64_u1_baseos_base ###
      - name: Oracle Linux 8.1 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 8 (x86_64). No errata included
        label: ol8_x86_64_u1_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/1/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol81 }}"

foreman_products_ol82:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol82 }}"
    repositories:
      ### Oracle Linux 8.2 BaseOS (x86_64) | ol8_x86_64_u2_baseos_base ###
      - name: Oracle Linux 8.2 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 8.2 (x86_64). No errata included
        label: ol8_x86_64_u2_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/2/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol82 }}"

foreman_products_ol83:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol83 }}"
    repositories:
      ### Oracle Linux 8.3 BaseOS (x86_64) | ol8_x86_64_u3_baseos_base ###
      - name: Oracle Linux 8.3 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 8.3 (x86_64). No errata included
        label: ol8_x86_64_u3_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/3/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol83 }}"

foreman_products_ol84:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol84 }}"
    repositories:
      ### Oracle Linux 8.4 BaseOS (x86_64) | ol8_x86_64_u4_baseos_base ###
      - name: Oracle Linux 8.4 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 8.4 (x86_64). No errata included
        label: ol8_x86_64_u4_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/4/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol84 }}"

foreman_products_ol85:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol85 }}"
    repositories:
      ### Oracle Linux 8.5 BaseOS (x86_64) | ol8_x86_64_u5_baseos_base ###
      - name: Oracle Linux 8.5 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 8.5 (x86_64). No errata included
        label: ol8_x86_64_u5_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/5/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol85 }}"

foreman_products_ol86:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol86 }}"
    repositories:
      ### Oracle Linux 8.6 BaseOS (x86_64) | ol8_x86_64_u6_baseos_base ###
      - name: Oracle Linux 8.6 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 8.6 (x86_64). No errata included
        label: ol8_x86_64_u6_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/6/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol86 }}"

foreman_products_ol87:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol87 }}"
    repositories:
      ### Oracle Linux 8.7 BaseOS (x86_64) | ol8_x86_64_u7_baseos_base ###
      - name: Oracle Linux 8.7 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 8.7 (x86_64). No errata included
        label: ol8_x86_64_u7_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/7/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol87 }}"

foreman_products_ol88:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol88 }}"
    repositories:
      ### Oracle Linux 8.8 BaseOS (x86_64) | ol8_x86_64_u8_baseos_base ###
      - name: Oracle Linux 8.8 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 8.8 (x86_64). No errata included
        label: ol8_x86_64_u8_baseos_base
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/8/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol88 }}"

foreman_products_ol8_versions: "{{ [] |
  union( foreman_products_ol80 | default([]) if foreman_enable_ol80 else [] ) |
  union( foreman_products_ol81 | default([]) if foreman_enable_ol81 else [] ) |
  union( foreman_products_ol82 | default([]) if foreman_enable_ol82 else [] ) |
  union( foreman_products_ol83 | default([]) if foreman_enable_ol83 else [] ) |
  union( foreman_products_ol84 | default([]) if foreman_enable_ol84 else [] ) |
  union( foreman_products_ol85 | default([]) if foreman_enable_ol85 else [] ) |
  union( foreman_products_ol86 | default([]) if foreman_enable_ol86 else [] ) |
  union( foreman_products_ol87 | default([]) if foreman_enable_ol87 else [] ) |
  union( foreman_products_ol88 | default([]) if foreman_enable_ol88 else [] )
  }}"


foreman_content_views_ol80:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u0_baseos_base"
    organization: "{{ foreman_organization_ol80 }}"
    repositories:
      - name: Oracle Linux 8 BaseOS GA (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol81:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u1_baseos_base"
    organization: "{{ foreman_organization_ol81 }}"
    repositories:
      - name: Oracle Linux 8.1 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol82:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u2_baseos_base"
    organization: "{{ foreman_organization_ol82 }}"
    repositories:
      - name: Oracle Linux 8.2 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol83:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u3_baseos_base"
    organization: "{{ foreman_organization_ol83 }}"
    repositories:
      - name: Oracle Linux 8.3 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol84:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u4_baseos_base"
    organization: "{{ foreman_organization_ol84 }}"
    repositories:
      - name: Oracle Linux 8.4 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol85:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u5_baseos_base"
    organization: "{{ foreman_organization_ol85 }}"
    repositories:
      - name: Oracle Linux 8.5 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol86:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u6_baseos_base"
    organization: "{{ foreman_organization_ol86 }}"
    repositories:
      - name: Oracle Linux 8.6 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol87:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u7_baseos_base"
    organization: "{{ foreman_organization_ol87 }}"
    repositories:
      - name: Oracle Linux 8.7 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol88:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_x86_64_u8_baseos_base"
    organization: "{{ foreman_organization_ol88 }}"
    repositories:
      - name: Oracle Linux 8.8 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol8_versions: "{{ [] |
  union( foreman_content_views_ol80 | default([]) if foreman_enable_ol80 else [] ) |
  union( foreman_content_views_ol81 | default([]) if foreman_enable_ol81 else [] ) |
  union( foreman_content_views_ol82 | default([]) if foreman_enable_ol82 else [] ) |
  union( foreman_content_views_ol83 | default([]) if foreman_enable_ol83 else [] ) |
  union( foreman_content_views_ol84 | default([]) if foreman_enable_ol84 else [] ) |
  union( foreman_content_views_ol85 | default([]) if foreman_enable_ol85 else [] ) |
  union( foreman_content_views_ol86 | default([]) if foreman_enable_ol86 else [] ) |
  union( foreman_content_views_ol87 | default([]) if foreman_enable_ol87 else [] ) |
  union( foreman_content_views_ol88 | default([]) if foreman_enable_ol88 else [] )
  }}"


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_cloud_init | default( foreman_operatingsystems_ol_template_cloud_init | default( foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_finish | default( foreman_operatingsystems_ol_template_finish | default( foreman_operatingsystems_el_template_finish | default('Kickstart default finish') ) ) }}"
    - template_kind: "host_init_config"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_host_init_config | default( foreman_operatingsystems_ol_template_host_init_config | default( foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    - template_kind: "iPXE"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_ipxe | default( foreman_operatingsystems_ol_template_ipxe | default( foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_provision | default( foreman_operatingsystems_ol_template_provision | default( foreman_operatingsystems_el_template_provision | default('Kickstart default') ) ) }}"
    - template_kind: "PXEGrub"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_pxegrub | default( foreman_operatingsystems_ol_template_pxegrub | default( foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_pxegrub2 | default( foreman_operatingsystems_ol_template_pxegrub2 | default( foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_pxelinux | default( foreman_operatingsystems_ol_template_pxelinux | default( foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_user_data | default( foreman_operatingsystems_ol_template_user_data | default( foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') ) ) }}"


foreman_operatingsystems_ol80:
  - name: "OracleLinux"
    major: "8"
    minor: "0"
    description: "Oracle Linux 8.0"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol81:
  - name: "OracleLinux"
    major: "8"
    minor: "1"
    description: "Oracle Linux 8.1"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol82:
  - name: "OracleLinux"
    major: "8"
    minor: "2"
    description: "Oracle Linux 8.2"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol83:
  - name: "OracleLinux"
    major: "8"
    minor: "3"
    description: "Oracle Linux 8.3"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol84:
  - name: "OracleLinux"
    major: "8"
    minor: "4"
    description: "Oracle Linux 8.4"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol85:
  - name: "OracleLinux"
    major: "8"
    minor: "5"
    description: "Oracle Linux 8.5"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol86:
  - name: "OracleLinux"
    major: "8"
    minor: "6"
    description: "Oracle Linux 8.6"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol87:
  - name: "OracleLinux"
    major: "8"
    minor: "7"
    description: "Oracle Linux 8.7"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol88:
  - name: "OracleLinux"
    major: "8"
    minor: "8"
    description: "Oracle Linux 8.8"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol8_versions: "{{ [] |
  union( foreman_operatingsystems_ol80 | default([]) if foreman_enable_ol80 else [] ) |
  union( foreman_operatingsystems_ol81 | default([]) if foreman_enable_ol81 else [] ) |
  union( foreman_operatingsystems_ol82 | default([]) if foreman_enable_ol82 else [] ) |
  union( foreman_operatingsystems_ol83 | default([]) if foreman_enable_ol83 else [] ) |
  union( foreman_operatingsystems_ol84 | default([]) if foreman_enable_ol84 else [] ) |
  union( foreman_operatingsystems_ol85 | default([]) if foreman_enable_ol85 else [] ) |
  union( foreman_operatingsystems_ol86 | default([]) if foreman_enable_ol86 else [] ) |
  union( foreman_operatingsystems_ol87 | default([]) if foreman_enable_ol87 else [] ) |
  union( foreman_operatingsystems_ol88 | default([]) if foreman_enable_ol88 else [] )
  }}"


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_ol80:
  - name: Oracle Linux 8.0 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_ga_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.0

foreman_installation_media_ol81:
  - name: Oracle Linux 8.1 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_u1_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.1

foreman_installation_media_ol82:
  - name: Oracle Linux 8.2 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_u2_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.2

foreman_installation_media_ol83:
  - name: Oracle Linux 8.3 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_u3_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.3

foreman_installation_media_ol84:
  - name: Oracle Linux 8.4 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_u4_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.4

foreman_installation_media_ol85:
  - name: Oracle Linux 8.5 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_u5_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.5

foreman_installation_media_ol86:
  - name: Oracle Linux 8.6 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_u6_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.6

foreman_installation_media_ol87:
  - name: Oracle Linux 8.7 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_u7_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.7

foreman_installation_media_ol88:
  - name: Oracle Linux 8.8 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol8_u8_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8.8

foreman_installation_media_ol8_versions: "{{ [] |
  union( foreman_installation_media_ol80 | default([]) if foreman_enable_ol80 else [] ) |
  union( foreman_installation_media_ol81 | default([]) if foreman_enable_ol81 else [] ) |
  union( foreman_installation_media_ol82 | default([]) if foreman_enable_ol82 else [] ) |
  union( foreman_installation_media_ol83 | default([]) if foreman_enable_ol83 else [] ) |
  union( foreman_installation_media_ol84 | default([]) if foreman_enable_ol84 else [] ) |
  union( foreman_installation_media_ol85 | default([]) if foreman_enable_ol85 else [] ) |
  union( foreman_installation_media_ol86 | default([]) if foreman_enable_ol86 else [] ) |
  union( foreman_installation_media_ol87 | default([]) if foreman_enable_ol87 else [] ) |
  union( foreman_installation_media_ol88 | default([]) if foreman_enable_ol88 else [] )
  }}"

