---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol7_uln_olm_spacewalk26:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"
    repositories:
      ### Spacewalk Client 2.6 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk26_client ###
      - name: Spacewalk Client 2.6 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.6 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk26_client
        url: uln://ol7_x86_64_spacewalk26_client
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"
      ### Spacewalk Server 2.6 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk26_server ###
      - name: Spacewalk Server 2.6 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.6 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk26_server
        url: uln://ol7_x86_64_spacewalk26_server
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"

foreman_products_ol7_uln_olm_spacewalk27:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"
    repositories:
      ### Spacewalk Client 2.7 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk27_client ###
      - name: Spacewalk Client 2.7 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.7 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk27_client
        url: uln://ol7_x86_64_spacewalk27_client
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"
      ### Spacewalk Server 2.7 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk27_server ###
      - name: Spacewalk Server 2.7 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.7 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk27_server
        url: uln://ol7_x86_64_spacewalk27_server
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"

foreman_products_ol7_uln_olm_spacewalk210:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"
    repositories:
      ### Spacewalk Client 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk210_client ###
      - name: Spacewalk Client 2.10 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk210_client
        url: uln://ol7_x86_64_spacewalk210_client
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"
      ### Spacewalk Server 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk210_server ###
      - name: Spacewalk Server 2.10 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_spacewalk210_server
        url: uln://ol7_x86_64_spacewalk210_server
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"

foreman_products_ol7_uln_olm_oraclelinuxmanager210:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"
    repositories:
      ### Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_oraclelinuxmanager210_client ###
      - name: Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64)
        description: All Oracle Linux Manager (formerly Spacewalk) Client 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_oraclelinuxmanager210_client
        url: uln://ol7_x86_64_oraclelinuxmanager210_client
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"
      ### Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_oraclelinuxmanager210_server ###
      - name: Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64)
        description: All Oracle Linux Manager (formerly Spacewalk) Server 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_uln_x86_64_oraclelinuxmanager210_server
        url: uln://ol7_x86_64_oraclelinuxmanager210_server
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"

foreman_products_ol7_uln_olm: "{{ [] |
  union( foreman_products_ol7_uln_olm_spacewalk26 | default([]) if foreman_enable_ol7_uln_olm_spacewalk26 else [] ) |
  union( foreman_products_ol7_uln_olm_spacewalk27 | default([]) if foreman_enable_ol7_uln_olm_spacewalk27 else [] ) |
  union( foreman_products_ol7_uln_olm_spacewalk210 | default([]) if foreman_enable_ol7_uln_olm_spacewalk210 else [] ) |
  union( foreman_products_ol7_uln_olm_oraclelinuxmanager210 | default([]) if foreman_enable_ol7_uln_olm_oraclelinuxmanager210 else [] )
  }}"


foreman_content_views_ol7_uln_olm_spacewalk26:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_spacewalk26_client"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"
    repositories:
      - name: Spacewalk Client 2.6 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_spacewalk26_server"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk26 }}"
    repositories:
      - name: Spacewalk Server 2.6 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_uln_olm_spacewalk27:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_spacewalk27_client"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"
    repositories:
      - name: Spacewalk Client 2.7 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_spacewalk27_server"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk27 }}"
    repositories:
      - name: Spacewalk Server 2.7 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_uln_olm_spacewalk210:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_spacewalk210_client"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"
    repositories:
      - name: Spacewalk Client 2.10 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_spacewalk210_server"
    organization: "{{ foreman_organization_ol7_uln_olm_spacewalk210 }}"
    repositories:
      - name: Spacewalk Server 2.10 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_uln_olm_oraclelinuxmanager210:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_oraclelinuxmanager210_client"
    organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"
    repositories:
      - name: Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol7_uln_x86_64_oraclelinuxmanager210_server"
    organization: "{{ foreman_organization_ol7_uln_olm_oraclelinuxmanager210 }}"
    repositories:
      - name: Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_uln_olm: "{{ [] |
  union( foreman_content_views_ol7_uln_olm_spacewalk26 | default([]) if foreman_enable_ol7_uln_olm_spacewalk26 else [] ) |
  union( foreman_content_views_ol7_uln_olm_spacewalk27 | default([]) if foreman_enable_ol7_uln_olm_spacewalk27 else [] ) |
  union( foreman_content_views_ol7_uln_olm_spacewalk210 | default([]) if foreman_enable_ol7_uln_olm_spacewalk210 else [] ) |
  union( foreman_content_views_ol7_uln_olm_oraclelinuxmanager210 | default([]) if foreman_enable_ol7_uln_olm_oraclelinuxmanager210 else [] )
  }}"

