---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol9_olm:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux Manager 2.10 Client (x86_64) | ol9_x86_64_oraclelinuxmanager210_client ###
      - name: Oracle Linux Manager 2.10 Client (x86_64)
        description: Latest Oracle Linux Manager 2.10 Client packages for Oracle Linux 9 (x86_64)
        label: ol9_x86_64_oraclelinuxmanager210_client
        url: "{{ foreman_repo_baseurl_oracle9 }}/OL9/oraclelinuxmanager210/client/x86_64/"
        <<: *foreman_products_defaults


foreman_content_views_ol9_olm:
  - name: cv_ol9_x86_64_oraclelinuxmanager210_client
    repositories:
      - name: Oracle Linux Manager 2.10 Client (x86_64)
        product: Oracle Linux
    allow_promote: False

