---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol8_uln_virtualization_kvm_utils:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol8_uln_virtualization_kvm_utils }}"
    repositories:
      ### Oracle Linux 8 KVM Application Stream (x86_64) | ol8_x86_64_kvm_appstream ###
      - name: Oracle Linux 8 KVM Application Stream (x86_64)
        description: Latest KVM Application Stream Packages for Oracle Linux 8 (x86_64)
        label: ol8_uln_x86_64_kvm_appstream
        url: uln://ol8_x86_64_kvm_appstream
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol8_uln_virtualization_kvm_utils }}"

foreman_products_ol8_uln_virtualization_ovirt44:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol8_uln_virtualization_ovirt44 }}"
    repositories:
      ### oVirt Release 4.4 on Oracle Linux 8 (x86_64) | ol8_x86_64_ovirt44 ###
      - name: oVirt Release 4.4 on Oracle Linux 8 (x86_64)
        description: Latest packages for oVirt Release 4.4 on Oracle Linux 8 (x86_64).
        label: ol8_uln_x86_64_ovirt44
        url: uln://ol8_x86_64_ovirt44
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol8_uln_virtualization_ovirt44 }}"
      ### oVirt Release 4.4 on Oracle Linux 8 (x86_64) - Extra | ol8_x86_64_ovirt44_extras ###
      - name: oVirt Release 4.4 on Oracle Linux 8 (x86_64) - Extra
        description: Latest extra packages for oVirt Release 4.4 on Oracle Linux 8 (x86_64).
        label: ol8_uln_x86_64_ovirt44_extras
        url: uln://ol8_x86_64_ovirt44_extras
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol8_uln_virtualization_ovirt44 }}"

foreman_products_ol8_uln_virtualization: "{{ [] |
  union( foreman_products_ol8_uln_virtualization_kvm_utils | default([]) if foreman_enable_ol8_uln_virtualization_kvm_utils else [] ) |
  union( foreman_products_ol8_uln_virtualization_ovirt44 | default([]) if foreman_enable_ol8_uln_virtualization_ovirt44 else [] )
  }}"


foreman_content_views_ol8_uln_virtualization_kvm_utils:
  - name: cv_ol8_uln_x86_64_kvm_appstream
    organization: "{{ foreman_organization_ol8_uln_virtualization_kvm_utils }}"
    repositories:
      - name: Oracle Linux 8 KVM Application Stream (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol8_uln_virtualization_ovirt44:
  - name: cv_ol8_uln_x86_64_ovirt44
    organization: "{{ foreman_organization_ol8_uln_virtualization_ovirt44 }}"
    repositories:
      - name: oVirt Release 4.4 on Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_uln_x86_64_ovirt44_extras
    organization: "{{ foreman_organization_ol8_uln_virtualization_ovirt44 }}"
    repositories:
      - name: oVirt Release 4.4 on Oracle Linux 8 (x86_64) - Extra
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol8_uln_virtualization: "{{ [] |
  union( foreman_content_views_ol8_uln_virtualization_kvm_utils | default([]) if foreman_enable_ol8_uln_virtualization_kvm_utils else [] ) |
  union( foreman_content_views_ol8_uln_virtualization_ovirt44 | default([]) if foreman_enable_ol8_uln_virtualization_ovirt44 else [] )
  }}"

