---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol7_olm_spacewalk26:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Spacewalk Client 2.6 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk26_client ###
      - name: Spacewalk Client 2.6 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.6 packages released for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_spacewalk26_client
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/spacewalk26/client/x86_64/"
        <<: *foreman_products_defaults
      ### Spacewalk Server 2.6 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk26_server ###
      - name: Spacewalk Server 2.6 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.6 packages released for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_spacewalk26_server
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/spacewalk26/server/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_olm_spacewalk27:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Spacewalk Client 2.7 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk27_client ###
      - name: Spacewalk Client 2.7 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.7 packages released for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_spacewalk27_client
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/spacewalk27/client/x86_64/"
        <<: *foreman_products_defaults
      ### Spacewalk Server 2.7 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk27_server ###
      - name: Spacewalk Server 2.7 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.7 packages released for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_spacewalk27_server
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/spacewalk27/server/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_olm_spacewalk210:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Spacewalk Client 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk210_client ###
      - name: Spacewalk Client 2.10 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Client 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_spacewalk210_client
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/spacewalk210/client/x86_64/"
        <<: *foreman_products_defaults
      ### Spacewalk Server 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_spacewalk210_server ###
      - name: Spacewalk Server 2.10 for Oracle Linux 7 (x86_64)
        description: All Spacewalk Server 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_spacewalk210_server
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/spacewalk210/server/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_olm_oraclelinuxmanager210:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_oraclelinuxmanager210_client ###
      - name: Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64)
        description: All Oracle Linux Manager (formerly Spacewalk) Client 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_oraclelinuxmanager210_client
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/oraclelinuxmanager210/client/x86_64/"
        <<: *foreman_products_defaults
      ### Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64) | ol7_x86_64_oraclelinuxmanager210_server ###
      - name: Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64)
        description: All Oracle Linux Manager (formerly Spacewalk) Server 2.10 packages released for Oracle Linux 7 (x86_64).
        label: ol7_x86_64_oraclelinuxmanager210_server
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/oraclelinuxmanager210/server/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_olm: "{{ [] |
  union( foreman_products_ol7_olm_spacewalk26 | default([]) if foreman_enable_ol7_olm_spacewalk26 else [] ) |
  union( foreman_products_ol7_olm_spacewalk27 | default([]) if foreman_enable_ol7_olm_spacewalk27 else [] ) |
  union( foreman_products_ol7_olm_spacewalk210 | default([]) if foreman_enable_ol7_olm_spacewalk210 else [] ) |
  union( foreman_products_ol7_olm_oraclelinuxmanager210 | default([]) if foreman_enable_ol7_olm_oraclelinuxmanager210 else [] )
  }}"


foreman_content_views_ol7_olm_spacewalk26:
  - name: cv_ol7_x86_64_spacewalk26_client
    repositories:
      - name: Spacewalk Client 2.6 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_spacewalk26_server
    repositories:
      - name: Spacewalk Server 2.6 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_olm_spacewalk27:
  - name: cv_ol7_x86_64_spacewalk27_client
    repositories:
      - name: Spacewalk Client 2.7 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_spacewalk27_server
    repositories:
      - name: Spacewalk Server 2.7 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_olm_spacewalk210:
  - name: cv_ol7_x86_64_spacewalk210_client
    repositories:
      - name: Spacewalk Client 2.10 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_spacewalk210_server
    repositories:
      - name: Spacewalk Server 2.10 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_olm_oraclelinuxmanager210:
  - name: cv_ol7_x86_64_oraclelinuxmanager210_client
    repositories:
      - name: Oracle Linux Manager (formerly Spacewalk) Client 2.10 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_oraclelinuxmanager210_server
    repositories:
      - name: Oracle Linux Manager (formerly Spacewalk) Server 2.10 for Oracle Linux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol7_olm: "{{ [] |
  union( foreman_content_views_ol7_olm_spacewalk26 | default([]) if foreman_enable_ol7_olm_spacewalk26 else [] ) |
  union( foreman_content_views_ol7_olm_spacewalk27 | default([]) if foreman_enable_ol7_olm_spacewalk27 else [] ) |
  union( foreman_content_views_ol7_olm_spacewalk210 | default([]) if foreman_enable_ol7_olm_spacewalk210 else [] ) |
  union( foreman_content_views_ol7_olm_oraclelinuxmanager210 | default([]) if foreman_enable_ol7_olm_oraclelinuxmanager210 else [] )
  }}"

