---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol9_uln_olm:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol9_uln_olm }}"
    repositories:
      ### Oracle Linux Manager 2.10 Client (x86_64) | ol9_x86_64_oraclelinuxmanager210_client ###
      - name: Oracle Linux Manager 2.10 Client (x86_64)
        description: Latest Oracle Linux Manager 2.10 Client packages for Oracle Linux 9 (x86_64)
        label: ol9_uln_x86_64_oraclelinuxmanager210_client
        url: uln://ol9_x86_64_oraclelinuxmanager210_client
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol9_uln_olm }}"


foreman_content_views_ol9_uln_olm:
  - name: cv_ol9_uln_x86_64_oraclelinuxmanager210_client
    organization: "{{ foreman_organization_ol9_uln_olm }}"
    repositories:
      - name: Oracle Linux Manager 2.10 Client (x86_64)
        product: Oracle Linux
    allow_promote: False

