---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol8_security_validation:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 8 Update 4 Security Validations packages (x86_64) | ol8_x86_64_u4_security_validation ###
      - name: Oracle Linux 8 Update 4 Security Validations packages (x86_64)
        description: Packages delivered for security validations, like FIPS or common criteria for Oracle Linux 8 Update 4 (x86_64).
        label: ol8_x86_64_u4_security_validation
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/4/security/validation/x86_64/"
        <<: *foreman_products_defaults


foreman_content_views_ol8_security_validation:
  - name: cv_ol8_x86_64_u4_security_validation
    repositories:
      - name: Oracle Linux 8 Update 4 Security Validations packages (x86_64)
        product: Oracle Linux
    allow_promote: False

