---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol9_uln_oci:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 9 OCI Included Packages (x86_64) | ol9_x86_64_oci_included ###
      - name: Oracle Linux 9 OCI Included Packages (x86_64)
        description: Oracle Linux 9 packages specifically for use in Oracle Cloud Infrastructure (x86_64)
        label: ol9_uln_x86_64_oci_included
        url: uln://ol9_x86_64_oci_included
        <<: *foreman_products_defaults


foreman_content_views_ol9_uln_oci:
  - name: cv_ol9_uln_x86_64_oci_included
    repositories:
      - name: Oracle Linux 9 OCI Included Packages (x86_64)
        product: Oracle Linux
    allow_promote: False

