---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol7_olcne:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      ### Oracle Linux Cloud Native Environment (x86_64) | ol7_x86_64_olcne ###
      - name: Oracle Linux Cloud Native Environment (x86_64)
        description: Latest packages for components of the Oracle Linux Cloud Native environment (x86_64)
        label: ol7_x86_64_olcne
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.1 (x86_64) | ol7_x86_64_olcne11 ###
      - name: Oracle Linux Cloud Native Environment 1.1 (x86_64)
        description: Packages for components of the 1.1 release of Oracle Linux Cloud Native environment (x86_64)
        label: ol7_x86_64_olcne11
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne11/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.2 - Oracle LInux 7 (x86_64) | ol7_x86_64_olcne12 ###
      - name: Oracle Linux Cloud Native Environment 1.2 - Oracle LInux 7 (x86_64)
        description: Packages for components of the 1.2 release of Oracle Linux Cloud Native environment for Oracle Linux 7 (x86_64)
        label: ol7_x86_64_olcne12
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne12/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.3 - Oracle LInux 7 (x86_64) | ol7_x86_64_olcne13 ###
      - name: Oracle Linux Cloud Native Environment 1.3 - Oracle LInux 7 (x86_64)
        description: Packages for components of the 1.3 release of Oracle Linux Cloud Native environment for Oracle Linux 7 (x86_64)
        label: ol7_x86_64_olcne13
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne13/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.4 - Oracle LInux 7 (x86_64) | ol7_x86_64_olcne14 ###
      - name: Oracle Linux Cloud Native Environment 1.4 - Oracle LInux 7 (x86_64)
        description: Packages for components of the 1.4 release of Oracle Linux Cloud Native environment for Oracle Linux 7 (x86_64)
        label: ol7_x86_64_olcne14
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne14/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Oracle Linux Cloud Native Environment 1.5 - Oracle LInux 7 (x86_64) | ol7_x86_64_olcne15 ###
      - name: Oracle Linux Cloud Native Environment 1.5 - Oracle LInux 7 (x86_64)
        description: Packages for components of the 1.5 release of Oracle Linux Cloud Native environment for Oracle Linux 7 (x86_64)
        label: ol7_x86_64_olcne15
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/olcne15/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_olcne }}"
      ### Developer Preview for Oracle Linux Cloud Native Environment (x86_64) | ol7_x86_64_developer_olcne ###
      - name: Developer Preview for Oracle Linux Cloud Native Environment (x86_64)
        description: Developer preview packages for components of the Oracle Linux Cloud Native environment (x86_64)
        label: ol7_x86_64_developer_olcne
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/developer/olcne/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol7_olcne }}"


foreman_content_views_ol7_olcne:
  - name: cv_ol7_x86_64_olcne
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: Oracle Linux Cloud Native Environment (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_olcne11
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: Oracle Linux Cloud Native Environment 1.1 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_olcne12
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: Oracle Linux Cloud Native Environment 1.2 - Oracle LInux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_olcne13
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: Oracle Linux Cloud Native Environment 1.3 - Oracle LInux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_olcne14
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: Oracle Linux Cloud Native Environment 1.4 - Oracle LInux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_olcne15
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: Oracle Linux Cloud Native Environment 1.5 - Oracle LInux 7 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol7_x86_64_developer_olcne
    organization: "{{ foreman_organization_ol7_olcne }}"
    repositories:
      - name: Developer Preview for Oracle Linux Cloud Native Environment (x86_64)
        product: Oracle Linux
    allow_promote: False

