---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol9_uln_virtualization_kvm_utils:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 9 KVM Utilities (x86_64) | ol9_x86_64_kvm_utils ###
      - name: Oracle Linux 9 KVM Utilities (x86_64)
        description: Latest Oracle Linux 9 KVM Utilities Packages (x86_64)
        label: ol9_uln_x86_64_kvm_utils
        url: uln://ol9_x86_64_kvm_utils
        <<: *foreman_products_defaults
      # ### Developer Preview of KVM Utilities for Oracle Linux 9 (x86_64) | ol9_x86_64_developer_kvm_utils ###
      # - name: Developer Preview of KVM Utilities for Oracle Linux 9 (x86_64)
      #   description: Latest KVM Utility packages for test and development for Oracle Linux 9 (x86_64).
      #   label: ol9_uln_x86_64_developer_kvm_utils
      #   url: uln://ol9_x86_64_developer_kvm_utils
      #   <<: *foreman_products_defaults

foreman_products_ol9_uln_virtualization: "{{ [] |
  union( foreman_products_ol9_uln_virtualization_kvm_utils | default([]) if foreman_enable_ol9_uln_virtualization_kvm_utils else [] )
  }}"


foreman_content_views_ol9_uln_virtualization_kvm_utils:
  - name: cv_ol9_uln_x86_64_kvm_utils
    repositories:
      - name: Oracle Linux 9 KVM Utilities (x86_64)
        product: Oracle Linux
    allow_promote: False
  # - name: cv_ol9_uln_x86_64_developer_kvm_utils
  #   repositories:
  #     - name: Developer Preview of KVM Utilities for Oracle Linux 9 (x86_64)
  #       product: Oracle Linux
  #   allow_promote: False

foreman_content_views_ol9_uln_virtualization: "{{ [] |
  union( foreman_content_views_ol9_uln_virtualization_kvm_utils | default([]) if foreman_enable_ol9_uln_virtualization_kvm_utils else [] )
  }}"

