---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol8_uln_am10:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol8_uln_am10 }}"
    repositories:
      ### Oracle Linux Automation Manager 1.0, based on the open source projects Ansible and AWX | ol8_x86_64_automation ###
      - name: Oracle Linux Automation Manager 1.0, based on the open source projects Ansible and AWX
        description: Oracle Linux Automation Manager 1.0, based on the open source projects Ansible and AWX.
        label: ol8_uln_x86_64_automation
        url: uln://ol8_x86_64_automation
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol8_uln_am10 }}"

foreman_products_ol8_uln_am20:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol8_uln_am20 }}"
    repositories:
      ### Oracle Linux Automation Manager 2.0, based on the open source projects Ansible and AWX | ol8_x86_64_automation2 ###
      - name: Oracle Linux Automation Manager 2.0, based on the open source projects Ansible and AWX
        description: Oracle Linux Automation Manager 2.0, based on the open source projects Ansible and AWX.
        label: ol8_uln_x86_64_automation2
        url: uln://ol8_x86_64_automation2
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol8_uln_am20 }}"

foreman_products_ol8_uln_am: "{{ [] |
  union( foreman_products_ol8_uln_am10 | default([]) if foreman_enable_ol8_uln_am10 else [] ) |
  union( foreman_products_ol8_uln_am20 | default([]) if foreman_enable_ol8_uln_am20 else [] )
  }}"


foreman_content_views_ol8_uln_am10:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_uln_x86_64_automation"
    organization: "{{ foreman_organization_ol8_uln_am10 }}"
    repositories:
      - name: Oracle Linux Automation Manager 1.0, based on the open source projects Ansible and AWX
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol8_uln_am20:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol8_uln_x86_64_automation2"
    organization: "{{ foreman_organization_ol8_uln_am20 }}"
    repositories:
      - name: Oracle Linux Automation Manager 2.0, based on the open source projects Ansible and AWX
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol8_uln_am: "{{ [] |
  union( foreman_content_views_ol8_uln_am10 | default([]) if foreman_enable_ol8_uln_am10 else [] ) |
  union( foreman_content_views_ol8_uln_am20 | default([]) if foreman_enable_ol8_uln_am20 else [] )
  }}"

