---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol8_mysql:
  - name: Oracle Linux
    label: OL
    repositories:
      ### MySQL 8.0 Connectors Community for Oracle Linux 8 (x86_64) | ol8_x86_64_MySQL80_connectors_community ###
      - name: MySQL 8.0 Connectors Community for Oracle Linux 8 (x86_64)
        description: Latest MySQL 8.0 Connectors Community packages for Oracle Linux 8 (x86_64).
        label: ol8_x86_64_MySQL80_connectors_community
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/MySQL80/connectors/community/x86_64/"
        <<: *foreman_products_defaults
      ### MySQL 8.0 for Oracle Linux 8 (x86_64) | ol8_x86_64_MySQL80_community ###
      - name: MySQL 8.0 for Oracle Linux 8 (x86_64)
        description: Latest MySQL 8.0 packages for Oracle Linux 8 (x86_64).
        label: ol8_x86_64_MySQL80_community
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/MySQL80/community/x86_64/"
        <<: *foreman_products_defaults
      ### MySQL 8.0 Tools Community for Oracle Linux 8 (x86_64) | ol8_x86_64_MySQL80_tools_community ###
      - name: MySQL 8.0 Tools Community for Oracle Linux 8 (x86_64)
        description: Latest MySQL 8.0 Tools Community packages for Oracle Linux 8 (x86_64).
        label: ol8_x86_64_MySQL80_tools_community
        url: "{{ foreman_repo_baseurl_oracle8 }}/OL8/MySQL80/tools/community/x86_64/"
        <<: *foreman_products_defaults


foreman_content_views_ol8_mysql:
  - name: cv_ol8_x86_64_MySQL80_connectors_community
    repositories:
      - name: MySQL 8.0 Connectors Community for Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_x86_64_MySQL80_community
    repositories:
      - name: MySQL 8.0 for Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_x86_64_MySQL80_tools_community
    repositories:
      - name: MySQL 8.0 Tools Community for Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False

