---

foreman_content_credentials_ol8_uln: []


foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  upstream_username: "{{ foreman_products_ol_uln_username | default('') }}"
  upstream_password: "{{ foreman_products_ol_uln_password | default('') }}"
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol8_uln:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 8 BaseOS Latest (x86_64) | ol8_x86_64_baseos_latest ###
      - name: Oracle Linux 8 BaseOS Latest (x86_64)
        description: Base operating system packages released for Oracle Linux 8 (x86_64) including the latest errata packages. (x86_64).
        label: ol8_uln_x86_64_baseos_latest
        url: uln://ol8_x86_64_baseos_latest
        <<: *foreman_products_defaults
      ### Oracle Linux 8 Application Stream Packages (x86_64) | ol8_x86_64_appstream ###
      - name: Oracle Linux 8 Application Stream Packages (x86_64)
        description: Application packages released for Oracle Linux 8 (x86_64) including the latest errata packages. (x86_64)
        label: ol8_uln_x86_64_appstream
        url: uln://ol8_x86_64_appstream
        <<: *foreman_products_defaults

      ### Oracle Linux 8 Addons (x86_64) | ol8_x86_64_addons ###
      - name: Oracle Linux 8 Addons (x86_64)
        description: Oracle Linux 8 Addons (x86_64).
        label: ol8_uln_x86_64_addons
        url: uln://ol8_x86_64_addons
        <<: *foreman_products_defaults
      ### Packages for creating test and development environments for Oracle Linux 8 (x86_64) | ol8_x86_64_developer ###
      - name: Packages for creating test and development environments for Oracle Linux 8 (x86_64)
        description: Latest packages for creating test and development environments - Oracle LInux 8 (x86_64)
        label: ol8_uln_x86_64_developer
        url: uln://ol8_x86_64_developer
        <<: *foreman_products_defaults
      ### EPEL Packages for creating test and development environments for Oracle Linux 8 (x86_64) | ol8_x86_64_developer_EPEL ###
      - name: EPEL Packages for creating test and development environments for Oracle Linux 8 (x86_64)
        description: Latest EPEL packages for creating test and development environments - Oracle LInux 8 (x86_64)
        label: ol8_uln_x86_64_developer_EPEL
        url: uln://ol8_x86_64_developer_EPEL
        <<: *foreman_products_defaults
      ### EPEL Modular Packages for Oracle Linux 8 (x86_64) | ol8_x86_64_developer_EPEL_modular ###
      - name: EPEL Modular Packages for Oracle Linux 8 (x86_64)
        description: Latest EPEL Modular packages for creating test and development environments - Oracle LInux 8 (x86_64)
        label: ol8_uln_x86_64_developer_EPEL_modular
        url: uln://ol8_x86_64_developer_EPEL_modular
        <<: *foreman_products_defaults
      ### CodeReady Linux Builder for Oracle Linux 8 (x86_64) | ol8_x86_64_codeready_builder ###
      - name: CodeReady Linux Builder for Oracle Linux 8 (x86_64)
        description: Repository of additional development and build tools for Oracle Linux 8 (x86_64) - (unsupported).
        label: ol8_uln_x86_64_codeready_builder
        url: uln://ol8_x86_64_codeready_builder
        <<: *foreman_products_defaults
      ### Oracle Linux 8 Distro Builder (x86_64) - Unsupported | ol8_x86_64_distro_builder ###
      - name: Oracle Linux 8 Distro Builder (x86_64) - Unsupported
        description: Latest packages for Oracle Linux 8 Distro Builder (x86_64) - Unsupported.
        label: ol8_uln_x86_64_distro_builder
        url: uln://ol8_x86_64_distro_builder
        <<: *foreman_products_defaults


foreman_content_views_ol8_uln:
  - name: cv_ol8_uln_x86_64_baseos_latest
    repositories:
      - name: Oracle Linux 8 BaseOS Latest (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_uln_x86_64_appstream
    repositories:
      - name: Oracle Linux 8 Application Stream Packages (x86_64)
        product: Oracle Linux
    allow_promote: False

  - name: cv_ol8_uln_x86_64_addons
    repositories:
      - name: Oracle Linux 8 Addons (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_uln_x86_64_developer
    repositories:
      - name: Packages for creating test and development environments for Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_uln_x86_64_developer_EPEL
    repositories:
      - name: EPEL Packages for creating test and development environments for Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_uln_x86_64_developer_EPEL_modular
    repositories:
      - name: EPEL Modular Packages for Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_uln_x86_64_codeready_builder
    repositories:
      - name: CodeReady Linux Builder for Oracle Linux 8 (x86_64)
        product: Oracle Linux
    allow_promote: False
  - name: cv_ol8_uln_x86_64_distro_builder
    repositories:
      - name: Oracle Linux 8 Distro Builder (x86_64) - Unsupported
        product: Oracle Linux
    allow_promote: False

  - name: ccv_ol8
    composite: True
    auto_publish: True
    components:
      - content_view: cv_ol8_uln_x86_64_baseos_latest
        latest: true
      - content_view: cv_ol8_uln_x86_64_appstream
        latest: true
      - content_view: cv_ol8_uln_x86_64_addons
        latest: true
      - content_view: cv_ol8_uln_x86_64_developer
        latest: true
      - content_view: cv_ol8_uln_x86_64_developer_EPEL
        latest: true
      - content_view: cv_ol8_uln_x86_64_developer_EPEL_modular
        latest: true
      - content_view: cv_ol8_uln_x86_64_codeready_builder
        latest: true
      - content_view: cv_ol8_uln_x86_64_distro_builder
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_cloud_init | default( foreman_operatingsystems_ol_template_cloud_init | default( foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_finish | default( foreman_operatingsystems_ol_template_finish | default( foreman_operatingsystems_el_template_finish | default('Kickstart default finish') ) ) }}"
    - template_kind: "host_init_config"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_host_init_config | default( foreman_operatingsystems_ol_template_host_init_config | default( foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    - template_kind: "iPXE"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_ipxe | default( foreman_operatingsystems_ol_template_ipxe | default( foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_provision | default( foreman_operatingsystems_ol_template_provision | default( foreman_operatingsystems_el_template_provision | default('Kickstart default') ) ) }}"
    - template_kind: "PXEGrub"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_pxegrub | default( foreman_operatingsystems_ol_template_pxegrub | default( foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_pxegrub2 | default( foreman_operatingsystems_ol_template_pxegrub2 | default( foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_pxelinux | default( foreman_operatingsystems_ol_template_pxelinux | default( foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_ol8_template_user_data | default( foreman_operatingsystems_ol_template_user_data | default( foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') ) ) }}"


foreman_operatingsystems_ol8_uln:
  - name: "OracleLinux"
    major: "8"
    minor: ""
    description: "Oracle Linux 8"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_ol8_uln:
  - name: Oracle Linux 8 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/OL/ol8_uln_x86_64_u8_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 8


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Oracle Linux"
  auto_attach: False
  # release_version: 8
  # service_level: Standard


foreman_activation_keys_ol8_uln:
  - name: ak_ol8
    content_view: ccv_ol8
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_OL_ol8_uln_x86_64_baseos_latest"
        override: default
      - label: "{{ foreman_organization }}_OL_ol8_uln_x86_64_appstream"
        override: default
      - label: "{{ foreman_organization }}_OL_ol8_uln_x86_64_addons"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol8_uln_x86_64_developer"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol8_uln_x86_64_developer_EPEL"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol8_uln_x86_64_developer_EPEL_modular"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol8_uln_x86_64_codeready_builder"
        override: disabled
      - label: "{{ foreman_organization }}_OL_ol8_uln_x86_64_distro_builder"
        override: disabled


foreman_sync_plan_products_ol8_uln: []

