---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol90:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol90 }}"
    repositories:
      ### Oracle Linux 9 BaseOS GA (x86_64) | ol9_x86_64_u0_baseos_base ###
      - name: Oracle Linux 9 BaseOS GA (x86_64)
        description: Base operating system packages released for Oracle Linux 9 (x86_64). No errata included
        label: ol9_x86_64_u0_baseos_base
        url: "{{ foreman_repo_baseurl_oracle9 }}/OL9/0/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol90 }}"

foreman_products_ol91:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol91 }}"
    repositories:
      ### Oracle Linux 9.1 BaseOS (x86_64) | ol9_x86_64_u1_baseos_base ###
      - name: Oracle Linux 9.1 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 9.1 (x86_64). No errata included
        label: ol9_x86_64_u1_baseos_base
        url: "{{ foreman_repo_baseurl_oracle9 }}/OL9/1/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol91 }}"

foreman_products_ol92:
  - name: Oracle Linux
    label: OL
    organization: "{{ foreman_organization_ol92 }}"
    repositories:
      ### Oracle Linux 9.2 BaseOS (x86_64) | ol9_x86_64_u2_baseos_base ###
      - name: Oracle Linux 9.2 BaseOS (x86_64)
        description: Base operating system packages released for Oracle Linux 9.2 (x86_64). No errata included
        label: ol9_x86_64_u2_baseos_base
        url: "{{ foreman_repo_baseurl_oracle9 }}/OL9/2/baseos/base/x86_64/"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_ol92 }}"

foreman_products_ol9_versions: "{{ [] |
  union( foreman_products_ol90 | default([]) if foreman_enable_ol90 else [] ) |
  union( foreman_products_ol91 | default([]) if foreman_enable_ol91 else [] ) |
  union( foreman_products_ol92 | default([]) if foreman_enable_ol92 else [] )
  }}"


foreman_content_views_ol90:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_x86_64_u0_baseos_base"
    organization: "{{ foreman_organization_ol90 }}"
    repositories:
      - name: Oracle Linux 9 BaseOS GA (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol91:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_x86_64_u1_baseos_base"
    organization: "{{ foreman_organization_ol91 }}"
    repositories:
      - name: Oracle Linux 9.1 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol92:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ol9_x86_64_u2_baseos_base"
    organization: "{{ foreman_organization_ol92 }}"
    repositories:
      - name: Oracle Linux 9.2 BaseOS (x86_64)
        product: Oracle Linux
    allow_promote: False

foreman_content_views_ol9_versions: "{{ [] |
  union( foreman_content_views_ol90 | default([]) if foreman_enable_ol90 else [] ) |
  union( foreman_content_views_ol91 | default([]) if foreman_enable_ol91 else [] ) |
  union( foreman_content_views_ol92 | default([]) if foreman_enable_ol92 else [] )
  }}"


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_cloud_init | default( foreman_operatingsystems_ol_template_cloud_init | default( foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_finish | default( foreman_operatingsystems_ol_template_finish | default( foreman_operatingsystems_el_template_finish | default('Kickstart default finish') ) ) }}"
    - template_kind: "host_init_config"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_host_init_config | default( foreman_operatingsystems_ol_template_host_init_config | default( foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    - template_kind: "iPXE"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_ipxe | default( foreman_operatingsystems_ol_template_ipxe | default( foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_provision | default( foreman_operatingsystems_ol_template_provision | default( foreman_operatingsystems_el_template_provision | default('Kickstart default') ) ) }}"
    - template_kind: "PXEGrub"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_pxegrub | default( foreman_operatingsystems_ol_template_pxegrub | default( foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_pxegrub2 | default( foreman_operatingsystems_ol_template_pxegrub2 | default( foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_pxelinux | default( foreman_operatingsystems_ol_template_pxelinux | default( foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_ol9_template_user_data | default( foreman_operatingsystems_ol_template_user_data | default( foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') ) ) }}"


foreman_operatingsystems_ol90:
  - name: "OracleLinux"
    major: "9"
    minor: "0"
    description: "Oracle Linux 9.0"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol91:
  - name: "OracleLinux"
    major: "9"
    minor: "1"
    description: "Oracle Linux 9.1"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol92:
  - name: "OracleLinux"
    major: "9"
    minor: "2"
    description: "Oracle Linux 9.2"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol9_versions: "{{ [] |
  union( foreman_operatingsystems_ol90 | default([]) if foreman_enable_ol90 else [] ) |
  union( foreman_operatingsystems_ol91 | default([]) if foreman_enable_ol91 else [] ) |
  union( foreman_operatingsystems_ol92 | default([]) if foreman_enable_ol92 else [] )
  }}"


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_ol90:
  - name: Oracle Linux 9.0 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_linux/ol9_ga_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 9.0

foreman_installation_media_ol91:
  - name: Oracle Linux 9.1 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_linux/ol9_u1_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 9.1

foreman_installation_media_ol92:
  - name: Oracle Linux 9.2 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_linux/ol9_u2_baseos_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 9.2

foreman_installation_media_ol9_versions: "{{ [] |
  union( foreman_installation_media_ol90 | default([]) if foreman_enable_ol90 else [] ) |
  union( foreman_installation_media_ol91 | default([]) if foreman_enable_ol91 else [] ) |
  union( foreman_installation_media_ol92 | default([]) if foreman_enable_ol92 else [] )
  }}"

