---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-oracle
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_ol7_0:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 GA installation media copy (x86_64) | ol7_x86_64_u0_base ###
      - name: Oracle Linux 7 GA installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 GA (x86_64). No errata included
        label: ol7_x86_64_u0_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/0/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_1:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 1 installation media copy (x86_64) | ol7_x86_64_u1_base ###
      - name: Oracle Linux 7 Update 1 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 1 (x86_64). No errata included
        label: ol7_x86_64_u1_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/1/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_2:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 2 installation media copy (x86_64) | ol7_x86_64_u2_base ###
      - name: Oracle Linux 7 Update 2 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 2 (x86_64). No errata included
        label: ol7_x86_64_u2_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/2/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_3:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 3 installation media copy (x86_64) | ol7_x86_64_u3_base ###
      - name: Oracle Linux 7 Update 3 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 3 (x86_64). No errata included
        label: ol7_x86_64_u3_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/3/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_4:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 4 installation media copy (x86_64) | ol7_x86_64_u4_base ###
      - name: Oracle Linux 7 Update 4 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 4 (x86_64). No errata included
        label: ol7_x86_64_u4_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/4/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_5:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 5 installation media copy (x86_64) | ol7_x86_64_u5_base ###
      - name: Oracle Linux 7 Update 5 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 5 (x86_64). No errata included
        label: ol7_x86_64_u5_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/5/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_6:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 6 installation media copy (x86_64) | ol7_x86_64_u6_base ###
      - name: Oracle Linux 7 Update 6 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 6 (x86_64). No errata included
        label: ol7_x86_64_u6_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/6/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_7:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 7 installation media copy (x86_64) | ol7_x86_64_u7_base ###
      - name: Oracle Linux 7 Update 7 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 7 (x86_64). No errata included
        label: ol7_x86_64_u7_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/7/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_8:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 8 installation media copy (x86_64) | ol7_x86_64_u8_base ###
      - name: Oracle Linux 7 Update 8 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 8 (x86_64). No errata included
        label: ol7_x86_64_u8_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/8/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_9:
  - name: Oracle Linux
    label: OL
    repositories:
      ### Oracle Linux 7 Update 9 installation media copy (x86_64) | ol7_x86_64_u9_base ###
      - name: Oracle Linux 7 Update 9 installation media copy (x86_64)
        description: All packages released for Oracle Linux 7 Update 9 (x86_64). No errata included
        label: ol7_x86_64_u9_base
        url: "{{ foreman_repo_baseurl_oracle7 }}/OL7/9/base/x86_64/"
        <<: *foreman_products_defaults

foreman_products_ol7_versions: "{{ [] |
  union( foreman_products_ol7_0 | default([]) if foreman_enable_ol7_0 else [] ) |
  union( foreman_products_ol7_1 | default([]) if foreman_enable_ol7_1 else [] ) |
  union( foreman_products_ol7_2 | default([]) if foreman_enable_ol7_2 else [] ) |
  union( foreman_products_ol7_3 | default([]) if foreman_enable_ol7_3 else [] ) |
  union( foreman_products_ol7_4 | default([]) if foreman_enable_ol7_4 else [] ) |
  union( foreman_products_ol7_5 | default([]) if foreman_enable_ol7_5 else [] ) |
  union( foreman_products_ol7_6 | default([]) if foreman_enable_ol7_6 else [] ) |
  union( foreman_products_ol7_7 | default([]) if foreman_enable_ol7_7 else [] ) |
  union( foreman_products_ol7_8 | default([]) if foreman_enable_ol7_8 else [] ) |
  union( foreman_products_ol7_9 | default([]) if foreman_enable_ol7_9 else [] )
  }}"


# foreman_content_views_ol7_0:
#   - name: cv_ol7_x86_64_u0_base
#     repositories:
#       - name: Oracle Linux 7 GA installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_1:
#   - name: cv_ol7_x86_64_u1_base
#     repositories:
#       - name: Oracle Linux 7 Update 1 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_2:
#   - name: cv_ol7_x86_64_u2_base
#     repositories:
#       - name: Oracle Linux 7 Update 2 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_3:
#   - name: ol7_x86_64_u3_base
#     repositories:
#       - name: Oracle Linux 7 Update 3 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_4:
#   - name: cv_ol7_x86_64_u4_base
#     repositories:
#       - name: Oracle Linux 7 Update 4 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_5:
#   - name: cv_ol7_x86_64_u5_base
#     repositories:
#       - name: Oracle Linux 7 Update 5 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_6:
#   - name: cv_ol7_x86_64_u6_base
#     repositories:
#       - name: Oracle Linux 7 Update 6 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_7:
#   - name: cv_ol7_x86_64_u7_base
#     repositories:
#       - name: Oracle Linux 7 Update 7 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_8:
#   - name: cv_ol7_x86_64_u8_base
#     repositories:
#       - name: Oracle Linux 7 Update 8 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

# foreman_content_views_ol7_9:
#   - name: cv_ol7_x86_64_u9_base
#     repositories:
#       - name: Oracle Linux 7 Update 9 installation media copy (x86_64)
#         product: Oracle Linux
#     allow_promote: False

foreman_content_views_ol7_versions: "{{ [] |
  union( foreman_content_views_ol7_0 | default([]) if foreman_enable_ol7_0 else [] ) |
  union( foreman_content_views_ol7_1 | default([]) if foreman_enable_ol7_1 else [] ) |
  union( foreman_content_views_ol7_2 | default([]) if foreman_enable_ol7_2 else [] ) |
  union( foreman_content_views_ol7_3 | default([]) if foreman_enable_ol7_3 else [] ) |
  union( foreman_content_views_ol7_4 | default([]) if foreman_enable_ol7_4 else [] ) |
  union( foreman_content_views_ol7_5 | default([]) if foreman_enable_ol7_5 else [] ) |
  union( foreman_content_views_ol7_6 | default([]) if foreman_enable_ol7_6 else [] ) |
  union( foreman_content_views_ol7_7 | default([]) if foreman_enable_ol7_7 else [] ) |
  union( foreman_content_views_ol7_8 | default([]) if foreman_enable_ol7_8 else [] ) |
  union( foreman_content_views_ol7_9 | default([]) if foreman_enable_ol7_9 else [] )
  }}"


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_cloud_init | default( foreman_operatingsystems_ol_template_cloud_init | default( foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_finish | default( foreman_operatingsystems_ol_template_finish | default( foreman_operatingsystems_el_template_finish | default('Kickstart default finish') ) ) }}"
    - template_kind: "host_init_config"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_host_init_config | default( foreman_operatingsystems_ol_template_host_init_config | default( foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    - template_kind: "iPXE"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_ipxe | default( foreman_operatingsystems_ol_template_ipxe | default( foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_provision | default( foreman_operatingsystems_ol_template_provision | default( foreman_operatingsystems_el_template_provision | default('Kickstart default') ) ) }}"
    - template_kind: "PXEGrub"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_pxegrub | default( foreman_operatingsystems_ol_template_pxegrub | default( foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_pxegrub2 | default( foreman_operatingsystems_ol_template_pxegrub2 | default( foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_pxelinux | default( foreman_operatingsystems_ol_template_pxelinux | default( foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_ol7_template_user_data | default( foreman_operatingsystems_ol_template_user_data | default( foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') ) ) }}"


foreman_operatingsystems_ol7_0:
  - name: "OracleLinux"
    major: "7"
    minor: "0"
    description: "Oracle Linux 7.0"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_1:
  - name: "OracleLinux"
    major: "7"
    minor: "1"
    description: "Oracle Linux 7.1"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_2:
  - name: "OracleLinux"
    major: "7"
    minor: "2"
    description: "Oracle Linux 7.2"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_3:
  - name: "OracleLinux"
    major: "7"
    minor: "3"
    description: "Oracle Linux 7.3"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_4:
  - name: "OracleLinux"
    major: "7"
    minor: "4"
    description: "Oracle Linux 7.4"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_5:
  - name: "OracleLinux"
    major: "7"
    minor: "5"
    description: "Oracle Linux 7.5"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_6:
  - name: "OracleLinux"
    major: "7"
    minor: "6"
    description: "Oracle Linux 7.6"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_7:
  - name: "OracleLinux"
    major: "7"
    minor: "7"
    description: "Oracle Linux 7.7"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_8:
  - name: "OracleLinux"
    major: "7"
    minor: "8"
    description: "Oracle Linux 7.8"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_9:
  - name: "OracleLinux"
    major: "7"
    minor: "9"
    description: "Oracle Linux 7.9"
    <<: *foreman_operatingsystems_defaults

foreman_operatingsystems_ol7_versions: "{{ [] |
  union( foreman_operatingsystems_ol7_0 | default([]) if foreman_enable_ol7_0 else [] ) |
  union( foreman_operatingsystems_ol7_1 | default([]) if foreman_enable_ol7_1 else [] ) |
  union( foreman_operatingsystems_ol7_2 | default([]) if foreman_enable_ol7_2 else [] ) |
  union( foreman_operatingsystems_ol7_3 | default([]) if foreman_enable_ol7_3 else [] ) |
  union( foreman_operatingsystems_ol7_4 | default([]) if foreman_enable_ol7_4 else [] ) |
  union( foreman_operatingsystems_ol7_5 | default([]) if foreman_enable_ol7_5 else [] ) |
  union( foreman_operatingsystems_ol7_6 | default([]) if foreman_enable_ol7_6 else [] ) |
  union( foreman_operatingsystems_ol7_7 | default([]) if foreman_enable_ol7_7 else [] ) |
  union( foreman_operatingsystems_ol7_8 | default([]) if foreman_enable_ol7_8 else [] ) |
  union( foreman_operatingsystems_ol7_9 | default([]) if foreman_enable_ol7_9 else [] )
  }}"


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_ol7_0:
  - name: Oracle Linux 7.0
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_ga_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.0

foreman_installation_media_ol7_1:
  - name: Oracle Linux 7.1
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u1_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.1

foreman_installation_media_ol7_2:
  - name: Oracle Linux 7.2
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u2_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.2

foreman_installation_media_ol7_3:
  - name: Oracle Linux 7.3
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u3_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.3

foreman_installation_media_ol7_4:
  - name: Oracle Linux 7.4
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u4_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.4

foreman_installation_media_ol7_5:
  - name: Oracle Linux 7.5
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u5_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.5

foreman_installation_media_ol7_6:
  - name: Oracle Linux 7.6
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u6_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.6

foreman_installation_media_ol7_7:
  - name: Oracle Linux 7.7
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u7_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.7

foreman_installation_media_ol7_8:
  - name: Oracle Linux 7.8
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u8_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.8

foreman_installation_media_ol7_9:
  - name: Oracle Linux 7.9
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Oracle_Linux/ol7_u9_base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Oracle Linux 7.9

foreman_installation_media_ol7_versions: "{{ [] |
  union( foreman_installation_media_ol7_0 | default([]) if foreman_enable_ol7_0 else [] ) |
  union( foreman_installation_media_ol7_1 | default([]) if foreman_enable_ol7_1 else [] ) |
  union( foreman_installation_media_ol7_2 | default([]) if foreman_enable_ol7_2 else [] ) |
  union( foreman_installation_media_ol7_3 | default([]) if foreman_enable_ol7_3 else [] ) |
  union( foreman_installation_media_ol7_4 | default([]) if foreman_enable_ol7_4 else [] ) |
  union( foreman_installation_media_ol7_5 | default([]) if foreman_enable_ol7_5 else [] ) |
  union( foreman_installation_media_ol7_6 | default([]) if foreman_enable_ol7_6 else [] ) |
  union( foreman_installation_media_ol7_7 | default([]) if foreman_enable_ol7_7 else [] ) |
  union( foreman_installation_media_ol7_8 | default([]) if foreman_enable_ol7_8 else [] ) |
  union( foreman_installation_media_ol7_9 | default([]) if foreman_enable_ol7_9 else [] )
  }}"

