---

foreman_content_credentials_template_el7:
  - name: RPM-GPG-KEY-Template-7
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_template ~ '/RPM-GPG-KEY-Template-7', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-Template-7') }}"


foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Template-7
  download_policy: on_demand
  # download_policy: immediate
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_template_el7:
  - name: Template Product
    label: Template
    organization: "{{ foreman_organization_template_el7 }}"
    repositories:
      - name: Template Product EL7
        label: template-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_template_el7 }}/7/x86_64/"
        organization: "{{ foreman_organization_template_el7 }}"


foreman_content_views_template_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}template_el7"
    organization: "{{ foreman_organization_template_el7 }}"
    repositories:
      - name: Template Product EL7
        product: Template Product
    allow_promote: "{{ foreman_cv_allow_promote_template_el7 }}"

  - name: "{{ foreman_ccv_prefix | default('ccv_') }}template_el7"
    organization: "{{ foreman_organization_template_el7 }}"
    composite: True
    auto_publish: True
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}template_el7"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"


foreman_operatingsystems_template7:
  - name: "Template"
    major: "7"
    minor: ""
    description: "Template 7"
    default_templates: "{{ foreman_operatingsystems_template7_default_templates | default( foreman_operatingsystems_template_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"
  # operatingsystems:
  #   - Template 7


foreman_installation_media_template7:
  - name: Template EL7
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Template/template-el7/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Template 7


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Rocky Linux"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  # release_version: 7Server
  # service_level: Standard


foreman_activation_keys_template_el7:
  - name: ak_template_el7
    organization: "{{ foreman_organization_template_el7 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}template_el7"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_Template_template_el7"
        override: default


foreman_sync_plan_products_template_el7:
  - Template Product

