---

foreman_content_credentials_template_el9:
  - name: RPM-GPG-KEY-Template-9
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_template ~ '/RPM-GPG-KEY-Template-9', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-Template-9') }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Template-9
  download_policy: on_demand
  # download_policy: immediate
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_template_el9:
  - name: Template Product
    label: Template
    repositories:
      - name: Template Product EL9
        label: template-el9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_template_el9 }}/9/x86_64/"

foreman_content_views_template_el9:
  - name: cv_template_el9
    repositories:
      - name: Template Product EL9
        product: Template Product
    allow_promote: False

foreman_activation_keys_template_el9: []

foreman_sync_plan_products_template_el9:
  - Template Product

