---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: ATIX-GPG-KEY
  download_policy: "{{ foreman_products_defaults_download_policy_atix }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_atix }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_atix | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_atix }}"
  unprotected: "{{ foreman_products_defaults_unprotected_atix | bool }}"

foreman_products_defaults_sles: &foreman_products_defaults_sles
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_atix_sles }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_atix_sles }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_atix_sles | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_atix_sles }}"
  unprotected: "{{ foreman_products_defaults_unprotected_atix_sles | bool }}"


foreman_products_atix_sles12:
  - name: ATIX
    label: ATIX
    organization: "{{ foreman_organization_atix_sles12 }}"
    repositories:
      - name: ATIX Subscription Manager for SLES 12
        label: atix-sles12
        <<: *foreman_products_defaults_sles
        url: "{{ foreman_repo_baseurl_atix_sles12 }}/SLES12SP5/"
        organization: "{{ foreman_organization_atix_sles12 }}"

foreman_products_atix_sles15:
  - name: ATIX
    label: ATIX
    organization: "{{ foreman_organization_atix_sles15 }}"
    repositories:
      - name: ATIX Subscription Manager for SLES 15
        label: atix-sles15
        <<: *foreman_products_defaults_sles
        url: "{{ foreman_repo_baseurl_atix_sles15 }}/SLES15SP5/"
        organization: "{{ foreman_organization_atix_sles15 }}"


foreman_content_views_atix_sles12:
  - name: "{{ foreman_cv_prefix | default('cv_') }}atix_sles12"
    organization: "{{ foreman_organization_atix_sles12 }}"
    repositories:
      - name: ATIX Subscription Manager for SLES 12
        product: ATIX
    allow_promote: False

foreman_content_views_atix_sles15:
  - name: "{{ foreman_cv_prefix | default('cv_') }}atix_sles15"
    organization: "{{ foreman_organization_atix_sles15 }}"
    repositories:
      - name: ATIX Subscription Manager for SLES 15
        product: ATIX
    allow_promote: False


foreman_content_credentials_atix_sles_main: []
foreman_content_credentials_atix_sles: "{{ ( foreman_content_credentials_atix_sles_main | default([]) if foreman_enable_atix_sles | bool else [] ) |
  union( foreman_content_credentials_atix_sles12 | default([]) if foreman_enable_atix_sles12 | bool else [] ) |
  union( foreman_content_credentials_atix_sles15 | default([]) if foreman_enable_atix_sles15 | bool else [] )
  }}"

foreman_products_atix_sles_main: []
foreman_products_atix_sles: "{{ ( foreman_products_atix_sles_main | default([]) if foreman_enable_atix_sles | bool else [] ) |
  union( foreman_products_atix_sles12 | default([]) if foreman_enable_atix_sles12 | bool else [] ) |
  union( foreman_products_atix_sles15 | default([]) if foreman_enable_atix_sles15 | bool else [] )
  }}"

foreman_content_views_atix_sles_main: []
foreman_content_views_atix_sles: "{{ ( foreman_content_views_atix_sles_main | default([]) if foreman_enable_atix_sles | bool else [] ) |
  union( foreman_content_views_atix_sles12 | default([]) if foreman_enable_atix_sles12 | bool else [] ) |
  union( foreman_content_views_atix_sles15 | default([]) if foreman_enable_atix_sles15 | bool else [] )
  }}"

foreman_operatingsystems_atix_sles_main: []
foreman_operatingsystems_atix_sles: "{{ ( foreman_operatingsystems_atix_sles_main | default([]) if foreman_enable_atix_sles | bool else [] ) |
  union( foreman_operatingsystems_atix_sles12 | default([]) if foreman_enable_atix_sles12 | bool else [] ) |
  union( foreman_operatingsystems_atix_sles15 | default([]) if foreman_enable_atix_sles15 | bool else [] )
  }}"

foreman_installation_media_atix_sles_main: []
foreman_installation_media_atix_sles: "{{ ( foreman_installation_media_atix_sles_main | default([]) if foreman_enable_atix_sles | bool else [] ) |
  union( foreman_installation_media_atix_sles12 | default([]) if foreman_enable_atix_sles12 | bool else [] ) |
  union( foreman_installation_media_atix_sles15 | default([]) if foreman_enable_atix_sles15 | bool else [] )
  }}"

foreman_activation_keys_atix_sles_main: []
foreman_activation_keys_atix_sles: "{{ ( foreman_activation_keys_atix_sles_main | default([]) if foreman_enable_atix_sles | bool else [] ) |
  union( foreman_installation_media_atix_sles12 | default([]) if foreman_enable_atix_sles12 | bool else [] ) |
  union( foreman_installation_media_atix_sles15 | default([]) if foreman_enable_atix_sles15 | bool else [] )
  }}"

foreman_sync_plan_products_atix_sles_main: []
foreman_sync_plan_products_atix_sles: "{{ ( foreman_sync_plan_products_atix_sles_main | default([]) if foreman_enable_atix_sles | bool else [] ) |
  union( foreman_installation_media_atix_sles12 | default([]) if foreman_enable_atix_sles12 | bool else [] ) |
  union( foreman_installation_media_atix_sles15 | default([]) if foreman_enable_atix_sles15 | bool else [] )
  }}"

