---
# debug tasks file for foreman

- name: "Debug | Get status info"
  theforeman.foreman.status_info:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
  register: foreman_status_info
  tags: [ "foreman_debug", "katello_debug" ]

- name: "Debug | Show status info"
  debug:
    var: foreman_status_info
  tags: [ "foreman_debug", "katello_debug" ]

- name: "Debug | Show organizations list"
  debug:
    msg: "{{ foreman_organizations | default([]) | map(attribute='name') | list }}"
  tags: [ "foreman_debug", "katello_debug" ]

- name: "Debug | Show locations list"
  debug:
    msg: "{{ foreman_locations | default([]) | map(attribute='name') | list }}"
  tags: [ "foreman_debug", "katello_debug" ]

- name: "Debug | Show operatingsystems"
  debug:
    var: foreman_operatingsystems | default([])
  tags: [ "foreman_debug", "katello_debug" ]

- name: "Debug | Show partition tables"
  debug:
    var: foreman_partition_tables | default([])
  tags: [ "foreman_debug", "katello_debug" ]

- name: "Debug | Show provisioning templates"
  debug:
    var: foreman_provisioning_templates | default([])
  tags: [ "foreman_debug", "katello_debug" ]

# - name: "Debug | Search for possible repository sets of a product"
#   theforeman.foreman.resource_info:
#     username: "{{ foreman_username | default(omit) }}"
#     password: "{{ foreman_password | default(omit) }}"
#     server_url: "{{ foreman_server_url | default(omit) }}"
#     organization: "Framed"
#     resource: repository_sets
#     search: product_name="Red Hat Enterprise Linux for x86_64"
#   register: data
#   tags: [ "katello_debug" ]

# - name: "Debug | Output found repository sets, see the contentUrl section for possible repository substitutions"
#   debug:
#     var: data
#   tags: [ "katello_debug" ]

- name: "Debug | Show products"
  debug:
    var: foreman_products | default([])
  tags: [ "katello_debug" ]

