---
# infrastructure section configuration tasks file for foreman

- name: "Configuration | Set up smart proxies"
  theforeman.foreman.smart_proxy:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    name: "{{ foreman_smart_proxies_item.name }}"
    url: "{{ foreman_smart_proxies_item.url | default( 'https://' ~ foreman_smart_proxies_item.name ~ ':' ~ foreman_proxy_https_port | default(9090) ) }}"
    organizations: "{{ foreman_smart_proxies_item.organizations | default(omit) }}"
    locations: "{{ foreman_smart_proxies_item.locations | default('omit') }}"
    lifecycle_environments: "{{ foreman_smart_proxies_item.lifecycle_environments | default(omit) }}"
    download_policy: "{{ foreman_smart_proxies_item.download_policy  | default(omit) }}"
    state: "{{ foreman_smart_proxies_item.state | default('present') }}"
  loop: "{{ foreman_smart_proxies | default([]) }}"
  loop_control:
    loop_var: "foreman_smart_proxies_item"
    label: "{{ foreman_smart_proxies_item.name }}"
  tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

- name: "Configuration | Include theforeman.foreman.domains role"
  ansible.builtin.import_role:
    name: theforeman.foreman.domains
  tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

- name: "Configuration | Include theforeman.foreman.subnets role"
  ansible.builtin.import_role:
    name: theforeman.foreman.subnets
  tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

### Compute resources need to be configured after provisioning configuration

