---
# infrastructure compute section configuration tasks file for foreman

# Disabled - collection role does not support attributes:
#            - updated_name
# - name: "Configuration | Include theforeman.foreman.compute_resources role"
#   ansible.builtin.import_role:
#     name: theforeman.foreman.compute_resources
#   tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

- name: "Configuration | Create compute resources"
  theforeman.foreman.compute_resource:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    name: "{{ foreman_compute_resources_item.name }}"
    updated_name: "{{ foreman_compute_resources_item.updated_name | default(omit) }}"
    description: "{{ foreman_compute_resources_item.description | default(omit) }}"
    organizations: "{{ foreman_compute_resources_item.organizations | default(omit) }}"
    locations: "{{ foreman_compute_resources_item.locations | default('omit') }}"
    provider: "{{ foreman_compute_resources_item.provider | default(omit) }}"
    provider_params: "{{ foreman_compute_resources_item.provider_params | default(omit) }}"
    state: "{{ foreman_compute_resources_item.state | default('present') }}"
  loop: "{{ foreman_compute_resources | default([]) }}"
  loop_control:
    loop_var: "foreman_compute_resources_item"
    label: "{{ foreman_compute_resources_item.name }}"
  register: foreman_compute_resources_tasks
  tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

- name: "Configuration | Create images for compute resources"
  theforeman.foreman.image:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    name: "{{ foreman_compute_resources_item.1.name }}"
    architecture: "{{ foreman_compute_resources_item.1.architecture | default(omit) }}"
    compute_resource: "{{ foreman_compute_resources_item.0.name | default(omit) }}"
    image_password: "{{ foreman_compute_resources_item.1.image_password | default(omit) }}"
    image_username: "{{ foreman_compute_resources_item.1.image_username | default(omit) }}"
    operatingsystem: "{{ foreman_compute_resources_item.1.operatingsystem | default(omit) }}"
    user_data: "{{ foreman_compute_resources_item.1.user_data | default(omit) }}"
    uuid: "{{ foreman_compute_resources_item.1.uuid | default(omit) }}"
    state: "{{ foreman_compute_resources_item.1.state | default('present') }}"
  loop: "{{ foreman_compute_resources | subelements('images', { 'skip_missing': True }) }}"
  loop_control:
    loop_var: "foreman_compute_resources_item"
    label: "{{ foreman_compute_resources_item.name }}"
  register: foreman_compute_resources_images_tasks
  tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

# Disabled - collection role does not support attributes:
#            - updated_name
# - name: "Configuration | Include theforeman.foreman.compute_profiles role"
#   ansible.builtin.import_role:
#     name: theforeman.foreman.compute_profiles
#   tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

- name: "Configuration | create compute profiles"
  theforeman.foreman.compute_profile:
    username: "{{ foreman_username | default(omit) }}"
    password: "{{ foreman_password | default(omit) }}"
    server_url: "{{ foreman_server_url | default(omit) }}"
    validate_certs: "{{ foreman_validate_certs | default(omit) }}"
    name: "{{ foreman_compute_profiles_item.name }}"
    updated_name: "{{ foreman_compute_profiles_item.updated_name | default(omit) }}"
    compute_attributes: "{{ foreman_compute_profiles_item.compute_attributes | default(omit) }}"
    state: "{{ foreman_compute_profiles_item.state | default('present') }}"
  loop: "{{ foreman_compute_profiles | default([]) }}"
  loop_control:
    loop_var: "foreman_compute_profiles_item"
    label: "{{ foreman_compute_profiles_item.name }}"
  register: foreman_compute_profiles_tasks
  tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

# - name: "DEBUG | Show foreman_compute_resources_tasks"
#   ansible.builtin.debug:
#     var: foreman_compute_resources_tasks
#   tags: [ "foreman", "katello", "debug", "configuration", "foreman_config_infrastructure" ]

# - name: "DEBUG | Show foreman_compute_resources_images_tasks"
#   ansible.builtin.debug:
#     var: foreman_compute_resources_images_tasks
#   tags: [ "foreman", "katello", "debug", "configuration", "foreman_config_infrastructure" ]

- name: "DEBUG | Show foreman_compute_profiles_tasks"
  ansible.builtin.debug:
    var: foreman_compute_profiles_tasks
  tags: [ "foreman", "katello", "debug", "configuration", "foreman_config_infrastructure" ]

