---
# tasks file for foreman

- name: "Configuration | Import content roles"
  ansible.builtin.include_role:
    name: "{{ item }}"
    public: true
    apply:
      tags: [ "always" ]
  loop: "{{ foreman_content_roles | default([]) }}"
  tags: [ "foreman", "katello", "configuration", "always" ]

- name: "Debug | Include debug tasks"
  ansible.builtin.include_tasks: foreman_debug.yml
  tags: [ "foreman_debug", "katello_debug" ]

- name: "Configuration | Include Administer section configuration tasks"
  ansible.builtin.include_tasks: foreman_config_administer.yml
  tags: [ "foreman", "katello", "configuration", "foreman_config_administer" ]

- name: "Configuration | Include Infrastructure section configuration tasks"
  ansible.builtin.include_tasks: foreman_config_infrastructure.yml
  tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

- name: "Configuration | Include Hosts section Provisioning configuration tasks"
  ansible.builtin.include_tasks: foreman_config_provisioning.yml
  tags: [ "foreman", "katello", "configuration", "foreman_config_provisioning" ]

- name: "Configuration | Include Hosts section Templates configuration tasks"
  ansible.builtin.include_tasks: foreman_config_templates.yml
  tags: [ "foreman", "katello", "configuration", "foreman_config_templates" ]

- name: "Configuration | Include Infrastructure section compute configuration tasks"
  ansible.builtin.include_tasks: foreman_config_infrastructure_compute.yml
  tags: [ "foreman", "katello", "configuration", "foreman_config_infrastructure" ]

- name: "Configuration | Include Configure section configuration tasks"
  ansible.builtin.include_tasks: foreman_config_configuration.yml
  tags: [ "foreman", "katello", "configuration", "foreman_config_configuration" ]


- name: "Configuration | Include Content section configuration tasks"
  ansible.builtin.include_tasks: foreman_config_content.yml
  tags: [ "katello", "configuration", "foreman_config_content" ]


- name: "Debug | Content Publish | Include Content publish debug tasks"
  ansible.builtin.include_tasks: foreman_content_publish_debug.yml
  when:
    foreman_publish_content | default(false) | bool
  tags: [ "katello", "configuration", "katello_publish_debug" ]

- name: "Content Publish | Include Content publish tasks"
  ansible.builtin.include_tasks: foreman_content_publish.yml
  when:
    foreman_publish_content | default(false) | bool
  tags: [ "katello", "configuration", "katello_publish" ]

- name: "Debug | Content Promote | Include Content promote debug tasks"
  ansible.builtin.include_tasks: foreman_content_promote_debug.yml
  when:
    foreman_promote_content | default(false) | bool
  tags: [ "katello", "configuration", "katello_promote_debug" ]

- name: "Content Promote | Include Content promote tasks"
  ansible.builtin.include_tasks: foreman_content_promote.yml
  when:
    foreman_promote_content | default(false) | bool
  tags: [ "katello", "configuration", "katello_promote" ]

- name: "Content Cleanup | Include Content cleanup tasks"
  ansible.builtin.include_tasks: foreman_content_cleanup.yml
  when:
    foreman_cleanup_content | default(false) | bool
  tags: [ "katello", "configuration", "katello_cleanup" ]

