---
# fdefaults file for foreman_content_ubuntu

foreman_enable_ubuntu: false
foreman_enable_ubuntu1804: false
foreman_enable_ubuntu2004: "{{ foreman_enable_ubuntu | bool }}"
foreman_enable_ubuntu2204: "{{ foreman_enable_ubuntu | bool }}"


foreman_repo_baseurl_ubuntu: http://archive.ubuntu.com/ubuntu
foreman_repo_baseurl_ubuntu1804: "{{ foreman_repo_baseurl_ubuntu }}"
foreman_repo_baseurl_ubuntu2004: "{{ foreman_repo_baseurl_ubuntu }}"
foreman_repo_baseurl_ubuntu2204: "{{ foreman_repo_baseurl_ubuntu }}"


foreman_content_credentials_ubuntu_main: []
foreman_content_credentials_ubuntu: "{{ foreman_content_credentials_ubuntu_main | default([]) if foreman_enable_ubuntu | bool else [] |
  union( foreman_content_credentials_ubuntu1804 | default([]) if foreman_enable_ubuntu1804 | bool else [] ) |
  union( foreman_content_credentials_ubuntu2004 | default([]) if foreman_enable_ubuntu2004 | bool else [] ) |
  union( foreman_content_credentials_ubuntu2204 | default([]) if foreman_enable_ubuntu2204 | bool else [] )
  }}"

foreman_products_ubuntu_main: []
foreman_products_ubuntu: "{{ foreman_products_ubuntu_main | default([]) if foreman_enable_ubuntu | bool else [] |
  union( foreman_products_ubuntu1804 | default([]) if foreman_enable_ubuntu1804 | bool else [] ) |
  union( foreman_products_ubuntu2004 | default([]) if foreman_enable_ubuntu2004 | bool else [] ) |
  union( foreman_products_ubuntu2204 | default([]) if foreman_enable_ubuntu2204 | bool else [] )
  }}"

foreman_content_views_ubuntu_main: []
foreman_content_views_ubuntu: "{{ foreman_content_views_ubuntu_main | default([]) if foreman_enable_ubuntu | bool else [] |
  union( foreman_content_views_ubuntu1804 | default([]) if foreman_enable_ubuntu1804 | bool else [] ) |
  union( foreman_content_views_ubuntu2004 | default([]) if foreman_enable_ubuntu2004 | bool else [] ) |
  union( foreman_content_views_ubuntu2204 | default([]) if foreman_enable_ubuntu2204 | bool else [] )
  }}"

foreman_operatingsystems_ubuntu_main: []
foreman_operatingsystems_ubuntu: "{{ foreman_operatingsystems_ubuntu_main | default([]) if foreman_enable_ubuntu | bool else [] |
  union( foreman_operatingsystems_ubuntu1804 | default([]) if foreman_enable_ubuntu1804 | bool else [] ) |
  union( foreman_operatingsystems_ubuntu2004 | default([]) if foreman_enable_ubuntu2004 | bool else [] ) |
  union( foreman_operatingsystems_ubuntu2204 | default([]) if foreman_enable_ubuntu2204 | bool else [] )
  }}"

foreman_installation_media_ubuntu_defaults: &foreman_installation_media_ubuntu_defaults
  os_family: Debian
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"

foreman_installation_media_ubuntu_main:
  - name: Ubuntu mirror
    path: "{{ foreman_repo_baseurl_ubuntu | default(foreman_default_repo_baseurl_ubuntu) }}/"
    <<: *foreman_installation_media_ubuntu_defaults
    operatingsystems:
      - Ubuntu 18.04 LTS (Bionic Beaver)
      - Ubuntu 20.04 LTS (Focal Fossa)
      - Ubuntu 22.04 LTS (Jammy Jellyfish)

foreman_installation_media_ubuntu: "{{ foreman_installation_media_ubuntu_main | default([]) if foreman_enable_ubuntu | bool else [] |
  union( foreman_installation_media_ubuntu1804 | default([]) if foreman_enable_ubuntu1804 | bool else [] ) |
  union( foreman_installation_media_ubuntu2004 | default([]) if foreman_enable_ubuntu2004 | bool else [] ) |
  union( foreman_installation_media_ubuntu2204 | default([]) if foreman_enable_ubuntu2204 | bool else [] )
  }}"

foreman_activation_keys_ubuntu_main: []
foreman_activation_keys_ubuntu: "{{ foreman_activation_keys_ubuntu_main | default([]) if foreman_enable_ubuntu | bool else [] |
  union( foreman_activation_keys_ubuntu1804 | default([]) if foreman_enable_ubuntu1804 | bool else [] ) |
  union( foreman_activation_keys_ubuntu2004 | default([]) if foreman_enable_ubuntu2004 | bool else [] ) |
  union( foreman_activation_keys_ubuntu2204 | default([]) if foreman_enable_ubuntu2204 | bool else [] )
  }}"

foreman_sync_plan_products_ubuntu_main:
  - Ubuntu

foreman_sync_plan_products_ubuntu: "{{ foreman_sync_plan_products_ubuntu_main | default([]) if foreman_enable_ubuntu | bool else [] |
  union( foreman_sync_plan_products_ubuntu1804 | default([]) if foreman_enable_ubuntu1804 | bool else [] ) |
  union( foreman_sync_plan_products_ubuntu2004 | default([]) if foreman_enable_ubuntu2004 | bool else [] ) |
  union( foreman_sync_plan_products_ubuntu2204 | default([]) if foreman_enable_ubuntu2204 | bool else [] )
  }}"

