---
# tasks file for foreman_content_ubuntu

- name: "Vars | Include Ubuntu content vars"
  ansible.builtin.include_vars:
    dir: vars
    ignore_files:
      - "main.yml"
    extensions:
      - "yml"
    ignore_unknown_extensions: true

