---
# epel 7 content vars file for foreman_content_epel

foreman_content_credentials_epel7:
  - name: RPM-GPG-KEY-EPEL-7
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_epel | default(foreman_default_repo_baseurl_epel) ~ '/RPM-GPG-KEY-EPEL-7', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-EPEL-7') }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-EPEL-7
  # download_policy: on_demand
  download_policy: immediate
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_epel7:
  - name: Extra Packages for Enterprise Linux
    label: EPEL
    repositories:
      - name: Extra Packages for Enterprise Linux 7 - x86_64
        label: epel-7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_epel | default(foreman_default_repo_baseurl_epel) }}/7/x86_64/"
      # - name: Extra Packages for Enterprise Linux 7 - Testing - x86_64
      #   label: epel-7-testing
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_epel | default(foreman_default_repo_baseurl_epel) }}/testing/7/x86_64/"

foreman_content_views_epel7:
  - name: cv_epel7
    repositories:
      - name: Extra Packages for Enterprise Linux 7 - x86_64
        product: Extra Packages for Enterprise Linux
    allow_promote: False
  # - name: cv_epel7_testing
  #   repositories:
  #     - name: Extra Packages for Enterprise Linux 7 - Testing - x86_64
  #       product: Extra Packages for Enterprise Linux
  #   allow_promote: False

foreman_activation_keys_epel7: []

foreman_sync_plan_products_epel7:
  - Extra Packages for Enterprise Linux

