---

foreman_content_credentials_remi_el7:
  - name: RPM-GPG-KEY-remi
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_remi ~ '/RPM-GPG-KEY-remi', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-remi') }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-remi
  download_policy: on_demand
  # download_policy: immediate
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_remi_el7:
  - name: Remi Repository
    label: Remi
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi - EL7
        label: remi-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/remi/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 5.4 - EL7
        label: remi-php54-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php54/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 5.5 - EL7
        label: remi-php55-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php55/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 5.6 - EL7
        label: remi-php56-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php56/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 7.0 - EL7
        label: remi-php70-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php70/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 7.1 - EL7
        label: remi-php71-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php71/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 7.2 - EL7
        label: remi-php72-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php72/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 7.3 - EL7
        label: remi-php73-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php73/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 7.4 - EL7
        label: remi-php74-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php74/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 8.0 - EL7
        label: remi-php80-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php80/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 8.1 - EL7
        label: remi-php81-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php81/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi PHP 8.2 - EL7
        label: remi-php82-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/php82/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"
      - name: Remi Safe - EL7
        label: remi-safe-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el7 }}/enterprise/7/safe/x86_64/"
        organization: "{{ foreman_organization_remi_el7 }}"

foreman_content_views_remi_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php54_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 5.4 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php55_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 5.5 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php56_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 5.6 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php70_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 7.0 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php71_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 7.1 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php72_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 7.2 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php73_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 7.3 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php74_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 7.4 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php80_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 8.0 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php81_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 8.1 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_php82_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi PHP 8.2 - EL7
        product: Remi Repository
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}remi_safe_el7"
    organization: "{{ foreman_organization_remi_el7 }}"
    repositories:
      - name: Remi Safe - EL7
        product: Remi Repository
    allow_promote: False

foreman_activation_keys_remi_el7: []

foreman_sync_plan_products_remi_el7:
  - Remi Repository

