---

foreman_content_credentials_remi_el9:
  - name: RPM-GPG-KEY-remi2021
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_remi ~ '/RPM-GPG-KEY-remi2021', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-remi2021') }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-remi2021
  download_policy: on_demand
  # download_policy: immediate
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_remi_el9:
  - name: Remi Repository
    label: Remi
    organization: "{{ foreman_organization_remi_el9 }}"
    repositories:
      - name: Remi - EL9
        label: remi-el9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el9 }}/enterprise/9/remi/x86_64/"
        organization: "{{ foreman_organization_remi_el9 }}"
      - name: Remi Modular - EL9
        label: remi-modular-el9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el9 }}/enterprise/9/modular/x86_64/"
        organization: "{{ foreman_organization_remi_el9 }}"
      - name: Remi Safe - EL9
        label: remi-safe-el9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_remi_el9 }}/enterprise/9/safe/x86_64/"
        organization: "{{ foreman_organization_remi_el9 }}"

foreman_content_views_remi_el9:
  - name: cv_remi_el9
    organization: "{{ foreman_organization_remi_el9 }}"
    repositories:
      - name: Remi - EL9
        product: Remi Repository
    allow_promote: False
  - name: cv_remi_modular_el9
    organization: "{{ foreman_organization_remi_el9 }}"
    repositories:
      - name: Remi Modular - EL9
        product: Remi Repository
    allow_promote: False
  - name: cv_remi_safe_el9
    organization: "{{ foreman_organization_remi_el9 }}"
    repositories:
      - name: Remi Safe - EL9
        product: Remi Repository
    allow_promote: False

foreman_activation_keys_remi_el9: []

foreman_sync_plan_products_remi_el9: []

