---

foreman_content_credentials_redhat7_aap: []

foreman_products_redhat7_aap:
  - name: Red Hat Ansible Automation Platform
    repository_sets:
      # Red Hat Automation Hub 4.2 for RHEL 7 RPMs x86_64
      - name: Red Hat Automation Hub 4.2 for RHEL 7 (RPMs)
        basearch: x86_64
        label: rhel-7-server-automation-hub-4.2-rpms

foreman_content_views_redhat7_aap:
  - name: cv_rhel7_automation_hub_4_2
    repositories:
      - name: Red Hat Automation Hub 4.2 for RHEL 7 RPMs x86_64
        product: 'Red Hat Ansible Automation Platform'
    allow_promote: False

  - name: ccv_rhel7_aap
    composite: True
    auto_publish: True
    components:
      - content_view: cv_rhel7_base
        latest: true
      - content_view: cv_rhel7_extras
        latest: true
      - content_view: cv_rhel7_optional
        latest: true
      - content_view: cv_rhel7_supplementary
        latest: true
      - content_view: cv_rhel7_sat_client_6
        latest: true
      - content_view: cv_rhel7_ansible_2
        latest: true
      - content_view: cv_rhel7_ansible_2_9
        latest: true
      - content_view: cv_rhel7_automation_hub_4_2
        latest: true

foreman_operatingsystems_redhat7_aap: []

foreman_installation_media_redhat7_aap: []

# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   # Example to uyse a pool id
  #   # - pool_id: "8a88e9826db22df5016dd018abdd029b"
  #   # - name: "Red Hat Ansible Engine"
  #   # - name: "Red Hat Ansible Automation Platform"
  #   # - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Red Hat Enterprise Linux Server"
  #   # - name: "Red Hat Satellite"
  #   # - name: "Red Hat Satellite Capsule"
  #   # - name: "Red Hat Software Collections (for RHEL Server)"
  #   # - name: "Red Hat OpenShift Container Platform"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  # service_level: Standard

foreman_activation_keys_defaults_el7: &foreman_activation_keys_defaults_el7
  <<: *foreman_activation_keys_defaults
  # subscriptions:
  #   - name: "Red Hat Ansible Engine"
  #   - name: "Red Hat Enterprise Linux Server"
  #   - name: "Red Hat Software Collections (for RHEL Server)"
  #   - name: "Extra Packages for Enterprise Linux"
  release_version: 7Server

foreman_activation_keys_redhat7_aap:
  - name: ak_rhel7_aap
    content_view: ccv_rhel7_aap
    <<: *foreman_activation_keys_defaults_el7
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Ansible Automation Platform"
    #   - name: "Red Hat Enterprise Linux Server"
    content_overrides:
      - label: rhel-7-server-rpms
        override: default
      - label: rhel-7-server-extras-rpms
        override: default
      - label: rhel-7-server-optional-rpms
        override: default
      - label: rhel-7-server-supplementary-rpms
        override: default
      - label: rhel-7-server-satellite-client-6-rpms
        override: default
      - label: rhel-7-server-ansible-2-rpms
        override: default
      - label: rhel-7-server-ansible-2.9-rpms
        override: default
      - label: rhel-7-server-automation-hub-4.2-rpms
        override: default

foreman_sync_plan_products_redhat7_aap:
  - Red Hat Ansible Engine
  - Red Hat Ansible Automation Platform
  - Red Hat Enterprise Linux Server

