---

foreman_content_credentials_redhat8_sat: []

foreman_products_redhat8_sat:
  - name: Red Hat Satellite
    repository_sets:
      # Red Hat Satellite 6.11 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite 6.11 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-6.11-for-rhel-8-x86_64-rpms
      # Red Hat Satellite 6.12 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite 6.12 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-6.12-for-rhel-8-x86_64-rpms
      # Red Hat Satellite 6.13 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite 6.13 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-6.13-for-rhel-8-x86_64-rpms

  - name: Red Hat Satellite Capsule
    repository_sets:
      # Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-capsule-6.11-for-rhel-8-x86_64-rpms
      # Red Hat Satellite Capsule 6.12 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite Capsule 6.12 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-capsule-6.12-for-rhel-8-x86_64-rpms
      # Red Hat Satellite Capsule 6.12 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite Capsule 6.12 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-capsule-6.12-for-rhel-8-x86_64-rpms

foreman_content_views_redhat8_sat:
  - name: cv_rhel8_satellite_6_11
    repositories:
      - name: Red Hat Satellite 6.11 for RHEL 8 x86_64 RPMs
        product: 'Red Hat Satellite'
    allow_promote: False
  - name: cv_rhel8_satellite_6_12
    repositories:
      - name: Red Hat Satellite 6.12 for RHEL 8 x86_64 RPMs
        product: 'Red Hat Satellite'
    allow_promote: False
  - name: cv_rhel8_satellite_6_13
    repositories:
      - name: Red Hat Satellite 6.13 for RHEL 8 x86_64 RPMs
        product: 'Red Hat Satellite'
    allow_promote: False

  - name: cv_rhel8_satellite_capsule_6_11
    repositories:
      - name: Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 RPMs
        product: 'Red Hat Satellite Capsule'
    allow_promote: False
  - name: cv_rhel8_satellite_capsule_6_12
    repositories:
      - name: Red Hat Satellite Capsule 6.12 for RHEL 8 x86_64 RPMs
        product: 'Red Hat Satellite Capsule'
    allow_promote: False
  - name: cv_rhel8_satellite_capsule_6_13
    repositories:
      - name: Red Hat Satellite Capsule 6.13 for RHEL 8 x86_64 RPMs
        product: 'Red Hat Satellite Capsule'
    allow_promote: False

  - name: ccv_rhel8_satellite
    composite: True
    auto_publish: True
    components:
      - content_view: cv_rhel8_baseos
        latest: true
      - content_view: cv_rhel8_appstream
        latest: true
      - content_view: cv_rhel8_supplementary
        latest: true
      - content_view: cv_rhel8_ansible_2
        latest: true
      - content_view: cv_rhel8_ansible_2_9
        latest: true
      - content_view: cv_rhel8_satellite_6_11
        latest: true
      - content_view: cv_rhel8_satellite_6_12
        latest: true
      - content_view: cv_rhel8_satellite_6_13
        latest: true

  - name: ccv_rhel8_capsule
    composite: True
    auto_publish: True
    components:
      - content_view: cv_rhel8_baseos
        latest: true
      - content_view: cv_rhel8_appstream
        latest: true
      - content_view: cv_rhel8_supplementary
        latest: true
      - content_view: cv_rhel8_ansible_2
        latest: true
      - content_view: cv_rhel8_ansible_2_9
        latest: true
      - content_view: cv_rhel8_satellite_capsule_6_11
        latest: true
      - content_view: cv_rhel8_satellite_capsule_6_12
        latest: true
      - content_view: cv_rhel8_satellite_capsule_6_13
        latest: true

foreman_operatingsystems_redhat8_sat: []

foreman_installation_media_redhat8_sat: []

# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   # Example to use a pool id
  #   # - pool_id: "8a88e9826db22df5016dd018abdd029b"
  #   # - name: "Red Hat Ansible Engine"
  #   # - name: "Red Hat Ansible Automation Platform"
  #   # - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Red Hat Enterprise Linux Server"
  #   # - name: "Red Hat Satellite"
  #   # - name: "Red Hat Satellite Capsule"
  #   # - name: "Red Hat Software Collections (for RHEL Server)"
  #   # - name: "Red Hat OpenShift Container Platform"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  # service_level: Standard

foreman_activation_keys_defaults_el8: &foreman_activation_keys_defaults_el8
  <<: *foreman_activation_keys_defaults
  # subscriptions:
  #   - name: "Red Hat Ansible Engine"
  #   - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Extra Packages for Enterprise Linux"
  release_version: 8

foreman_activation_keys_redhat8_sat:
  - name: ak_rhel8_satellite
    content_view: ccv_rhel8_satellite
    <<: *foreman_activation_keys_defaults_el8
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux for x86_64"
    #   - name: "Red Hat Satellite"
    content_overrides:
      - label: rhel-8-for-x86_64-baseos-rpms
        override: default
      - label: rhel-8-for-x86_64-appstream-rpms
        override: default
      - label: rhel-8-for-x86_64-supplementary-rpms
        override: default
      - label: ansible-2-for-rhel-8-x86_64-rpms
        override: default
      - label: ansible-2.9-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-6.11-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-6.12-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-6.13-for-rhel-8-x86_64-rpms
        override: default

  - name: ak_rhel8_capsule
    content_view: ccv_rhel8_capsule
    <<: *foreman_activation_keys_defaults_el8
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux for x86_64"
    #   - name: "Red Hat Satellite Capsule"
    content_overrides:
      - label: rhel-8-for-x86_64-baseos-rpms
        override: default
      - label: rhel-8-for-x86_64-appstream-rpms
        override: default
      - label: rhel-8-for-x86_64-supplementary-rpms
        override: default
      - label: ansible-2-for-rhel-8-x86_64-rpms
        override: default
      - label: ansible-2.9-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-capsule-6.11-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-capsule-6.12-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-capsule-6.13-for-rhel-8-x86_64-rpms
        override: default

foreman_sync_plan_products_redhat8_sat:
  - Red Hat Ansible Engine
  - Red Hat Enterprise Linux for x86_64
  - Red Hat Satellite
  - Red Hat Satellite Capsule

