---
# defaults file for foreman_content_remi

foreman_enable_remi: false
foreman_enable_remi_el7: false
foreman_enable_remi_el8: "{{ foreman_enable_remi | bool }}"
foreman_enable_remi_el9: "{{ foreman_enable_remi | bool }}"


# foreman_repo_baseurl_remi: https://rpms.remirepo.net
# foreman_repo_baseurl_remi_el7: "{{ foreman_repo_baseurl_remi | default('https://rpms.remirepo.net') }}"
# foreman_repo_baseurl_remi_el8: "{{ foreman_repo_baseurl_remi | default('https://rpms.remirepo.net') }}"
# foreman_repo_baseurl_remi_el9: "{{ foreman_repo_baseurl_remi | default('https://rpms.remirepo.net') }}"

foreman_default_repo_baseurl_remi: https://rpms.remirepo.net
foreman_default_repo_baseurl_remi_el7: "{{ foreman_default_repo_baseurl_remi }}"
foreman_default_repo_baseurl_remi_el8: "{{ foreman_default_repo_baseurl_remi }}"
foreman_default_repo_baseurl_remi_el9: "{{ foreman_default_repo_baseurl_remi }}"


foreman_content_credentials_remi_main: []
foreman_content_credentials_remi: "{{ foreman_content_credentials_remi_main | default([]) if foreman_enable_remi | bool else [] |
  union( foreman_content_credentials_remi_el7 | default([]) if foreman_enable_remi_el7 | bool else [] ) |
  union( foreman_content_credentials_remi_el8 | default([]) if foreman_enable_remi_el8 | bool else [] ) |
  union( foreman_content_credentials_remi_el9 | default([]) if foreman_enable_remi_el9 | bool else [] )
  }}"

foreman_products_remi_main: []
foreman_products_remi: "{{ foreman_products_remi_main | default([]) if foreman_enable_remi | bool else [] |
  union( foreman_products_remi_el7 | default([]) if foreman_enable_remi_el7 | bool else [] ) |
  union( foreman_products_remi_el8 | default([]) if foreman_enable_remi_el8 | bool else [] ) |
  union( foreman_products_remi_el9 | default([]) if foreman_enable_remi_el9 | bool else [] )
  }}"

foreman_content_views_remi_main: []
foreman_content_views_remi: "{{ foreman_content_views_remi_main | default([]) if foreman_enable_remi | bool else [] |
  union( foreman_content_views_remi_el7 | default([]) if foreman_enable_remi_el7 | bool else [] ) |
  union( foreman_content_views_remi_el8 | default([]) if foreman_enable_remi_el8 | bool else [] ) |
  union( foreman_content_views_remi_el9 | default([]) if foreman_enable_remi_el9 | bool else [] )
  }}"

foreman_operatingsystems_remi_main: []
foreman_operatingsystems_remi: "{{ foreman_operatingsystems_remi_main | default([]) if foreman_enable_remi | bool else [] |
  union( foreman_operatingsystems_remi_el7 | default([]) if foreman_enable_remi_el7 | bool else [] ) |
  union( foreman_operatingsystems_remi_el8 | default([]) if foreman_enable_remi_el8 | bool else [] ) |
  union( foreman_operatingsystems_remi_el9 | default([]) if foreman_enable_remi_el9 | bool else [] )
  }}"

foreman_installation_media_remi_main: []
foreman_installation_media_remi: "{{ foreman_installation_media_remi_main | default([]) if foreman_enable_remi | bool else [] |
  union( foreman_installation_media_remi_el7 | default([]) if foreman_enable_remi_el7 | bool else [] ) |
  union( foreman_installation_media_remi_el8 | default([]) if foreman_enable_remi_el8 | bool else [] ) |
  union( foreman_installation_media_remi_el9 | default([]) if foreman_enable_remi_el9 | bool else [] )
  }}"

foreman_activation_keys_remi_main: []
foreman_activation_keys_remi: "{{ foreman_activation_keys_remi_main | default([]) if foreman_enable_remi | bool else [] |
  union( foreman_activation_keys_remi_el7 | default([]) if foreman_enable_remi_el7 | bool else [] ) |
  union( foreman_activation_keys_remi_el8 | default([]) if foreman_enable_remi_el8 | bool else [] ) |
  union( foreman_activation_keys_remi_el9 | default([]) if foreman_enable_remi_el9 | bool else [] )
  }}"

foreman_sync_plan_products_remi_main:
  - Remi Repository

foreman_sync_plan_products_remi: "{{ foreman_sync_plan_products_remi_main | default([]) if foreman_enable_remi | bool else [] |
  union( foreman_sync_plan_products_remi_el7 | default([]) if foreman_enable_remi_el7 | bool else [] ) |
  union( foreman_sync_plan_products_remi_el8 | default([]) if foreman_enable_remi_el8 | bool else [] ) |
  union( foreman_sync_plan_products_remi_el9 | default([]) if foreman_enable_remi_el9 | bool else [] )
  }}"

