---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Ceph-release
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: false
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_defaults_deb: &foreman_products_defaults_deb
  <<: *foreman_products_defaults
  content_type: deb
  mirroring_policy: "mirror_content_only"
  deb_components: main
  deb_architectures: amd64


foreman_products_ceph_quincy_el7:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_quincy_el7 }}"
    repositories:
      - name: Ceph packages for x86_64 - Quincy - EL7
        label: ceph-quincy-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_el7 }}/rpm-quincy/el7/x86_64/"
        organization: "{{ foreman_organization_ceph_quincy_el7 }}"
      - name: Ceph noarch packages - Quincy - EL7
        label: ceph-noarch-quincy-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_el7 }}/rpm-quincy/el7/noarch"
        organization: "{{ foreman_organization_ceph_quincy_el7 }}"

foreman_products_ceph_quincy_el8:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_quincy_el8 }}"
    repositories:
      - name: Ceph packages for x86_64 - Quincy - EL8
        label: ceph-quincy-el8
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_el8 }}/rpm-quincy/el8/x86_64/"
        organization: "{{ foreman_organization_ceph_quincy_el8 }}"
      - name: Ceph noarch packages - Quincy - EL8
        label: ceph-noarch-quincy-el8
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_el8 }}/rpm-quincy/el8/noarch"
        organization: "{{ foreman_organization_ceph_quincy_el8 }}"

foreman_products_ceph_quincy_el9:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_quincy_el9 }}"
    repositories:
      - name: Ceph packages for x86_64 - Quincy - EL9
        label: ceph-quincy-el9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_el9 }}/rpm-quincy/el9/x86_64/"
        organization: "{{ foreman_organization_ceph_quincy_el9 }}"
      - name: Ceph noarch packages - Quincy - EL9
        label: ceph-noarch-quincy-el9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_el9 }}/rpm-quincy/el9/noarch"
        organization: "{{ foreman_organization_ceph_quincy_el9 }}"

foreman_products_ceph_quincy_deb11:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_quincy_deb11 }}"
    repositories:
      - name: Ceph packages for amd64 - Quincy - Debian 11 (Bullseye)
        label: ceph-quincy-debian-bullseye
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_deb11 }}/debian-quincy/"
        deb_releases: bullseye
        organization: "{{ foreman_organization_ceph_quincy_deb11 }}"

foreman_products_ceph_quincy_ub2004:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_quincy_ub2004 }}"
    repositories:
      - name: Ceph packages for amd64 - Quincy - Ubuntu 20.04 LTS (Focal Fossa)
        label: ceph-quincy-ubuntu-focal
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_quincy_ub2004 }}/debian-quincy/"
        deb_releases: focal
        organization: "{{ foreman_organization_ceph_quincy_ub2004 }}"


foreman_content_views_ceph_quincy_el7:
  - name: cv_ceph_quincy_el7
    organization: "{{ foreman_organization_ceph_quincy_el7 }}"
    repositories:
      - name: Ceph packages for x86_64 - Quincy - EL7
        product: Ceph
      - name: Ceph noarch packages - Quincy - EL7
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_quincy_el8:
  - name: cv_ceph_quincy_el8
    organization: "{{ foreman_organization_ceph_quincy_el8 }}"
    repositories:
      - name: Ceph packages for x86_64 - Quincy - EL8
        product: Ceph
      - name: Ceph noarch packages - Quincy - EL8
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_quincy_el9:
  - name: cv_ceph_quincy_el9
    organization: "{{ foreman_organization_ceph_quincy_el9 }}"
    repositories:
      - name: Ceph packages for x86_64 - Quincy - EL9
        product: Ceph
      - name: Ceph noarch packages - Quincy - EL9
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_quincy_deb11:
  - name: cv_ceph_quincy_deb11
    organization: "{{ foreman_organization_ceph_quincy_deb11 }}"
    repositories:
      - name: Ceph packages for amd64 - Quincy - Debian 11 (Bullseye)
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_quincy_ub2004:
  - name: cv_ceph_quincy_ub2004
    organization: "{{ foreman_organization_ceph_quincy_ub2004 }}"
    repositories:
      - name: Ceph packages for amd64 - Quincy - Ubuntu 20.04 LTS (Focal Fossa)
        product: Ceph
    allow_promote: False


foreman_content_credentials_quincy_ceph_main: []
foreman_content_credentials_quincy_ceph: "{{ ( foreman_content_credentials_quincy_ceph_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_content_credentials_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_products_ceph_quincy_main: []
foreman_products_ceph_quincy: "{{ ( foreman_products_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_products_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_products_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_products_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_products_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_products_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_content_views_ceph_quincy_main: []
foreman_content_views_ceph_quincy: "{{ ( foreman_content_views_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_content_views_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_content_views_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_content_views_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_content_views_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_content_views_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_operatingsystems_ceph_quincy_main: []
foreman_operatingsystems_ceph_quincy: "{{ ( foreman_operatingsystems_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_operatingsystems_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_installation_media_ceph_quincy_main: []
foreman_installation_media_ceph_quincy: "{{ ( foreman_installation_media_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_activation_keys_ceph_quincy_main: []
foreman_activation_keys_ceph_quincy: "{{ ( foreman_activation_keys_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

foreman_sync_plan_products_ceph_quincy_main: []
foreman_sync_plan_products_ceph_quincy: "{{ ( foreman_sync_plan_products_ceph_quincy_main | default([]) if foreman_enable_ceph_quincy | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el7 | default([]) if foreman_enable_ceph_quincy_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el8 | default([]) if foreman_enable_ceph_quincy_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_el9 | default([]) if foreman_enable_ceph_quincy_el9 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_deb11 | default([]) if foreman_enable_ceph_quincy_deb11 | bool else [] ) |
  union( foreman_installation_media_ceph_quincy_ub2004 | default([]) if foreman_enable_ceph_quincy_ub2004 | bool else [] )
  }}"

