---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Ceph-release
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: false
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_ceph_docker:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_docker }}"
    repositories:
      - name: Ceph Docker images
        label: ceph-docker
        url: "{{ foreman_repo_baseurl_ceph_docker }}"
        docker_upstream_name: ceph/ceph
        # docker_tags_whitelist:
        #   - ceph/ceph
        # include_tags: []
        exclude_tags:
          - "*-source"
        <<: *foreman_products_defaults
        content_type: docker
        mirroring_policy: "mirror_content_only"
        organization: "{{ foreman_organization_ceph_docker }}"

