---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Ceph-release
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: false
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_defaults_deb: &foreman_products_defaults_deb
  <<: *foreman_products_defaults
  content_type: deb
  mirroring_policy: "mirror_content_only"
  deb_components: main
  deb_architectures: amd64


foreman_products_ceph_nautilus_el7:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_nautilus_el7 }}"
    repositories:
      - name: Ceph packages for x86_64 - Nautilus - EL7
        label: ceph-nautilus-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_nautilus_el7 }}/rpm-nautilus/el7/x86_64/"
        organization: "{{ foreman_organization_ceph_nautilus_el7 }}"
      - name: Ceph noarch packages - Nautilus - EL7
        label: ceph-noarch-nautilus-el7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_nautilus_el7 }}/rpm-nautilus/el7/noarch"
        organization: "{{ foreman_organization_ceph_nautilus_el7 }}"

foreman_products_ceph_nautilus_el8:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_nautilus_el8 }}"
    repositories:
      - name: Ceph packages for x86_64 - Nautilus - EL8
        label: ceph-nautilus-el8
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_nautilus_el8 }}/rpm-nautilus/el8/x86_64/"
        organization: "{{ foreman_organization_ceph_nautilus_el8 }}"
      - name: Ceph noarch packages - Nautilus - EL8
        label: ceph-noarch-nautilus-el8
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ceph_nautilus_el8 }}/rpm-nautilus/el8/noarch"
        organization: "{{ foreman_organization_ceph_nautilus_el8 }}"

foreman_products_ceph_nautilus_deb9:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_nautilus_deb9 }}"
    repositories:
      - name: Ceph packages for amd64 - Nautilus - Debian 9 (Stretch)
        label: ceph-nautilus-debian-stretch
        <<: *foreman_products_defaults_deb
        url: "{{ foreman_repo_baseurl_ceph_nautilus_deb9 }}/debian-nautilus/"
        deb_releases: stretch
        organization: "{{ foreman_organization_ceph_nautilus_deb9 }}"

foreman_products_ceph_nautilus_deb10:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_nautilus_deb10 }}"
    repositories:
      - name: Ceph packages for amd64 - Nautilus - Debian 10 (Buster)
        label: ceph-nautilus-debian-buster
        <<: *foreman_products_defaults_deb
        url: "{{ foreman_repo_baseurl_ceph_nautilus_deb10 }}/debian-nautilus/"
        deb_releases: buster
        organization: "{{ foreman_organization_ceph_nautilus_deb10 }}"

foreman_products_ceph_nautilus_ub1804:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_nautilus_ub1804 }}"
    repositories:
      - name: Ceph packages for amd64 - Nautilus - Ubuntu 18.04 LTS (Bionic Beaver)
        label: ceph-nautilus-ubuntu-bionic
        <<: *foreman_products_defaults_deb
        url: "{{ foreman_repo_baseurl_ceph_nautilus_ub1804 }}/debian-nautilus/"
        deb_releases: bionic
        organization: "{{ foreman_organization_ceph_nautilus_ub1804 }}"

foreman_products_ceph_nautilus_ub2004:
  - name: Ceph
    label: Ceph
    organization: "{{ foreman_organization_ceph_nautilus_ub2004 }}"
    repositories:
      - name: Ceph packages for amd64 - Nautilus - Ubuntu 20.04 LTS (Focal Fossa)
        label: ceph-nautilus-ubuntu-focal
        <<: *foreman_products_defaults_deb
        url: "{{ foreman_repo_baseurl_ceph_nautilus_ub2004 }}/debian-nautilus/"
        deb_releases: focal
        organization: "{{ foreman_organization_ceph_nautilus_ub2004 }}"


foreman_content_views_ceph_nautilus_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ceph_nautilus_el7"
    organization: "{{ foreman_organization_ceph_nautilus_el7 }}"
    repositories:
      - name: Ceph packages for x86_64 - Nautilus - EL7
        product: Ceph
      - name: Ceph noarch packages - Nautilus - EL7
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_nautilus_el8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ceph_nautilus_el8"
    organization: "{{ foreman_organization_ceph_nautilus_el8 }}"
    repositories:
      - name: Ceph packages for x86_64 - Nautilus - EL8
        product: Ceph
      - name: Ceph noarch packages - Nautilus - EL8
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_nautilus_deb9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ceph_nautilus_deb9"
    organization: "{{ foreman_organization_ceph_nautilus_deb9 }}"
    repositories:
      - name: Ceph packages for amd64 - Nautilus - Debian 9 (Stretch)
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_nautilus_deb10:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ceph_nautilus_deb10"
    organization: "{{ foreman_organization_ceph_nautilus_deb10 }}"
    repositories:
      - name: Ceph packages for amd64 - Nautilus - Debian 10 (Buster)
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_nautilus_ub1804:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ceph_nautilus_ub1804"
    organization: "{{ foreman_organization_ceph_nautilus_ub1804 }}"
    repositories:
      - name: Ceph packages for amd64 - Nautilus - Ubuntu 18.04 LTS (Bionic Beaver)
        product: Ceph
    allow_promote: False

foreman_content_views_ceph_nautilus_ub2004:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ceph_nautilus_ub2004"
    organization: "{{ foreman_organization_ceph_nautilus_ub2004 }}"
    repositories:
      - name: Ceph packages for amd64 - Nautilus - Ubuntu 20.04 LTS (Focal Fossa)
        product: Ceph
    allow_promote: False


foreman_content_credentials_nautilus_ceph_main: []
foreman_content_credentials_nautilus_ceph: "{{ ( foreman_content_credentials_nautilus_ceph_main | default([]) if foreman_enable_ceph_nautilus | bool else [] ) |
  union( foreman_content_credentials_ceph_nautilus_el7 | default([]) if foreman_enable_ceph_nautilus_el7 | bool else [] ) |
  union( foreman_content_credentials_ceph_nautilus_el8 | default([]) if foreman_enable_ceph_nautilus_el8 | bool else [] ) |
  union( foreman_content_credentials_ceph_nautilus_deb9 | default([]) if foreman_enable_ceph_nautilus_deb9 | bool else [] ) |
  union( foreman_content_credentials_ceph_nautilus_deb10 | default([]) if foreman_enable_ceph_nautilus_deb10 | bool else [] ) |
  union( foreman_content_credentials_ceph_nautilus_ub1804 | default([]) if foreman_enable_ceph_nautilus_ub1804 | bool else [] ) |
  union( foreman_content_credentials_ceph_nautilus_ub2004 | default([]) if foreman_enable_ceph_nautilus_ub2004 | bool else [] )
  }}"

foreman_products_ceph_nautilus_main: []
foreman_products_ceph_nautilus: "{{ ( foreman_products_ceph_nautilus_main | default([]) if foreman_enable_ceph_nautilus | bool else [] ) |
  union( foreman_products_ceph_nautilus_el7 | default([]) if foreman_enable_ceph_nautilus_el7 | bool else [] ) |
  union( foreman_products_ceph_nautilus_el8 | default([]) if foreman_enable_ceph_nautilus_el8 | bool else [] ) |
  union( foreman_products_ceph_nautilus_deb9 | default([]) if foreman_enable_ceph_nautilus_deb9 | bool else [] ) |
  union( foreman_products_ceph_nautilus_deb10 | default([]) if foreman_enable_ceph_nautilus_deb10 | bool else [] ) |
  union( foreman_products_ceph_nautilus_ub1804 | default([]) if foreman_enable_ceph_nautilus_ub1804 | bool else [] ) |
  union( foreman_products_ceph_nautilus_ub2004 | default([]) if foreman_enable_ceph_nautilus_ub2004 | bool else [] )
  }}"

foreman_content_views_ceph_nautilus_main: []
foreman_content_views_ceph_nautilus: "{{ ( foreman_content_views_ceph_nautilus_main | default([]) if foreman_enable_ceph_nautilus | bool else [] ) |
  union( foreman_content_views_ceph_nautilus_el7 | default([]) if foreman_enable_ceph_nautilus_el7 | bool else [] ) |
  union( foreman_content_views_ceph_nautilus_el8 | default([]) if foreman_enable_ceph_nautilus_el8 | bool else [] ) |
  union( foreman_content_views_ceph_nautilus_deb9 | default([]) if foreman_enable_ceph_nautilus_deb9 | bool else [] ) |
  union( foreman_content_views_ceph_nautilus_deb10 | default([]) if foreman_enable_ceph_nautilus_deb10 | bool else [] ) |
  union( foreman_content_views_ceph_nautilus_ub1804 | default([]) if foreman_enable_ceph_nautilus_ub1804 | bool else [] ) |
  union( foreman_content_views_ceph_nautilus_ub2004 | default([]) if foreman_enable_ceph_nautilus_ub2004 | bool else [] )
  }}"

foreman_operatingsystems_ceph_nautilus_main: []
foreman_operatingsystems_ceph_nautilus: "{{ ( foreman_operatingsystems_ceph_nautilus_main | default([]) if foreman_enable_ceph_nautilus | bool else [] ) |
  union( foreman_operatingsystems_ceph_nautilus_el7 | default([]) if foreman_enable_ceph_nautilus_el7 | bool else [] ) |
  union( foreman_operatingsystems_ceph_nautilus_el8 | default([]) if foreman_enable_ceph_nautilus_el8 | bool else [] ) |
  union( foreman_operatingsystems_ceph_nautilus_deb9 | default([]) if foreman_enable_ceph_nautilus_deb9 | bool else [] ) |
  union( foreman_operatingsystems_ceph_nautilus_deb10 | default([]) if foreman_enable_ceph_nautilus_deb10 | bool else [] ) |
  union( foreman_operatingsystems_ceph_nautilus_ub1804 | default([]) if foreman_enable_ceph_nautilus_ub1804 | bool else [] ) |
  union( foreman_operatingsystems_ceph_nautilus_ub2004 | default([]) if foreman_enable_ceph_nautilus_ub2004 | bool else [] )
  }}"

foreman_installation_media_ceph_nautilus_main: []
foreman_installation_media_ceph_nautilus: "{{ ( foreman_installation_media_ceph_nautilus_main | default([]) if foreman_enable_ceph_nautilus | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_el7 | default([]) if foreman_enable_ceph_nautilus_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_el8 | default([]) if foreman_enable_ceph_nautilus_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_deb9 | default([]) if foreman_enable_ceph_nautilus_deb9 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_deb10 | default([]) if foreman_enable_ceph_nautilus_deb10 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_ub1804 | default([]) if foreman_enable_ceph_nautilus_ub1804 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_ub2004 | default([]) if foreman_enable_ceph_nautilus_ub2004 | bool else [] )
  }}"

foreman_activation_keys_ceph_nautilus_main: []
foreman_activation_keys_ceph_nautilus: "{{ ( foreman_activation_keys_ceph_nautilus_main | default([]) if foreman_enable_ceph_nautilus | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_el7 | default([]) if foreman_enable_ceph_nautilus_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_el8 | default([]) if foreman_enable_ceph_nautilus_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_deb9 | default([]) if foreman_enable_ceph_nautilus_deb9 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_deb10 | default([]) if foreman_enable_ceph_nautilus_deb10 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_ub1804 | default([]) if foreman_enable_ceph_nautilus_ub1804 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_ub2004 | default([]) if foreman_enable_ceph_nautilus_ub2004 | bool else [] )
  }}"

foreman_sync_plan_products_ceph_nautilus_main: []
foreman_sync_plan_products_ceph_nautilus: "{{ ( foreman_sync_plan_products_ceph_nautilus_main | default([]) if foreman_enable_ceph_nautilus | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_el7 | default([]) if foreman_enable_ceph_nautilus_el7 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_el8 | default([]) if foreman_enable_ceph_nautilus_el8 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_deb9 | default([]) if foreman_enable_ceph_nautilus_deb9 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_deb10 | default([]) if foreman_enable_ceph_nautilus_deb10 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_ub1804 | default([]) if foreman_enable_ceph_nautilus_ub1804 | bool else [] ) |
  union( foreman_installation_media_ceph_nautilus_ub2004 | default([]) if foreman_enable_ceph_nautilus_ub2004 | bool else [] )
  }}"

