---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  # gpg_key: RPM-GPG-KEY-copr-dmann-subscription-manager
  download_policy: "{{ foreman_products_defaults_download_policy_fedora_copr }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_fedora_copr }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_fedora_copr | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_fedora_copr }}"
  unprotected: "{{ foreman_products_defaults_unprotected_fedora_copr | bool }}"


### dgoodwin/subscription-manager OL 6/7

foreman_content_credentials_fedora_copr_dgoodwin_subscription_manager_main:
  - name: RPM-GPG-KEY-copr-dgoodwin-subscription-manager
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_fedora_copr ~ '/dgoodwin/subscription-manager/pubkey.gpg', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-copr-dgoodwin-subscription-manager') }}"

foreman_content_credentials_fedora_copr_dgoodwin_subscription_manager: "{{ ( foreman_content_credentials_fedora_copr_dgoodwin_subscription_manager_main | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager | bool else [] ) |
  union( foreman_content_credentials_fedora_copr_dgoodwin_subscription_manager_ol6 | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager_ol6 | bool else [] ) |
  union( foreman_content_credentials_fedora_copr_dgoodwin_subscription_manager_ol7 | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager_ol7 | bool else [] )
  }}"


foreman_products_fedora_copr_dgoodwin_subscription_manager_ol6:
  - name: Fedora COPR
    label: Fedora_COPR
    organization: "{{ foreman_organization_fedora_copr_dgoodwin_subscription_manager_ol6 }}"
    repositories:
      - name: Fedora COPR - dgoodwin:subscription-manager - OL6
        label: copr-dgoodwin-subscription-manager-ol6
        url: "{{ foreman_repo_baseurl_fedora_copr }}/dgoodwin/subscription-manager/fedora_copr-6-x86_64/"
        <<: *foreman_products_defaults
        gpg_key: RPM-GPG-KEY-copr-dgoodwin-subscription-manager
        organization: "{{ foreman_organization_fedora_copr_dgoodwin_subscription_manager_ol6 }}"

foreman_products_fedora_copr_dgoodwin_subscription_manager_ol7:
  - name: Fedora COPR
    label: Fedora_COPR
    organization: "{{ foreman_organization_fedora_copr_dgoodwin_subscription_manager_ol7 }}"
    repositories:
      - name: Fedora COPR - dgoodwin:subscription-manager - OL7
        label: copr-dgoodwin-subscription-manager-ol7
        url: "{{ foreman_repo_baseurl_fedora_copr }}/dgoodwin/subscription-manager/fedora_copr-7-x86_64/"
        <<: *foreman_products_defaults
        gpg_key: RPM-GPG-KEY-copr-dgoodwin-subscription-manager
        organization: "{{ foreman_organization_fedora_copr_dgoodwin_subscription_manager_ol7 }}"

foreman_products_fedora_copr_dgoodwin_subscription_manager_main: []
foreman_products_fedora_copr_dgoodwin_subscription_manager: "{{ ( foreman_products_fedora_copr_dgoodwin_subscription_manager_main | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager | bool else [] ) |
  union( foreman_products_fedora_copr_dgoodwin_subscription_manager_ol6 | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager_ol6 | bool else [] ) |
  union( foreman_products_fedora_copr_dgoodwin_subscription_manager_ol7 | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager_ol7 | bool else [] )
  }}"


foreman_content_views_fedora_copr_dgoodwin_subscription_manager_ol6:
  - name: "{{ foreman_cv_prefix | default('cv_') }}copr_dgoodwin_subscription_manager_ol6"
    organization: "{{ foreman_organization_fedora_copr_dgoodwin_subscription_manager_ol6 }}"
    repositories:
      - name: Fedora COPR - dgoodwin:subscription-manager - OL6
        product: Fedora COPR
    allow_promote: "{{ foreman_cv_allow_promote_fedora_copr_dgoodwin_subscription_manager_ol6 }}"

foreman_content_views_fedora_copr_dgoodwin_subscription_manager_ol7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}copr_dgoodwin_subscription_manager_ol7"
    organization: "{{ foreman_organization_fedora_copr_dgoodwin_subscription_manager_ol7 }}"
    repositories:
      - name: Fedora COPR - dgoodwin:subscription-manager - OL7
        product: Fedora COPR
    allow_promote: "{{ foreman_cv_allow_promote_fedora_copr_dgoodwin_subscription_manager_ol7 }}"

foreman_content_views_fedora_copr_dgoodwin_subscription_manager_main: []
foreman_content_views_fedora_copr_dgoodwin_subscription_manager: "{{ ( foreman_content_views_fedora_copr_dgoodwin_subscription_manager_main | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager | bool else [] ) |
  union( foreman_content_views_fedora_copr_dgoodwin_subscription_manager_ol6 | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager_ol6 | bool else [] ) |
  union( foreman_content_views_fedora_copr_dgoodwin_subscription_manager_ol7 | default([]) if foreman_enable_fedora_copr_dgoodwin_subscription_manager_ol7 | bool else [] )
  }}"


### dmann/subscription-manager OL 8

foreman_content_credentials_fedora_copr_dmann_subscription_manager_main:
  - name: RPM-GPG-KEY-copr-dmann-subscription-manager
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_fedora_copr ~ '/dmann/subscription-manager/pubkey.gpg', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-copr-dmann-subscription-manager') }}"

foreman_content_credentials_fedora_copr_dmann_subscription_manager: "{{ ( foreman_content_credentials_fedora_copr_dmann_subscription_manager_main | default([]) if foreman_enable_fedora_copr_dmann_subscription_manager | bool else [] ) |
  union( foreman_content_credentials_fedora_copr_dmann_subscription_manager_ol8 | default([]) if foreman_enable_fedora_copr_dmann_subscription_manager_ol8 | bool else [] )
  }}"


foreman_products_fedora_copr_dmann_subscription_manager_ol8:
  - name: Fedora COPR
    label: Fedora_COPR
    organization: "{{ foreman_organization_fedora_copr_dmann_subscription_manager_ol8 }}"
    repositories:
      - name: Fedora COPR - dmann:subscription-manager - OL8
        label: copr-dmann-subscription-manager-ol8
        url: "{{ foreman_repo_baseurl_fedora_copr }}/dmann/subscription-manager/fedora_copr-8-x86_64/"
        <<: *foreman_products_defaults
        gpg_key: RPM-GPG-KEY-copr-dmann-subscription-manager
        organization: "{{ foreman_organization_fedora_copr_dmann_subscription_manager_ol8 }}"

foreman_products_fedora_copr_dmann_subscription_manager_main: []
foreman_products_fedora_copr_dmann_subscription_manager: "{{ ( foreman_products_fedora_copr_dmann_subscription_manager_main | default([]) if foreman_enable_fedora_copr_dmann_subscription_manager | bool else [] ) |
  union( foreman_products_fedora_copr_dmann_subscription_manager_ol8 | default([]) if foreman_enable_fedora_copr_dmann_subscription_manager_ol8 | bool else [] )
  }}"


foreman_content_views_fedora_copr_dmann_subscription_manager_ol8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}copr_dmann_subscription_manager_ol8"
    organization: "{{ foreman_organization_fedora_copr_dmann_subscription_manager_ol8 }}"
    repositories:
      - name: Fedora COPR - dmann:subscription-manager - OL8
        product: Fedora COPR
    allow_promote: "{{ foreman_cv_allow_promote_fedora_copr_dmann_subscription_manager_ol8 }}"

foreman_content_views_fedora_copr_dmann_subscription_manager_main: []
foreman_content_views_fedora_copr_dmann_subscription_manager: "{{ ( foreman_content_views_fedora_copr_dmann_subscription_manager_main | default([]) if foreman_enable_fedora_copr_dmann_subscription_manager | bool else [] ) |
  union( foreman_content_views_fedora_copr_dmann_subscription_manager_ol8 | default([]) if foreman_enable_fedora_copr_dmann_subscription_manager_ol8 | bool else [] )
  }}"

