---
# foreman hashicorp content group vars file for katello-main

foreman_default_repo_baseurl_hashicorp: https://rpm.releases.hashicorp.com

foreman_content_credentials_hashicorp:
  - name: RPM-GPG-KEY-Hashicorp
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_hashicorp | default(foreman_default_repo_baseurl_hashicorp) ~ '/gpg', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', ansible_parent_role_paths[0] | default(role_path) ~ '/files/RPM-GPG-KEY-hashicorp') }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-Hashicorp
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_hashicorp:
  - name: Hashicorp
    label: Hashicorp
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 7
        label: hashicorp-el7
        url: "{{ foreman_repo_baseurl_hashicorp | default(foreman_default_repo_baseurl_hashicorp) }}/RHEL/7/x86_64/stable"
        <<: *foreman_products_defaults
      - name: Hashicorp Stable - x86_64 - RHEL 8
        label: hashicorp-el8
        url: "{{ foreman_repo_baseurl_hashicorp | default(foreman_default_repo_baseurl_hashicorp) }}/RHEL/8/x86_64/stable"
        <<: *foreman_products_defaults
      - name: Hashicorp Stable - x86_64 - RHEL 9
        label: hashicorp-el9
        url: "{{ foreman_repo_baseurl_hashicorp | default(foreman_default_repo_baseurl_hashicorp) }}/RHEL/9/x86_64/stable"
        <<: *foreman_products_defaults

foreman_content_views_hashicorp:
  - name: cv_hashicorp_el7
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 7
        product: Hashicorp
    allow_promote: False
  - name: cv_hashicorp_el8
    repositories:
      - name: Hashicorp Stable - x86_64 - RHEL 8
        product: Hashicorp
    allow_promote: False

foreman_activation_keys_hashicorp: []

foreman_sync_plan_products_hashicorp:
  - Hashicorp

