---

foreman_content_credentials_ubuntu1804: []


foreman_products_defaults: &foreman_products_defaults
  content_type: deb
  download_policy: "{{ foreman_products_defaults_download_policy_ubuntu }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ubuntu }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ubuntu | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ubuntu }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ubuntu | bool }}"
  deb_components: "{{ foreman_products_defaults_deb_components_ubuntu }}"
  deb_architectures: "{{ foreman_products_defaults_deb_architectures_ubuntu }}"


foreman_products_defaults_ubuntu1804: &foreman_products_defaults_ubuntu1804
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_ubuntu1804 }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_ubuntu1804 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_ubuntu1804 | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_ubuntu1804 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_ubuntu1804 | bool }}"
  deb_components: "{{ foreman_products_defaults_deb_components_ubuntu1804 }}"
  deb_architectures: "{{ foreman_products_defaults_deb_architectures_ubuntu1804 }}"


foreman_products_ubuntu1804:
  - name: Ubuntu
    label: Ubuntu
    organization: "{{ foreman_organization_ubuntu1804 }}"
    repositories:
      - name: Ubuntu 18.04 LTS (Bionic Beaver)
        label: ubuntu-1804
        <<: *foreman_products_defaults_ubuntu1804
        url: "{{ foreman_repo_baseurl_ubuntu1804 }}/"
        deb_releases: bionic
        organization: "{{ foreman_organization_ubuntu1804 }}"
      - name: Ubuntu 18.04 LTS (Bionic Beaver) - Updates
        label: ubuntu-1804-updates
        <<: *foreman_products_defaults_ubuntu1804
        url: "{{ foreman_repo_baseurl_ubuntu1804 }}/"
        deb_releases: bionic-updates
        organization: "{{ foreman_organization_ubuntu1804 }}"
      # - name: Ubuntu 18.04 LTS (Bionic Beaver) - Proposed Updates
      #   label: ubuntu-1804-proposed
      #   <<: *foreman_products_defaults_ubuntu1804
      #   url: "{{ foreman_repo_baseurl_ubuntu1804 }}/"
      #   deb_releases: bionic-proposed
      #   organization: "{{ foreman_organization_ubuntu1804 }}"
      - name: Ubuntu 18.04 LTS (Bionic Beaver) - Backports
        label: ubuntu-1804-backports
        <<: *foreman_products_defaults_ubuntu1804
        url: "{{ foreman_repo_baseurl_ubuntu1804 }}/"
        deb_releases: bionic-backports
        organization: "{{ foreman_organization_ubuntu1804 }}"
      - name: Ubuntu 18.04 LTS (Bionic Beaver) - Security updates
        label: ubuntu-1804-security
        <<: *foreman_products_defaults_ubuntu1804
        url: "{{ foreman_repo_baseurl_ubuntu1804 }}/"
        deb_releases: bionic-security
        organization: "{{ foreman_organization_ubuntu1804 }}"


foreman_content_views_ubuntu1804:
  - name: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804"
    organization: "{{ foreman_organization_ubuntu1804 }}"
    repositories:
      - name: Ubuntu 18.04 LTS (Bionic Beaver)
        product: Ubuntu
    allow_promote: "{{ foreman_cv_allow_promote_ubuntu1804 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804_updates"
    organization: "{{ foreman_organization_ubuntu1804 }}"
    repositories:
      - name: Ubuntu 18.04 LTS (Bionic Beaver) - Updates
        product: Ubuntu
    allow_promote: "{{ foreman_cv_allow_promote_ubuntu1804 }}"
  # - name: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804_proposed"
  #   organization: "{{ foreman_organization_ubuntu1804 }}"
  #   repositories:
  #     - name: Ubuntu 18.04 LTS (Bionic Beaver) - Proposed Updates
  #       product: Ubuntu
  #   allow_promote: "{{ foreman_cv_allow_promote_ubuntu1804 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804_backports"
    organization: "{{ foreman_organization_ubuntu1804 }}"
    repositories:
      - name: Ubuntu 18.04 LTS (Bionic Beaver) - Backports
        product: Ubuntu
    allow_promote: "{{ foreman_cv_allow_promote_ubuntu1804 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804_security"
    organization: "{{ foreman_organization_ubuntu1804 }}"
    repositories:
      - name: Ubuntu 18.04 LTS (Bionic Beaver) - Security updates
        product: Ubuntu
    allow_promote: "{{ foreman_cv_allow_promote_ubuntu1804 }}"

foreman_composite_content_views_ubuntu1804:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}ubuntu1804"
    organization: "{{ foreman_organization_ubuntu1804 }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_ubuntu1804 }}"
    auto_publish: "{{ foreman_ccv_auto_publish_ubuntu1804 }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804_updates"
        latest: true
      # - content_view: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804_proposed"
      #   latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804_backports"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}ubuntu1804_security"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Debian"
  password_hash: "SHA512"
  architectures: "{{ foreman_operatingsystems_ubuntu1804_architectures }}"
  # ptables:
  #   - Preseed default
  #   - Preseed default LVM
  ptables: "{{ foreman_operatingsystems_ubuntu1804_ptables }}"


foreman_operatingsystems_ubuntu1804:
  - name: "Ubuntu"
    major: "18"
    minor: "04"
    release_name: bionic
    description: "Ubuntu 18.04 LTS (Bionic Beaver)"
    default_templates: "{{ foreman_operatingsystems_ubuntu1804_default_templates | default( foreman_operatingsystems_ubuntu_default_templates | default( foreman_operatingsystems_deb_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Debian
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_installation_media_ubuntu1804_organizations }}"
  locations: "{{ foreman_installation_media_ubuntu1804_locations }}"
  operatingsystems: "{{ foreman_installation_media_ubuntu1804_operatingsystems }}"


foreman_installation_media_ubuntu1804:
  - name: Ubuntu 18.04 LTS (Bionic Beaver)
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Ubuntu/ubuntu-1804/"
    <<: *foreman_installation_media_defaults


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Ubuntu"
  auto_attach: False


foreman_activation_keys_ubuntu1804:
  - name: ak_ubuntu1804
    organization: "{{ foreman_organization_ubuntu1804 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}ubuntu1804"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-1804"
        override: default
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-1804-updates"
        override: default
      # - label: "{{ foreman_organization }}_Ubuntu_ubuntu-1804-proposed"
      #   override: default
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-1804-backports"
        override: disabled
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-1804-security"
        override: disabled


foreman_sync_plan_products_ubuntu1804:
  - Ubuntu

