---
# foreman ubuntu content vars file for foreman_content_ubuntu

foreman_content_credentials_ubuntu2204: []

foreman_products_defaults: &foreman_products_defaults
  content_type: deb
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy
  deb_components: main multiverse restricted universe
  deb_architectures: amd64

foreman_products_ubuntu2204:
  - name: Ubuntu
    label: Ubuntu
    repositories:
      - name: Ubuntu 22.04 LTS (Jammy Jellyfish)
        label: ubuntu-2204
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ubuntu2204 | default(foreman_default_repo_baseurl_ubuntu2204) }}/"
        deb_releases: jammy
      - name: Ubuntu 22.04 LTS (Jammy Jellyfish) - Updates
        label: ubuntu-2204-updates
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ubuntu2204 | default(foreman_default_repo_baseurl_ubuntu2204) }}/"
        deb_releases: jammy-updates
      # - name: Ubuntu 22.04 LTS (Jammy Jellyfish) - Proposed Updates
      #   label: ubuntu-2204-proposed
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_ubuntu2204 | default(foreman_default_repo_baseurl_ubuntu2204) }}/"
      #   deb_releases: jammy-proposed
      - name: Ubuntu 22.04 LTS (Jammy Jellyfish) - Backports
        label: ubuntu-2204-backports
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ubuntu2204 | default(foreman_default_repo_baseurl_ubuntu2204) }}/"
        deb_releases: jammy-backports
      - name: Ubuntu 22.04 LTS (Jammy Jellyfish) - Security updates
        label: ubuntu-2204-security
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ubuntu2204 | default(foreman_default_repo_baseurl_ubuntu2204) }}/"
        deb_releases: jammy-security

foreman_content_views_ubuntu2204:
  - name: cv_ubuntu2204
    repositories:
      - name: Ubuntu 22.04 LTS (Jammy Jellyfish)
        product: Ubuntu
    allow_promote: False
  - name: cv_ubuntu2204_updates
    repositories:
      - name: Ubuntu 22.04 LTS (Jammy Jellyfish) - Updates
        product: Ubuntu
    allow_promote: False
  # - name: cv_ubuntu2204_proposed
  #   repositories:
  #     - name: Ubuntu 22.04 LTS (Jammy Jellyfish) - Proposed Updates
  #       product: Ubuntu
  #   allow_promote: False
  - name: cv_ubuntu2204_backports
    repositories:
      - name: Ubuntu 22.04 LTS (Jammy Jellyfish) - Backports
        product: Ubuntu
    allow_promote: False
  - name: cv_ubuntu2204_security
    repositories:
      - name: Ubuntu 22.04 LTS (Jammy Jellyfish) - Security updates
        product: Ubuntu
    allow_promote: False

  - name: ccv_ubuntu2204
    composite: True
    auto_publish: True
    components:
      - content_view: cv_ubuntu2204
        latest: true
      - content_view: cv_ubuntu2204_updates
        latest: true
      # - content_view: cv_ubuntu2204_proposed
      #   latest: true
      - content_view: cv_ubuntu2204_backports
        latest: true
      - content_view: cv_ubuntu2204_security
        latest: true

foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Debian"
  password_hash: "SHA512"
  architectures:
    - amd64
  # ptables:
  #   - Preseed default autoinstall
  ptables: "{{
    [ 'Preseed default autoinstall' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Debian') | map(attribute='name') | list )
    }}"
  default_templates:
    # - template_kind: "cloud-init"
    #   provisioning_template: "{{ foreman_operatingsystems_ub2204_template_cloud_init | default( foreman_operatingsystems_ub2x_template_cloud_init | default( foreman_operatingsystems_deb_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_ub2204_template_finish | default( foreman_operatingsystems_ub2x_template_finish | default( foreman_operatingsystems_deb_template_finish | default('Kickstart default finish') ) ) }}"
    # - template_kind: "host_init_config"
    #   provisioning_template: "{{ foreman_operatingsystems_ub2204_template_host_init_config | default( foreman_operatingsystems_ub2x_template_host_init_config | default( foreman_operatingsystems_deb_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    # - template_kind: "iPXE"
    #   provisioning_template: "{{ foreman_operatingsystems_ub2204_template_ipxe | default( foreman_operatingsystems_ub2x_template_ipxe | default( foreman_operatingsystems_deb_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_ub2204_template_provision | default( foreman_operatingsystems_ub2x_template_provision | default( foreman_operatingsystems_deb_template_provision | default('Kickstart default') ) ) }}"
    # - template_kind: "PXEGrub"
    #   provisioning_template: "{{ foreman_operatingsystems_ub2204_template_pxegrub | default( foreman_operatingsystems_ub2x_template_pxegrub | default( foreman_operatingsystems_deb_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_ub2204_template_pxegrub2 | default( foreman_operatingsystems_ub2x_template_pxegrub2 | default( foreman_operatingsystems_deb_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_ub2204_template_pxelinux | default( foreman_operatingsystems_ub2x_template_pxelinux | default( foreman_operatingsystems_deb_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_ub2204_template_user_data | default( foreman_operatingsystems_ub2x_template_user_data | default( foreman_operatingsystems_deb_template_user_data | default('Kickstart default user data') ) ) }}"

foreman_operatingsystems_ubuntu2204:
  - name: "Ubuntu"
    release_name: jammy
    description: "Ubuntu 22.04 LTS (Jammy Jellyfish)"
    <<: *foreman_operatingsystems_defaults

foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Debian
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"
  operatingsystems:
    - Ubuntu 22.04 LTS (Jammy Jellyfish)

foreman_installation_media_ubuntu2204:
  - name: Ubuntu 22.04 LTS (Jammy Jellyfish)
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Ubuntu/ubuntu-2204/"
    <<: *foreman_installation_media_defaults

foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Ubuntu"
  auto_attach: False

foreman_activation_keys_ubuntu2204:
  - name: ak_ubuntu2204
    content_view: ccv_ubuntu2204
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2204"
        override: default
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2204-updates"
        override: default
      # - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2204-proposed"
      #   override: default
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2204-backports"
        override: disabled
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2204-security"
        override: disabled

foreman_sync_plan_products_ubuntu2204:
  - Ubuntu

