---

foreman_content_credentials_ubuntu2004: []

foreman_products_defaults: &foreman_products_defaults
  content_type: deb
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  mirroring_policy: "mirror_content_only"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy
  # deb_components: main restricted universe multiverse
  deb_components: main restricted
  deb_architectures: amd64

foreman_products_ubuntu2004:
  - name: Ubuntu
    label: Ubuntu
    repositories:
      - name: Ubuntu 20.04 LTS (Focal Fossa)
        label: ubuntu-2004
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ubuntu2004 }}/"
        deb_releases: focal
      - name: Ubuntu 20.04 LTS (Focal Fossa) - Updates
        label: ubuntu-2004-updates
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ubuntu2004 }}/"
        deb_releases: focal-updates
      # - name: Ubuntu 20.04 LTS (Focal Fossa) - Proposed Updates
      #   label: ubuntu-2004-proposed
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_ubuntu2004 }}/"
      #   deb_releases: focal-proposed
      - name: Ubuntu 20.04 LTS (Focal Fossa) - Backports
        label: ubuntu-2004-backports
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ubuntu2004 }}/"
        deb_releases: focal-backports
      - name: Ubuntu 20.04 LTS (Focal Fossa) - Security updates
        label: ubuntu-2004-security
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ubuntu2004 }}/"
        deb_releases: focal-security

foreman_content_views_ubuntu2004:
  - name: cv_ubuntu2004
    repositories:
      - name: Ubuntu 20.04 LTS (Focal Fossa)
        product: Ubuntu
    allow_promote: False
  - name: cv_ubuntu2004_updates
    repositories:
      - name: Ubuntu 20.04 LTS (Focal Fossa) - Updates
        product: Ubuntu
    allow_promote: False
  # - name: cv_ubuntu2004_proposed
  #   repositories:
  #     - name: Ubuntu 20.04 LTS (Focal Fossa) - Proposed Updates
  #       product: Ubuntu
  #   allow_promote: False
  - name: cv_ubuntu2004_backports
    repositories:
      - name: Ubuntu 20.04 LTS (Focal Fossa) - Backports
        product: Ubuntu
    allow_promote: False
  - name: cv_ubuntu2004_security
    repositories:
      - name: Ubuntu 20.04 LTS (Focal Fossa) - Security updates
        product: Ubuntu
    allow_promote: False

  - name: ccv_ubuntu2004
    composite: True
    auto_publish: True
    components:
      - content_view: cv_ubuntu2004
        latest: true
      - content_view: cv_ubuntu2004_updates
        latest: true
      # - content_view: cv_ubuntu2004_proposed
      #   latest: true
      - content_view: cv_ubuntu2004_backports
        latest: true
      - content_view: cv_ubuntu2004_security
        latest: true

foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Debian"
  password_hash: "SHA512"
  architectures:
    - amd64
  # ptables:
  #   - Preseed default autoinstall
  ptables: "{{
    [ 'Preseed default autoinstall' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Debian') | map(attribute='name') | list )
    }}"

foreman_operatingsystems_ubuntu2004:
  - name: "Ubuntu"
    release_name: focal
    description: "Ubuntu 20.04 LTS (Focal Fossa)"
    default_templates: "{{ foreman_operatingsystems_ubuntu2004_default_templates | default( foreman_operatingsystems_ubuntu2x_default_templates | default( foreman_operatingsystems_deb_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults

foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Debian
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"
  operatingsystems:
    - Ubuntu 20.04 LTS (Focal Fossa)

foreman_installation_media_ubuntu2004:
  - name: Ubuntu 20.04 LTS (Focal Fossa)
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Ubuntu/ubuntu-2004/"
    <<: *foreman_installation_media_defaults

foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Ubuntu"
  auto_attach: False

foreman_activation_keys_ubuntu2004:
  - name: ak_ubuntu2004
    content_view: ccv_ubuntu2004
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2004"
        override: default
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2004-updates"
        override: default
      # - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2004-proposed"
      #   override: default
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2004-backports"
        override: disabled
      - label: "{{ foreman_organization }}_Ubuntu_ubuntu-2004-security"
        override: disabled

foreman_sync_plan_products_ubuntu2004:
  - Ubuntu

