---
# redhat 9 content for foremen group vars file for katello-main

foreman_content_credentials_redhat9: []

foreman_products_redhat9:
  - name: Red Hat Enterprise Linux for x86_64
    repository_sets:
      # Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
        releasever: '9'
        # label: rhel-9-for-x86_64-baseos-rpms
      # Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
        releasever: '9'
        # label: rhel-9-for-x86_64-appstream-rpms
      # Red Hat Enterprise Linux 9 for x86_64 - Supplementary RPMs 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)
        releasever: '9'
        # label: rhel-9-for-x86_64-supplementary-rpms
      # Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
      - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-client-6-for-rhel-9-x86_64-rpms

      ### Unable to activate with these settings... ###
      # # Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.0
      # - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (Kickstart)
      #   # basearch: x86_64
      #   releasever: '9.0'
      #   # label: rhel-8-for-x86_64-baseos-kickstart
      # # Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.0
      # - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (Kickstart)
      #   # basearch: x86_64
      #   releasever: '9.0'
      #   # label: rhel-9-for-x86_64-appstream-kickstart
      # Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.1
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (Kickstart)
        # basearch: x86_64
        releasever: '9.1'
        # label: rhel-8-for-x86_64-baseos-kickstart
      # Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.1
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (Kickstart)
        # basearch: x86_64
        releasever: '9.1'
        # label: rhel-9-for-x86_64-appstream-kickstart

foreman_content_views_redhat9:
  - name: cv_rhel9_baseos
    repositories:
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
        product: 'Red Hat Enterprise Linux for x86_64'
    allow_promote: False
  - name: cv_rhel9_appstream
    repositories:
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
        product: 'Red Hat Enterprise Linux for x86_64'
    allow_promote: False
  - name: cv_rhel9_supplementary
    repositories:
      - name: Red Hat Enterprise Linux 9 for x86_64 - Supplementary RPMs 9
        product: 'Red Hat Enterprise Linux for x86_64'
    allow_promote: False
  - name: cv_rhel9_sat_client_6
    repositories:
      - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
        product: 'Red Hat Enterprise Linux for x86_64'
    allow_promote: False

  - name: ccv_rhel9
    composite: True
    auto_publish: True
    components:
      - content_view: cv_rhel9_baseos
        latest: true
      - content_view: cv_rhel9_appstream
        latest: true
      - content_view: cv_rhel9_supplementary
        latest: true
      - content_view: cv_rhel9_sat_client_6
        latest: true
      - content_view: cv_epel9
        latest: true

foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "CloudInit default"
    - template_kind: "finish"
      provisioning_template: "Kickstart default finish"
    - template_kind: "host_init_config"
      provisioning_template: "Linux host_init_config default"
    - template_kind: "iPXE"
      provisioning_template: "Kickstart default iPXE"
    - template_kind: "provision"
      provisioning_template: "Kickstart default"
    - template_kind: "PXEGrub"
      provisioning_template: "Kickstart default PXEGrub"
    - template_kind: "PXEGrub2"
      provisioning_template: "Kickstart default PXEGrub2"
    - template_kind: "PXELinux"
      provisioning_template: "Kickstart default PXELinux"
    - template_kind: "user_data"
      provisioning_template: "Kickstart default user data"

foreman_operatingsystems_redhat9:
  - name: "RedHat"
    major: "9"
    description: "Red Hat 9"
    <<: *foreman_operatingsystems_defaults
  - name: "RedHat"
    major: "9"
    minor: "0"
    description: "Red Hat 9.0"
    <<: *foreman_operatingsystems_defaults
  - name: "RedHat"
    major: "9"
    minor: "1"
    description: "Red Hat 9.1"
    <<: *foreman_operatingsystems_defaults

foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"

foreman_installation_media_redhat9:
  - name: Red Hat 9.0 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/content/dist/rhel9/9.0/x86_64/baseos/kickstart/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Red Hat 9
      - Red Hat 9.0
  - name: Red Hat 9.0 AppStream
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/content/dist/rhel9/9.0/x86_64/appstream/kickstart/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Red Hat 9
      - Red Hat 9.0

# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  lifecycle_environment: "Library"
  subscriptions:
    # Example to uyse a pool id
    # - pool_id: "8a88e9826db22df5016dd018abdd029b"
    # - name: "Red Hat Ansible Engine"
    # - name: "Red Hat Enterprise Linux for x86_64"
    - name: "Red Hat Enterprise Linux Server"
    # - name: "Red Hat Satellite"
    # - name: "Red Hat Satellite Capsule"
    # - name: "Red Hat Software Collections (for RHEL Server)"
    - name: "Extra Packages for Enterprise Linux"
    # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  service_level: Standard

foreman_activation_keys_defaults_el9: &foreman_activation_keys_defaults_el9
  <<: *foreman_activation_keys_defaults
  subscriptions:
    - name: "Red Hat Enterprise Linux for x86_64"
    - name: "Extra Packages for Enterprise Linux"
  release_version: 9

foreman_activation_keys_redhat9:
  - name: ak_rhel9
    content_view: ccv_rhel9
    <<: *foreman_activation_keys_defaults_el9
    subscriptions:
      - name: "Red Hat Enterprise Linux for x86_64"
      - name: "Extra Packages for Enterprise Linux"
    content_overrides:
      - label: rhel-9-for-x86_64-baseos-rpms
        override: default
      - label: rhel-9-for-x86_64-appstream-rpms
        override: default
      - label: rhel-9-for-x86_64-supplementary-rpms
        override: default
      - label: satellite-client-6-for-rhel-9-x86_64-rpms
        override: default
      - label: "{{ foreman_organization }}_EPEL_epel-9"
        override: default

foreman_sync_plan_products_redhat:
  - Red Hat Enterprise Linux for x86_64

