---
# redhat 7 content for foremen group vars file for katello-main

foreman_content_credentials_redhat7_rhocp: []

foreman_products_redhat7_rhocp:
  - name: Red Hat OpenShift Container Platform
    repository_sets:
      # Red Hat OpenShift Container Platform 4.10 RPMs x86_64
      - name: Red Hat OpenShift Container Platform 4.10 (RPMs)
        basearch: x86_64
        label: rhel-7-server-ose-4.10-rpms
      # Red Hat OpenShift Container Platform 4.11 RPMs x86_64
      - name: Red Hat OpenShift Container Platform 4.11 (RPMs)
        basearch: x86_64
        label: rhel-7-server-ose-4.11-rpms
      # # Red Hat OpenShift Container Platform 4.12 RPMs x86_64
      # - name: Red Hat OpenShift Container Platform 4.12 (RPMs)
      #   basearch: x86_64
      #   label: rhel-7-server-ose-4.12-rpms

foreman_content_views_redhat7_rhocp:
  - name: cv_rhel7_rhocp_4_10
    repositories:
      - name: Red Hat OpenShift Container Platform 4.10 RPMs x86_64
        product: 'Red Hat OpenShift Container Platform'
    allow_promote: False
  - name: cv_rhel7_rhocp_4_11
    repositories:
      - name: Red Hat OpenShift Container Platform 4.11 RPMs x86_64
        product: 'Red Hat OpenShift Container Platform'
    allow_promote: False
  # - name: cv_rhel7_rhocp_4_12
  #   repositories:
  #     - name: Red Hat OpenShift Container Platform 4.12 RPMs x86_64
  #       product: 'Red Hat OpenShift Container Platform'
  #   allow_promote: False

  - name: ccv_rhel7_rhocp
    composite: True
    auto_publish: True
    components:
      - content_view: cv_rhel7_base
        latest: true
      - content_view: cv_rhel7_extras
        latest: true
      - content_view: cv_rhel7_optional
        latest: true
      - content_view: cv_rhel7_supplementary
        latest: true
      - content_view: cv_rhel7_sat_client_6
        latest: true
      - content_view: cv_rhel7_rhscl
        latest: true
      - content_view: cv_rhel7_ansible_2
        latest: true
      - content_view: cv_rhel7_ansible_2_9
        latest: true
      - content_view: cv_rhel7_rhocp_4_10
        latest: true
      - content_view: cv_rhel7_rhocp_4_11
        latest: true
      # - content_view: cv_rhel7_rhocp_4_12
      #   latest: true

foreman_operatingsystems_redhat7_rhocp: []

foreman_installation_media_redhat7_rhocp: []

# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   # Example to uyse a pool id
  #   # - pool_id: "8a88e9826db22df5016dd018abdd029b"
  #   # - name: "Red Hat Ansible Engine"
  #   # - name: "Red Hat Ansible Automation Platform"
  #   # - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Red Hat Enterprise Linux Server"
  #   # - name: "Red Hat Satellite"
  #   # - name: "Red Hat Satellite Capsule"
  #   # - name: "Red Hat Software Collections (for RHEL Server)"
  #   # - name: "Red Hat OpenShift Container Platform"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  # service_level: Standard

foreman_activation_keys_defaults_el7: &foreman_activation_keys_defaults_el7
  <<: *foreman_activation_keys_defaults
  # subscriptions:
  #   - name: "Red Hat Ansible Engine"
  #   - name: "Red Hat Enterprise Linux Server"
  #   - name: "Red Hat Software Collections (for RHEL Server)"
  #   - name: "Extra Packages for Enterprise Linux"
  release_version: 7Server

foreman_activation_keys_redhat7_rhocp:
  - name: ak_rhel7_rhocp
    content_view: ccv_rhel7_rhocp
    <<: *foreman_activation_keys_defaults_el7
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux Server"
    #   - name: "Red Hat Software Collections (for RHEL Server)"
    #   - name: "Red Hat OpenShift Container Platform"
    content_overrides:
      - label: rhel-7-server-rpms
        override: default
      - label: rhel-7-server-extras-rpms
        override: default
      - label: rhel-7-server-optional-rpms
        override: default
      - label: rhel-7-server-supplementary-rpms
        override: default
      - label: rhel-7-server-satellite-client-6-rpms
        override: default
      - label: rhel-server-rhscl-7-rpms
        override: default
      - label: rhel-7-server-ansible-2-rpms
        override: default
      - label: rhel-7-server-ansible-2.9-rpms
        override: default
      - label: rhel-7-server-ose-4.10-rpms
        override: default
      - label: rhel-7-server-ose-4.11-rpms
        override: default
      # - label: rhel-7-server-ose-4.12-rpms
      #   override: default

foreman_sync_plan_products_redhat7_rhocp:
  - Red Hat Ansible Engine
  - Red Hat Enterprise Linux Server
  - Red Hat Software Collections (for RHEL Server)
  - Red Hat OpenShift Container Platform

