---
# defaults file for foreman_content_datadog

foreman_enable_datadog: false
foreman_enable_datadog_v6: false
foreman_enable_datadog_v7: "{{ foreman_enable_datadog | bool }}"

foreman_repo_baseurl_datadog: https://yum.datadoghq.com


foreman_content_credentials_datadog_main:
  - name: RPM-GPG-KEY-Datadog
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', 'https://keys.datadoghq.com/DATADOG_RPM_KEY_CURRENT.public', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/DATADOG_RPM_KEY_CURRENT.public') }}"

foreman_content_credentials_datadog: "{{ ( foreman_content_credentials_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_content_credentials_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_content_credentials_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_products_datadog_main: []
foreman_products_datadog: "{{ ( foreman_products_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_products_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_products_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_content_views_datadog_main: []
foreman_content_views_datadog: "{{ ( foreman_content_views_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_content_views_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_content_views_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_operatingsystems_datadog_main: []
foreman_operatingsystems_datadog: "{{ ( foreman_operatingsystems_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_operatingsystems_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_operatingsystems_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_installation_media_datadog_main: []
foreman_installation_media_datadog: "{{ ( foreman_installation_media_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_installation_media_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_installation_media_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_activation_keys_datadog_main: []
foreman_activation_keys_datadog: "{{ ( foreman_activation_keys_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_activation_keys_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_activation_keys_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

foreman_sync_plan_products_datadog_main:
  - Datadog

foreman_sync_plan_products_datadog: "{{ ( foreman_sync_plan_products_datadog_main | default([]) if foreman_enable_datadog | bool else [] ) |
  union( foreman_sync_plan_products_datadog_v6 | default([]) if foreman_enable_datadog_v6 | bool else [] ) |
  union( foreman_sync_plan_products_datadog_v7 | default([]) if foreman_enable_datadog_v7 | bool else [] )
  }}"

