---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-centosofficial
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_centos8_sig_kmods_main:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 8 - Kmods
        label: centos-8-kmods
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/kmods/x86_64/packages-main/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Kmods

foreman_products_centos8_sig_kmods_rebuild:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 8 - Kmods - Rebuild
        label: centos-8-kmods-rebuild
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/kmods/x86_64/packages-rebuild/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Kmods

foreman_products_centos8_sig_kmods: "{{ [] |
  union( foreman_products_centos8_sig_kmods_main | default([]) if foreman_enable_centos8_sig_kmods_main else [] ) |
  union( foreman_products_centos8_sig_kmods_rebuild | default([]) if foreman_enable_centos8_sig_kmods_rebuild else [] )
  }}"

foreman_content_views_centos8_sig_kmods_main:
  - name: cv_centos8_kmods
    repositories:
      - name: CentOS 8 - Kmods
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_kmods_rebuild:
  - name: cv_centos8_kmods_rebuild
    repositories:
      - name: CentOS 8 - Kmods - Rebuild
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_kmods: "{{ [] |
  union( foreman_content_views_centos8_sig_kmods_main | default([]) if foreman_enable_centos8_sig_kmods_main else [] ) |
  union( foreman_content_views_centos8_sig_kmods_rebuild | default([]) if foreman_enable_centos8_sig_kmods_rebuild else [] )
  }}"

