---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: "{{ foreman_products_defaults_download_policy_centos8 | default('on_demand') }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8 | default('mirror_complete') }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8 | default(false) }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8 | default('global_default_http_proxy') }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8 | default(false) | bool }}"


foreman_products_defaults_centos8_sig_kmods: &foreman_products_defaults_centos8_sig_kmods
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos8_sig_kmods | default('on_demand') }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8_sig_kmods | default('mirror_complete') }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8_sig_kmods | default(false) }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8_sig_kmods | default('global_default_http_proxy') }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8_sig_kmods | default(false) | bool }}"


foreman_products_centos8_sig_kmods_main:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_kmods_main }}"
    repositories:
      - name: CentOS 8 - Kmods
        label: centos-8-kmods
        <<: *foreman_products_defaults_centos8_sig_kmods
        url: "{{ foreman_repo_baseurl_centos8 }}/8/kmods/x86_64/packages-main/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Kmods
        organization: "{{ foreman_organization_centos8_sig_kmods_main }}"

foreman_products_centos8_sig_kmods_rebuild:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_kmods_rebuild }}"
    repositories:
      - name: CentOS 8 - Kmods - Rebuild
        label: centos-8-kmods-rebuild
        <<: *foreman_products_defaults_centos8_sig_kmods
        url: "{{ foreman_repo_baseurl_centos8 }}/8/kmods/x86_64/packages-rebuild/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Kmods
        organization: "{{ foreman_organization_centos8_sig_kmods_rebuild }}"

foreman_products_centos8_sig_kmods: "{{ [] |
  union( foreman_products_centos8_sig_kmods_main | default([]) if foreman_enable_centos8_sig_kmods_main else [] ) |
  union( foreman_products_centos8_sig_kmods_rebuild | default([]) if foreman_enable_centos8_sig_kmods_rebuild else [] )
  }}"


foreman_content_views_centos8_sig_kmods_main:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_kmods"
    organization: "{{ foreman_organization_centos8_sig_kmods_main }}"
    repositories:
      - name: CentOS 8 - Kmods
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_kmods_rebuild:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_kmods_rebuild"
    organization: "{{ foreman_organization_centos8_sig_kmods_rebuild }}"
    repositories:
      - name: CentOS 8 - Kmods - Rebuild
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_kmods: "{{ [] |
  union( foreman_content_views_centos8_sig_kmods_main | default([]) if foreman_enable_centos8_sig_kmods_main else [] ) |
  union( foreman_content_views_centos8_sig_kmods_rebuild | default([]) if foreman_enable_centos8_sig_kmods_rebuild else [] )
  }}"

