---

foreman_content_credentials_centos7:
  - name: RPM-GPG-KEY-CentOS-7
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', 'https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-CentOS-7') }}"
  - name: RPM-GPG-KEY-CentOS-Debug-7
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', 'https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Debug-7', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-CentOS-Debug-7') }}"
  - name: RPM-GPG-KEY-CentOS-Testing-7
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', 'https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Testing-7', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-CentOS-Testing-7') }}"


foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-7
  download_policy: immediate
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_on_demand: &foreman_products_on_demand
  <<: *foreman_products_defaults
  download_policy: on_demand


foreman_products_centos7:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 - Base
        label: centos-7-base
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos7 }}/7/os/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: CentOS 7 - Updates
        label: centos-7-updates
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos7 }}/7/updates/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: CentOS 7 - Extras
        label: centos-7-extras
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos7 }}/7/extras/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: CentOS 7 - Plus
        label: centos-7-plus
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos7 }}/7/centosplus/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: CentOS 7 - fasttrack
        label: centos-7-fasttrack
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos7 }}/7/fasttrack/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"

      - name: CentOS 7 - cr
        label: centos-7-cr
        <<: *foreman_products_on_demand
        url: "{{ foreman_repo_baseurl_centos7 }}/7/cr/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"

      - name: CentOS 7 LTS Kernels for x86_64
        label: centos-7-kernel
        <<: *foreman_products_on_demand
        url: "{{ foreman_repo_baseurl_centos_altarch }}/7/kernel/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"
      - name: CentOS 7 Experimental Kernels for x86_64
        label: centos-7-kernel-experimental
        <<: *foreman_products_on_demand
        url: "{{ foreman_repo_baseurl_centos_altarch }}/7/experimental/x86_64/"
        organization: "{{ foreman_organization_centos7 }}"


foreman_content_views_centos7:
  - name: cv_centos7_base
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 - Base
        product: CentOS
    allow_promote: False
  - name: cv_centos7_updates
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 - Updates
        product: CentOS
    allow_promote: False
  - name: cv_centos7_extras
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 - Extras
        product: CentOS
    allow_promote: False
  - name: cv_centos7_plus
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 - Plus
        product: CentOS
    allow_promote: False
  - name: cv_centos7_fasttrack
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 - fasttrack
        product: CentOS
    allow_promote: False

  - name: cv_centos7_cr
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 - cr
        product: CentOS
    allow_promote: False

  - name: cv_centos7_kernel
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 LTS Kernels for x86_64
        product: CentOS
    allow_promote: False
  - name: cv_centos7_kernel_experimental
    organization: "{{ foreman_organization_centos7 }}"
    repositories:
      - name: CentOS 7 Experimental Kernels for x86_64
        product: CentOS
    allow_promote: False

  - name: ccv_centos7
    organization: "{{ foreman_organization_centos7 }}"
    composite: True
    auto_publish: True
    components:
      - content_view: cv_centos7_base
        latest: true
      - content_view: cv_centos7_updates
        latest: true
      - content_view: cv_centos7_extras
        latest: true
      - content_view: cv_centos7_plus
        latest: true
      - content_view: cv_centos7_fasttrack
        latest: true
      - content_view: cv_centos7_cr
        latest: true
      - content_view: cv_centos7_kernel
        latest: true
      - content_view: cv_centos7_kernel_experimental
        latest: true
      - content_view: cv_epel7
        latest: true

  # - name: ccv_centos7_foreman
  #   organization: "{{ foreman_organization_centos7 }}"
  #   composite: True
  #   auto_publish: True
  #   components:
  #     - content_view: cv_centos7_base
  #       latest: true
  #     - content_view: cv_centos7_updates
  #       latest: true
  #     - content_view: cv_centos7_extras
  #       latest: true
  #     - content_view: cv_centos7_sclo_sclo
  #       latest: true
  #     - content_view: cv_centos7_sclo_rh
  #       latest: true
  #     - content_view: "cv_foreman_{{ foreman_version_label }}_el7"
  #       latest: true
  #     - content_view: "cv_foreman_plugins_{{ foreman_version_label }}_el7"
  #       latest: true
  #     - content_view: "cv_puppet{{ foreman_puppet_version }}_el7"
  #       latest: true

  # - name: ccv_centos7_katello
  #   organization: "{{ foreman_organization_centos7 }}"
  #   composite: True
  #   auto_publish: True
  #   components:
  #     - content_view: cv_centos7_base
  #       latest: true
  #     - content_view: cv_centos7_updates
  #       latest: true
  #     - content_view: cv_centos7_extras
  #       latest: true
  #     - content_view: cv_centos7_sclo_sclo
  #       latest: true
  #     - content_view: cv_centos7_sclo_rh
  #       latest: true
  #     - content_view: "cv_foreman_{{ foreman_version_label }}_el7"
  #       latest: true
  #     - content_view: "cv_foreman_plugins_{{ foreman_version_label }}_el7"
  #       latest: true
  #     - content_view: "cv_katello_{{ foreman_katello_version_label }}_el7"
  #       latest: true
  #     - content_view: "cv_katello_{{ foreman_katello_version_label }}_candlepin_el7"
  #       latest: true
  #     - content_view: "cv_pulpcore_{{ foreman_pulpcore_version_label }}_el7"
  #       latest: true
  #     - content_view: "cv_puppet{{ foreman_puppet_version }}_el7"
  #       latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"


foreman_operatingsystems_centos7:
  - name: "CentOS"
    major: "7"
    minor: ""
    description: "CentOS 7"
    default_templates: "{{ foreman_operatingsystems_centos7_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_centos7:
  - name: CentOS 7
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-7-base/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - CentOS 7
  # - name: CentOS 7 - Updates
  #   path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-7-updates/"
  #   <<: *foreman_installation_media_defaults
  #   operatingsystems:
  #     - CentOS 7
  # - name: CentOS 7 - Extras
  #   path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-7-extras/"
  #   <<: *foreman_installation_media_defaults
  #   operatingsystems:
  #     - CentOS 7
  # - name: CentOS 7 - CentOSPlus
  #   path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-7-centosplus/"
  #   <<: *foreman_installation_media_defaults
  #   operatingsystems:
  #     - CentOS 7
  # - name: CentOS 7 - Fasttrack
  #   path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-7-fasttrack/"
  #   <<: *foreman_installation_media_defaults
  #   operatingsystems:
  #     - CentOS 7


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "CentOS"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  # release_version: 7Server
  # service_level: Standard


foreman_activation_keys_centos7:
  - name: ak_centos7
    organization: "{{ foreman_organization_centos7 }}"
    content_view: ccv_centos7
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_CentOS_centos-7-base"
        override: default
      - label: "{{ foreman_organization }}_CentOS_centos-7-updates"
        override: default
      - label: "{{ foreman_organization }}_CentOS_centos-7-extras"
        override: default
      - label: "{{ foreman_organization }}_CentOS_centos-7-plus"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-7-fasttrack"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-7-cr"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-7-kernel"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-7-kernel-experimental"
        override: disabled
      - label: "{{ foreman_organization }}_EPEL_epel-7"
        override: disabled

  # - name: ak_centos7_foreman
  #   organization: "{{ foreman_organization_centos7 }}"
  #   content_view: ccv_centos7_foreman
  #   <<: *foreman_activation_keys_defaults
  #   content_overrides:
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-base"
  #       override: default
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-updates"
  #       override: default
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-extras"
  #       override: default
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-sclo-sclo"
  #       override: default
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-sclo-rh"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_foreman-{{ foreman_version_label }}-el7"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_foreman-plugins-{{ foreman_version_label }}-el7"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_puppet{{ foreman_puppet_version }}-el7"
  #       override: default

  # - name: ak_centos7_katello
  #   organization: "{{ foreman_organization_centos7 }}"
  #   content_view: ccv_centos7_katello
  #   <<: *foreman_activation_keys_defaults
  #   content_overrides:
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-base"
  #       override: default
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-updates"
  #       override: default
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-extras"
  #       override: default
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-sclo-sclo"
  #       override: default
  #     - label: "{{ foreman_organization }}_CentOS_centos-7-sclo-rh"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_foreman-{{ foreman_version_label }}-el7"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_foreman-plugins-{{ foreman_version_label }}-el7"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_katello-{{ foreman_katello_version_label }}-el7"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_katello-{{ foreman_katello_version_label }}-candlepin-el7"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_pulpcore-{{ foreman_pulpcore_version_label }}-el7"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_puppet{{ foreman_puppet_version }}_el7"
  #       override: default


foreman_sync_plan_products_centos7: []

