---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8 | bool }}"


foreman_products_defaults_centos_stream8_sig_opstools: &foreman_products_defaults_centos_stream8_sig_opstools
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8_sig_opstools }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8_sig_opstools }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8_sig_opstools | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8_sig_opstools }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8_sig_opstools | bool }}"

foreman_products_defaults_centos_stream8_sig_plus: &foreman_products_defaults_centos_stream8_sig_plus
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8_sig_plus }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8_sig_plus }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8_sig_plus | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8_sig_plus }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8_sig_plus | bool }}"

foreman_products_defaults_centos_stream8_sig_nfv: &foreman_products_defaults_centos_stream8_sig_nfv
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8_sig_nfv }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8_sig_nfv }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8_sig_nfv | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8_sig_nfv }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8_sig_nfv | bool }}"

foreman_products_defaults_centos_stream8_sig_messaging: &foreman_products_defaults_centos_stream8_sig_messaging
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos_stream8_sig_messaging }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos_stream8_sig_messaging }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos_stream8_sig_messaging | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos_stream8_sig_messaging }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos_stream8_sig_messaging | bool }}"


foreman_products_centos_stream8_sig_opstools:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_opstools }}"
    repositories:
      - name: CentOS Stream 8 - OpsTools - collectd
        label: centos-stream-8-opstools
        <<: *foreman_products_defaults_centos_stream8_sig_opstools
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/opstools/x86_64/collectd-5/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-OpsTools
        organization: "{{ foreman_organization_centos_stream8_sig_opstools }}"

foreman_content_views_centos_stream8_sig_opstools:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_opstools"
    organization: "{{ foreman_organization_centos_stream8_sig_opstools }}"
    repositories:
      - name: CentOS Stream 8 - OpsTools - collectd
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_opstools }}"


foreman_products_centos_stream8_sig_plus:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_plus }}"
    repositories:
      - name: CentOS Stream 8 - Plus
        label: centos-stream-8-plus
        <<: *foreman_products_defaults_centos_stream8_sig_plus
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/core/x86_64/centos-plus/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Core
        organization: "{{ foreman_organization_centos_stream8_sig_plus }}"

foreman_content_views_centos_stream8_sig_plus:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_plus"
    organization: "{{ foreman_organization_centos_stream8_sig_plus }}"
    repositories:
      - name: CentOS Stream 8 - Plus
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_plus }}"


foreman_products_centos_stream8_sig_nfv_extras:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_nfv_extras }}"
    repositories:
      - name: CentOS Stream 8 - NFV extras
        label: centos-stream-8-nfv-extras
        <<: *foreman_products_defaults_centos_stream8_sig_nfv
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/nfv/x86_64/network-extras/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-NFV
        organization: "{{ foreman_organization_centos_stream8_sig_nfv_extras }}"

foreman_products_centos_stream8_sig_nfv_openvswitch:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_nfv_openvswitch }}"
    repositories:
      - name: CentOS Stream 8 - NFV OpenvSwitch
        label: centos-stream-8-nfv-openvswitch
        <<: *foreman_products_defaults_centos_stream8_sig_nfv
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/nfv/x86_64/openvswitch-2/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-NFV
        organization: "{{ foreman_organization_centos_stream8_sig_nfv_openvswitch }}"

foreman_products_centos_stream8_sig_nfv: "{{ [] |
  union( foreman_products_centos_stream8_sig_nfv_extras | default([]) if foreman_enable_centos_stream8_sig_nfv_extras else [] ) |
  union( foreman_products_centos_stream8_sig_nfv_openvswitch | default([]) if foreman_enable_centos_stream8_sig_nfv_openvswitch else [] )
  }}"

foreman_content_views_centos_stream8_sig_nfv_extras:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_nfv_extras"
    organization: "{{ foreman_organization_centos_stream8_sig_nfv_extras }}"
    repositories:
      - name: CentOS Stream 8 - NFV extras
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_nfv_extras }}"

foreman_content_views_centos_stream8_sig_nfv_openvswitch:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_nfv_openvswitch"
    organization: "{{ foreman_organization_centos_stream8_sig_nfv_openvswitch }}"
    repositories:
      - name: CentOS Stream 8 - NFV OpenvSwitch
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_nfv_openvswitch }}"

foreman_content_views_centos_stream8_nfv: "{{ [] |
  union( foreman_content_views_centos_stream8_sig_nfv_extras | default([]) if foreman_enable_centos_stream8_sig_nfv_extras else [] ) |
  union( foreman_content_views_centos_stream8_sig_nfv_openvswitch | default([]) if foreman_enable_centos_stream8_sig_nfv_openvswitch else [] )
  }}"


foreman_products_centos_stream8_sig_messaging_qpid_proton:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_messaging_qpid_proton }}"
    repositories:
      - name: CentOS Stream 8 - QPID Proton
        label: centos-stream-8-qpid-proton
        <<: *foreman_products_defaults_centos_stream8_sig_messaging
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/messaging/x86_64/qpid-proton/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Messaging
        organization: "{{ foreman_organization_centos_stream8_sig_messaging_qpid_proton }}"

foreman_products_centos_stream8_sig_messaging_rabbitmq38:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_messaging_rabbitmq38 }}"
    repositories:
      - name: CentOS Stream 8 - RabbitMQ 38
        label: centos-stream-8-rabbitmq38
        <<: *foreman_products_defaults_centos_stream8_sig_messaging
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/messaging/x86_64/rabbitmq-38/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Messaging
        organization: "{{ foreman_organization_centos_stream8_sig_messaging_rabbitmq38 }}"


foreman_products_centos_stream8_sig_messaging: "{{ [] |
  union( foreman_products_centos_stream8_sig_messaging_qpid_proton | default([]) if foreman_enable_centos_stream8_sig_messaging_qpid_proton else [] ) |
  union( foreman_products_centos_stream8_sig_messaging_rabbitmq38 | default([]) if foreman_enable_centos_stream8_sig_messaging_rabbitmq38 else [] )
  }}"

foreman_content_views_centos_stream8_sig_messaging_qpid_proton:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_qpid_proton"
    organization: "{{ foreman_organization_centos_stream8_sig_messaging_qpid_proton }}"
    repositories:
      - name: CentOS Stream 8 - QPID Proton
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_messaging_qpid_proton }}"

foreman_content_views_centos_stream8_sig_messaging_rabbitmq38:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_rabbitmq38"
    organization: "{{ foreman_organization_centos_stream8_sig_messaging_rabbitmq38 }}"
    repositories:
      - name: CentOS Stream 8 - RabbitMQ 38
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos_stream8_sig_messaging_rabbitmq38 }}"

foreman_content_views_centos_stream8_sig_messaging: "{{ [] |
  union( foreman_content_views_centos_stream8_sig_messaging_qpid_proton | default([]) if foreman_enable_centos_stream8_sig_messaging_qpid_proton else [] ) |
  union( foreman_content_views_centos_stream8_sig_messaging_rabbitmq38 | default([]) if foreman_enable_centos_stream8_sig_messaging_rabbitmq38 else [] )
  }}"

