---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_centos_stream8_sig_opstools:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - OpsTools - collectd
        label: centos-stream-8-opstools
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/opstools/x86_64/collectd-5/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-OpsTools

foreman_content_views_centos_stream8_opstools:
  - name: cv_centos_stream8_opstools
    repositories:
      - name: CentOS Stream 8 - OpsTools - collectd
        product: CentOS
    allow_promote: False


foreman_products_centos_stream8_sig_plus:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - Plus
        label: centos-stream-8-plus
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/core/x86_64/centos-plus/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Core

foreman_content_views_centos_stream8_plus:
  - name: cv_centos_stream8_plus
    repositories:
      - name: CentOS Stream 8 - Plus
        product: CentOS
    allow_promote: False


foreman_products_centos_stream8_sig_nfv_extras:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - NFV extras
        label: centos-stream-8-nfv-extras
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/nfv/x86_64/network-extras/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-NFV

foreman_products_centos_stream8_sig_nfv_openvswitch:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - NFV OpenvSwitch
        label: centos-stream-8-nfv-openvswitch
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/nfv/x86_64/openvswitch-2/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-NFV

foreman_products_centos_stream8_sig_nfv: "{{ [] |
  union( foreman_products_centos_stream8_sig_nfv_extras | default([]) if foreman_enable_centos_stream8_sig_nfv_extras else [] ) |
  union( foreman_products_centos_stream8_sig_nfv_openvswitch | default([]) if foreman_enable_centos_stream8_sig_nfv_openvswitch else [] )
  }}"

foreman_content_views_centos_stream8_nfv_extras:
  - name: cv_centos_stream8_nfv_extras
    repositories:
      - name: CentOS Stream 8 - NFV extras
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_nfv_openvswitch:
  - name: cv_centos_stream8_nfv_openvswitch
    repositories:
      - name: CentOS Stream 8 - NFV OpenvSwitch
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_nfv: "{{ [] |
  union( foreman_content_views_centos_stream8_nfv_extras | default([]) if foreman_enable_centos_stream8_sig_nfv_extras else [] ) |
  union( foreman_content_views_centos_stream8_nfv_openvswitch | default([]) if foreman_enable_centos_stream8_sig_nfv_openvswitch else [] )
  }}"


foreman_products_centos_stream8_sig_messaging_qpid_proton:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - QPID Proton
        label: centos-stream-8-qpid-proton
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/messaging/x86_64/qpid-proton/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Messaging

foreman_products_centos_stream8_sig_messaging_rabbitmq38:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - RabbitMQ 38
        label: centos-stream-8-rabbitmq38
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/messaging/x86_64/rabbitmq-38/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Messaging


foreman_products_centos_stream8_sig_messaging: "{{ [] |
  union( foreman_products_centos_stream8_sig_messaging_qpid_proton | default([]) if foreman_enable_centos_stream8_sig_messaging_qpid_proton else [] ) |
  union( foreman_products_centos_stream8_sig_messaging_rabbitmq38 | default([]) if foreman_enable_centos_stream8_sig_messaging_rabbitmq38 else [] )
  }}"

foreman_content_views_centos_stream8_sig_messaging_qpid_proton:
  - name: cv_centos_stream8_qpid_proton
    repositories:
      - name: CentOS Stream 8 - QPID Proton
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_messaging_rabbitmq38:
  - name: cv_centos_stream8_rabbitmq38
    repositories:
      - name: CentOS Stream 8 - RabbitMQ 38
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_messaging: "{{ [] |
  union( foreman_content_views_centos_stream8_sig_messaging_qpid_proton | default([]) if foreman_enable_centos_stream8_sig_messaging_qpid_proton else [] ) |
  union( foreman_content_views_centos_stream8_sig_messaging_rabbitmq38 | default([]) if foreman_enable_centos_stream8_sig_messaging_rabbitmq38 else [] )
  }}"

