---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-centosofficial
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_centos8_sig_virtualization_advanced_virtualization:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 8 - Advanced Virtualization
        label: centos-8-advanced-virtualization
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/virt/x86_64/advanced-virtualization/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Virtualization

foreman_products_centos8_sig_virtualization_ovirt44:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 8 - oVirt 4.4
        label: centos-8-ovirt44
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/virt/x86_64/ovirt-44/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Virtualization

foreman_products_centos8_sig_virtualization: "{{ [] |
  union( foreman_products_centos8_sig_virtualization_advanced_virtualization | default([]) if foreman_enable_centos8_sig_virtualization_advanced_virtualization else [] ) |
  union( foreman_products_centos8_sig_virtualization_ovirt44 | default([]) if foreman_enable_centos8_sig_virtualization_ovirt44 else [] )
  }}"

foreman_content_views_centos8_sig_virtualization_advanced_virtualization:
  - name: cv_centos8_advanced_virtualization
    repositories:
      - name: CentOS 8 - Advanced Virtualization
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_virtualization_ovirt44:
  - name: cv_centos8_ovirt44
    repositories:
      - name: CentOS 8 - oVirt 4.4
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_virtualization: "{{ [] |
  union( foreman_content_views_centos8_sig_virtualization_advanced_virtualization | default([]) if foreman_enable_centos8_sig_virtualization_advanced_virtualization else [] ) |
  union( foreman_content_views_centos8_sig_virtualization_ovirt44 | default([]) if foreman_enable_centos8_sig_virtualization_ovirt44 else [] )
  }}"

