---

foreman_content_credentials_centos8: []


foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: "{{ foreman_products_defaults_download_policy_centos8 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8 | bool }}"


foreman_products_centos8:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - BaseOS
        label: centos-8-baseos
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/BaseOS/x86_64/os/"
        organization: "{{ foreman_organization_centos8 }}"
      - name: CentOS 8 - AppStream
        label: centos-8-appstream
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/AppStream/x86_64/os/"
        organization: "{{ foreman_organization_centos8 }}"
      - name: CentOS 8 - Extras
        label: centos-8-extras
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/extras/x86_64/os/"
        organization: "{{ foreman_organization_centos8 }}"
      - name: CentOS 8 - Plus
        label: centos-8-plus
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/centosplus/x86_64/os/"
        organization: "{{ foreman_organization_centos8 }}"
      - name: CentOS 8 - PowerTools
        label: centos-8-powertools
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/PowerTools/x86_64/os/"
        organization: "{{ foreman_organization_centos8 }}"
      - name: CentOS 8 - HighAvailability
        label: centos-8-ha
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/HighAvailability/x86_64/os/"
        organization: "{{ foreman_organization_centos8 }}"
      - name: CentOS 8 - ContinuousRelease
        label: centos-8-cr
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/cr/x86_64/os/"
        organization: "{{ foreman_organization_centos8 }}"
      - name: CentOS 8 - FastTrack
        label: centos-8-fasttrack
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/fasttrack/x86_64/os/"
        organization: "{{ foreman_organization_centos8 }}"

foreman_products_centos8_kickstart:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - BaseOS Kickstart
        label: centos-8-baseos-kickstart
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/BaseOS/x86_64/kickstart/"
        organization: "{{ foreman_organization_centos8 }}"
      - name: CentOS 8 - AppStream Kickstart
        label: centos-8-appstream-kickstart
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/AppStream/x86_64/kickstart/"
        organization: "{{ foreman_organization_centos8 }}"


foreman_content_views_centos8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_baseos"
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - BaseOS
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_appstream"
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - AppStream
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos8 }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_extras"
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - Extras
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_plus"
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - Plus
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_powertools"
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - PowerTools
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_ha"
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - HighAvailability
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_cr"
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - ContinuousRelease
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_fasttrack"
    organization: "{{ foreman_organization_centos8 }}"
    repositories:
      - name: CentOS 8 - FastTrack
        product: CentOS
    allow_promote: "{{ foreman_cv_allow_promote_centos8 }}"

foreman_composite_content_views_centos8:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}centos8"
    organization: "{{ foreman_organization_centos8 }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_centos8 }}"
    auto_publish: "{{ foreman_ccv_auto_publish_centos8 }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}centos8_baseos"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}centos8_appstream"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}centos8_extras"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}centos8_plus"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}centos8_powertools"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}centos8_ha"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}centos8_cr"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}centos8_fasttrack"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"


foreman_operatingsystems_centos8:
  - name: "CentOS"
    major: "8"
    minor: ""
    description: "CentOS 8"
    default_templates: "{{ foreman_operatingsystems_centos8_default_templates | default( foreman_operatingsystems_centos_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_centos8:
  - name: CentOS 8 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-8-baseos-kickstart/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - CentOS 8
  - name: CentOS 8 AppStream
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-8-appstream-kickstart/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - CentOS 8


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "CentOS"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  # release_version: 8
  # service_level: Standard


foreman_activation_keys_centos8:
  - name: ak_centos8
    organization: "{{ foreman_organization_centos8 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}centos8"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_CentOS_centos-8-baseos"
        override: enabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-appstream"
        override: enabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-extras"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-plus"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-powertools"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-ha"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-cr"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-fasttrack"
        override: disabled


foreman_sync_plan_products_centos8: []

