---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_centos_stream9_sig_hyperscale_main:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 9 - Hyperscale
        label: centos-stream-9-hyperscale
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/SIGs/9-stream/hyperscale/x86_64/packages-main/"
        gpgkey: RPM-GPG-KEY-CentOS-SIG-HyperScale

foreman_products_centos_stream9_sig_hyperscale_spin:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 9 - Hyperscale Spin
        label: centos-stream-9-hyperscale-spin
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/SIGs/9-stream/hyperscale/x86_64/packages-spin/"
        gpgkey: RPM-GPG-KEY-CentOS-SIG-HyperScale

foreman_products_centos_stream9_sig_hyperscale_experimental:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 9 - Hyperscale Experimental
        label: centos-stream-9-hyperscale-experimental
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/SIGs/9-stream/hyperscale/x86_64/packages-experimental/"
        gpgkey: RPM-GPG-KEY-CentOS-SIG-HyperScale

foreman_products_centos_stream9_sig_virtualization: "{{ [] |
  union( foreman_products_centos_stream9_sig_hyperscale_main | default([]) if foreman_enable_centos_stream9_sig_hyperscale_main else [] ) |
  union( foreman_products_centos_stream9_sig_hyperscale_spin | default([]) if foreman_enable_centos_stream9_sig_hyperscale_spin else [] ) |
  union( foreman_products_centos_stream9_sig_hyperscale_experimental | default([]) if foreman_enable_centos_stream9_sig_hyperscale_experimental else [] )
  }}"


foreman_content_views_centos_stream9_sig_hyperscale_main:
  - name: cv_centos_stream9_hyperscale
    repositories:
      - name: CentOS Stream 9 - Hyperscale
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream9_sig_hyperscale_spin:
  - name: cv_centos_stream9_hyperscale_spin
    repositories:
      - name: CentOS Stream 9 - Hyperscale Spin
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream9_sig_hyperscale_experimental:
  - name: cv_centos_stream9_hyperscale_experimental
    repositories:
      - name: CentOS Stream 9 - Hyperscale Experimental
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream9_sig_virtualization: "{{ [] |
  union( foreman_content_views_centos_stream9_sig_hyperscale_main | default([]) if foreman_enable_centos_stream9_sig_hyperscale_main else [] ) |
  union( foreman_content_views_centos_stream9_sig_hyperscale_spin | default([]) if foreman_enable_centos_stream9_sig_hyperscale_spin else [] ) |
  union( foreman_content_views_centos_stream9_sig_hyperscale_experimental | default([]) if foreman_enable_centos_stream9_sig_hyperscale_experimental else [] )
  }}"

