---
# centos content group vars file for foreman_content_centos

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-7
  download_policy: immediate
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_on_demand: &foreman_products_on_demand
  <<: *foreman_products_defaults
  download_policy: on_demand

foreman_products_centos7_sig_configmanagement_ansible26:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 7 - Configmanagement SIG - ansible26
        label: centos-7-ansible-26
        <<: *foreman_products_on_demand
        url: "{{ foreman_repo_baseurl_centos7 }}/7/configmanagement/x86_64/ansible26/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-ConfigManagement

foreman_products_centos7_sig_configmanagement_ansible27:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 7 - Configmanagement SIG - ansible-27
        label: centos-7-ansible-27
        <<: *foreman_products_on_demand
        url: "{{ foreman_repo_baseurl_centos7 }}/7/configmanagement/x86_64/ansible-27/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-ConfigManagement

foreman_products_centos7_sig_configmanagement_ansible28:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 7 - Configmanagement SIG - ansible-28
        label: centos-7-ansible-28
        <<: *foreman_products_on_demand
        url: "{{ foreman_repo_baseurl_centos7 }}/7/configmanagement/x86_64/ansible-28/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-ConfigManagement

foreman_products_centos7_sig_configmanagement_ansible29:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 7 - Configmanagement SIG - ansible-29
        label: centos-7-ansible-29
        <<: *foreman_products_on_demand
        url: "{{ foreman_repo_baseurl_centos7 }}/7/configmanagement/x86_64/ansible-29/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-ConfigManagement

foreman_products_centos7_sig_configmanagement: "{{ [] |
  union( foreman_products_centos7_sig_configmanagement_ansible26 | default([]) if foreman_enable_centos7_sig_configmanagement_ansible26 else [] ) |
  union( foreman_products_centos7_sig_configmanagement_ansible27 | default([]) if foreman_enable_centos7_sig_configmanagement_ansible27 else [] ) |
  union( foreman_products_centos7_sig_configmanagement_ansible28 | default([]) if foreman_enable_centos7_sig_configmanagement_ansible28 else [] ) |
  union( foreman_products_centos7_sig_configmanagement_ansible29 | default([]) if foreman_enable_centos7_sig_configmanagement_ansible29 else [] )
  }}"


foreman_content_views_centos7_sig_configmanagement_ansible26:
  - name: cv_centos7_ansible_26
    repositories:
      - name: CentOS 7 - Configmanagement SIG - ansible26
        product: CentOS
    allow_promote: False

foreman_content_views_centos7_sig_configmanagement_ansible27:
  - name: cv_centos7_ansible_27
    repositories:
      - name: CentOS 7 - Configmanagement SIG - ansible-27
        product: CentOS
    allow_promote: False

foreman_content_views_centos7_sig_configmanagement_ansible28:
  - name: cv_centos7_ansible_28
    repositories:
      - name: CentOS 7 - Configmanagement SIG - ansible-28
        product: CentOS
    allow_promote: False

foreman_content_views_centos7_sig_configmanagement_ansible29:
  - name: cv_centos7_ansible_29
    repositories:
      - name: CentOS 7 - Configmanagement SIG - ansible-29
        product: CentOS
    allow_promote: False

foreman_content_views_centos7_sig_configmanagement: "{{ [] |
  union( foreman_content_views_centos7_sig_configmanagement_ansible26 | default([]) if foreman_enable_centos7_sig_configmanagement_ansible26 else [] ) |
  union( foreman_content_views_centos7_sig_configmanagement_ansible27 | default([]) if foreman_enable_centos7_sig_configmanagement_ansible27 else [] ) |
  union( foreman_content_views_centos7_sig_configmanagement_ansible28 | default([]) if foreman_enable_centos7_sig_configmanagement_ansible28 else [] ) |
  union( foreman_content_views_centos7_sig_configmanagement_ansible29 | default([]) if foreman_enable_centos7_sig_configmanagement_ansible29 else [] )
  }}"

