---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: "{{ foreman_products_defaults_download_policy_centos8 | default('on_demand') }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8 | default('mirror_complete') }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8 | default(false) }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8 | default('global_default_http_proxy') }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8 | default(false) | bool }}"


foreman_products_defaults_centos8_sig_virtualization: &foreman_products_defaults_centos8_sig_virtualization
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos8_sig_virtualization | default('on_demand') }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos8_sig_virtualization | default('mirror_complete') }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos8_sig_virtualization | default(false) }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos8_sig_virtualization | default('global_default_http_proxy') }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos8_sig_virtualization | default(false) | bool }}"


foreman_products_centos8_sig_virtualization_advanced_virtualization:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_virtualization_advanced_virtualization }}"
    repositories:
      - name: CentOS 8 - Advanced Virtualization
        label: centos-8-advanced-virtualization
        <<: *foreman_products_defaults_centos8_sig_virtualization
        url: "{{ foreman_repo_baseurl_centos8 }}/8/virt/x86_64/advanced-virtualization/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Virtualization
        organization: "{{ foreman_organization_centos8_sig_virtualization_advanced_virtualization }}"

foreman_products_centos8_sig_virtualization_ovirt44:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_virtualization_ovirt44 }}"
    repositories:
      - name: CentOS 8 - oVirt 4.4
        label: centos-8-ovirt44
        <<: *foreman_products_defaults_centos8_sig_virtualization
        url: "{{ foreman_repo_baseurl_centos8 }}/8/virt/x86_64/ovirt-44/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Virtualization
        organization: "{{ foreman_organization_centos8_sig_virtualization_ovirt44 }}"

foreman_products_centos8_sig_virtualization: "{{ [] |
  union( foreman_products_centos8_sig_virtualization_advanced_virtualization | default([]) if foreman_enable_centos8_sig_virtualization_advanced_virtualization else [] ) |
  union( foreman_products_centos8_sig_virtualization_ovirt44 | default([]) if foreman_enable_centos8_sig_virtualization_ovirt44 else [] )
  }}"


foreman_content_views_centos8_sig_virtualization_advanced_virtualization:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_advanced_virtualization"
    organization: "{{ foreman_organization_centos8_sig_virtualization_advanced_virtualization }}"
    repositories:
      - name: CentOS 8 - Advanced Virtualization
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_virtualization_ovirt44:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos8_ovirt44"
    organization: "{{ foreman_organization_centos8_sig_virtualization_ovirt44 }}"
    repositories:
      - name: CentOS 8 - oVirt 4.4
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_virtualization: "{{ [] |
  union( foreman_content_views_centos8_sig_virtualization_advanced_virtualization | default([]) if foreman_enable_centos8_sig_virtualization_advanced_virtualization else [] ) |
  union( foreman_content_views_centos8_sig_virtualization_ovirt44 | default([]) if foreman_enable_centos8_sig_virtualization_ovirt44 else [] )
  }}"

