---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  # gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_centos8_sig_storage_samba411:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_samba411 }}"
    repositories:
      - name: CentOS 8 - Samba 4.11
        label: centos-8-samba411
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/samba-411/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_samba411 }}"

foreman_products_centos8_sig_storage_samba412:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_samba412 }}"
    repositories:
      - name: CentOS 8 - Samba 4.12
        label: centos-8-samba412
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/samba-412/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_samba412 }}"

foreman_products_centos8_sig_storage_samba413:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_samba413 }}"
    repositories:
      - name: CentOS 8 - Samba 4.13
        label: centos-8-samba413
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/samba-413/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_samba413 }}"

foreman_products_centos8_sig_storage_samba414:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_samba414 }}"
    repositories:
      - name: CentOS 8 - Samba 4.14
        label: centos-8-samba414
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/samba-414/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_samba414 }}"

foreman_products_centos8_sig_storage_samba415:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_samba415 }}"
    repositories:
      - name: CentOS 8 - Samba 4.15
        label: centos-8-samba415
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/samba-415/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_samba415 }}"

foreman_products_centos8_sig_storage_gluster6:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_gluster6 }}"
    repositories:
      - name: CentOS 8 - Gluster 6
        label: centos-8-gluster6
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/gluster-6/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_gluster6 }}"

foreman_products_centos8_sig_storage_gluster7:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_gluster7 }}"
    repositories:
      - name: CentOS 8 - Gluster 7
        label: centos-8-gluster7
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/gluster-7/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_gluster7 }}"

foreman_products_centos8_sig_storage_gluster8:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_gluster8 }}"
    repositories:
      - name: CentOS 8 - Gluster 8
        label: centos-8-gluster8
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/gluster-8/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_gluster8 }}"

foreman_products_centos8_sig_storage_gluster9:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_gluster9 }}"
    repositories:
      - name: CentOS 8 - Gluster 9
        label: centos-8-gluster9
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/gluster-9/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_gluster9 }}"

foreman_products_centos8_sig_storage_ceph_nautilus:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_ceph_nautilus }}"
    repositories:
      - name: CentOS 8 - Ceph Nautilus
        label: centos-8-ceph-nautilus
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/ceph-nautilus/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_ceph_nautilus }}"

foreman_products_centos8_sig_storage_ceph_octopus:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_ceph_octopus }}"
    repositories:
      - name: CentOS 8 - Ceph Octopus
        label: centos-8-ceph-octopus
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/ceph-octopus/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage

foreman_products_centos8_sig_storage_ceph_pacific:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_ceph_pacific }}"
    repositories:
      - name: CentOS 8 - Ceph Pacific
        label: centos-8-ceph-pacific
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/ceph-pacific/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_ceph_pacific }}"

foreman_products_centos8_sig_storage_nfs_ganesha28:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_nfs_ganesha28 }}"
    repositories:
      - name: CentOS 8 - NFS Ganesha 2.8
        label: centos-8-nfs-ganesha28
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/nfs-ganesha-28/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_nfs_ganesha28 }}"

foreman_products_centos8_sig_storage_nfs_ganesha30:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos8_sig_storage_nfs_ganesha30 }}"
    repositories:
      - name: CentOS 8 - NFS Ganesha 3.0
        label: centos-8-nfs-ganesha30
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/storage/x86_64/nfs-ganesha-30/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Storage
        organization: "{{ foreman_organization_centos8_sig_storage_nfs_ganesha30 }}"

foreman_products_centos8_sig_storage: "{{ [] |
  union ( foreman_products_centos8_sig_storage_samba411 | default([]) if foreman_enable_centos8_sig_storage_samba411 else [] ) |
  union ( foreman_products_centos8_sig_storage_samba412 | default([]) if foreman_enable_centos8_sig_storage_samba412 else [] ) |
  union ( foreman_products_centos8_sig_storage_samba413 | default([]) if foreman_enable_centos8_sig_storage_samba413 else [] ) |
  union ( foreman_products_centos8_sig_storage_samba414 | default([]) if foreman_enable_centos8_sig_storage_samba414 else [] ) |
  union ( foreman_products_centos8_sig_storage_samba415 | default([]) if foreman_enable_centos8_sig_storage_samba415 else [] ) |
  union ( foreman_products_centos8_sig_storage_gluster6 | default([]) if foreman_enable_centos8_sig_storage_gluster6 else [] ) |
  union ( foreman_products_centos8_sig_storage_gluster7 | default([]) if foreman_enable_centos8_sig_storage_gluster7 else [] ) |
  union ( foreman_products_centos8_sig_storage_gluster8 | default([]) if foreman_enable_centos8_sig_storage_gluster8 else [] ) |
  union ( foreman_products_centos8_sig_storage_gluster9 | default([]) if foreman_enable_centos8_sig_storage_gluster9 else [] ) |
  union ( foreman_products_centos8_sig_storage_ceph_nautilus | default([]) if foreman_enable_centos8_sig_storage_ceph_nautilus else [] ) |
  union ( foreman_products_centos8_sig_storage_ceph_octopus | default([]) if foreman_enable_centos8_sig_storage_ceph_octopus else [] ) |
  union ( foreman_products_centos8_sig_storage_ceph_pacific | default([]) if foreman_enable_centos8_sig_storage_ceph_pacific else [] ) |
  union ( foreman_products_centos8_sig_storage_nfs_ganesha28 | default([]) if foreman_enable_centos8_sig_storage_nfs_ganesha28 else [] ) |
  union ( foreman_products_centos8_sig_storage_nfs_ganesha30 | default([]) if foreman_enable_centos8_sig_storage_nfs_ganesha30 else [] )
  }}"


foreman_content_views_centos8_sig_storage_samba411:
  - name: cv_centos8_samba411
    organization: "{{ foreman_organization_centos8_sig_storage_samba411 }}"
    repositories:
      - name: CentOS 8 - Samba 4.11
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_samba412:
  - name: cv_centos8_samba412
    organization: "{{ foreman_organization_centos8_sig_storage_samba412 }}"
    repositories:
      - name: CentOS 8 - Samba 4.12
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_samba413:
  - name: cv_centos8_samba413
    organization: "{{ foreman_organization_centos8_sig_storage_samba413 }}"
    repositories:
      - name: CentOS 8 - Samba 4.13
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_samba414:
  - name: cv_centos8_samba414
    organization: "{{ foreman_organization_centos8_sig_storage_samba414 }}"
    repositories:
      - name: CentOS 8 - Samba 4.14
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_samba415:
  - name: cv_centos8_samba415
    organization: "{{ foreman_organization_centos8_sig_storage_samba415 }}"
    repositories:
      - name: CentOS 8 - Samba 4.15
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_gluster6:
  - name: cv_centos8_gluster6
    organization: "{{ foreman_organization_centos8_sig_storage_gluster6 }}"
    repositories:
      - name: CentOS 8 - Gluster 6
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_gluster7:
  - name: cv_centos8_gluster7
    organization: "{{ foreman_organization_centos8_sig_storage_gluster7 }}"
    repositories:
      - name: CentOS 8 - Gluster 7
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_gluster8:
  - name: cv_centos8_gluster8
    organization: "{{ foreman_organization_centos8_sig_storage_gluster8 }}"
    repositories:
      - name: CentOS 8 - Gluster 8
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_gluster9:
  - name: cv_centos8_gluster9
    organization: "{{ foreman_organization_centos8_sig_storage_gluster9 }}"
    repositories:
      - name: CentOS 8 - Gluster 9
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_ceph_nautilus:
  - name: cv_centos8_ceph_nautilus
    organization: "{{ foreman_organization_centos8_sig_storage_ceph_nautilus }}"
    repositories:
      - name: CentOS 8 - Ceph Nautilus
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_ceph_octopus:
  - name: cv_centos8_ceph_octopus
    organization: "{{ foreman_organization_centos8_sig_storage_ceph_octopus }}"
    repositories:
      - name: CentOS 8 - Ceph Octopus
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_ceph_pacific:
  - name: cv_centos8_ceph_pacific
    organization: "{{ foreman_organization_centos8_sig_storage_ceph_pacific }}"
    repositories:
      - name: CentOS 8 - Ceph Pacific
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_nfs_ganesha28:
  - name: cv_centos8_nfs_ganesha28
    organization: "{{ foreman_organization_centos8_sig_storage_nfs_ganesha28 }}"
    repositories:
      - name: CentOS 8 - NFS Ganesha 2.8
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage_nfs_ganesha30:
  - name: cv_centos8_nfs_ganesha30
    organization: "{{ foreman_organization_centos8_sig_storage_nfs_ganesha30 }}"
    repositories:
      - name: CentOS 8 - NFS Ganesha 3.0
        product: CentOS
    allow_promote: False

foreman_content_views_centos8_sig_storage: "{{ [] |
  union ( foreman_content_views_centos8_sig_storage_samba411 | default([]) if foreman_enable_centos8_sig_storage_samba411 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_samba412 | default([]) if foreman_enable_centos8_sig_storage_samba412 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_samba413 | default([]) if foreman_enable_centos8_sig_storage_samba413 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_samba414 | default([]) if foreman_enable_centos8_sig_storage_samba414 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_samba415 | default([]) if foreman_enable_centos8_sig_storage_samba415 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_gluster6 | default([]) if foreman_enable_centos8_sig_storage_gluster6 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_gluster7 | default([]) if foreman_enable_centos8_sig_storage_gluster7 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_gluster8 | default([]) if foreman_enable_centos8_sig_storage_gluster8 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_gluster9 | default([]) if foreman_enable_centos8_sig_storage_gluster9 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_ceph_nautilus | default([]) if foreman_enable_centos8_sig_storage_ceph_nautilus else [] ) |
  union ( foreman_content_views_centos8_sig_storage_ceph_octopus | default([]) if foreman_enable_centos8_sig_storage_ceph_octopus else [] ) |
  union ( foreman_content_views_centos8_sig_storage_ceph_pacific | default([]) if foreman_enable_centos8_sig_storage_ceph_pacific else [] ) |
  union ( foreman_content_views_centos8_sig_storage_nfs_ganesha28 | default([]) if foreman_enable_centos8_sig_storage_nfs_ganesha28 else [] ) |
  union ( foreman_content_views_centos8_sig_storage_nfs_ganesha30 | default([]) if foreman_enable_centos8_sig_storage_nfs_ganesha30 else [] )
  }}"

