---
# centos content group vars file for foreman_content_centos

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-centosofficial
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_centos_stream8_sig_hyperscale_main:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - Hyperscale
        label: centos-stream-8-hyperscale
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/hyperscale/x86_64/packages-main/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-HyperScale

foreman_products_centos_stream8_sig_hyperscale_hotfixes:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - Hyperscale Hotfixes
        label: centos-stream-8-hyperscale-hotfixes
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/hyperscale/x86_64/packages-hotfixes/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-HyperScale

foreman_products_centos_stream8_sig_hyperscale_spin:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - Hyperscale Spin
        label: centos-stream-8-hyperscale-spin
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/hyperscale/x86_64/packages-spin/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-HyperScale

foreman_products_centos_stream8_sig_hyperscale_experimental:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS Stream 8 - Hyperscale Experimental
        label: centos-stream-8-hyperscale-experimental
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/hyperscale/x86_64/packages-experimental/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-HyperScale

foreman_products_centos_stream8_sig_virtualization: "{{ [] |
  union( foreman_products_centos_stream8_sig_hyperscale_main | default([]) if foreman_enable_centos_stream8_sig_hyperscale_main else [] ) |
  union( foreman_products_centos_stream8_sig_hyperscale_hotfixes | default([]) if foreman_enable_centos_stream8_sig_hyperscale_hotfixes else [] ) |
  union( foreman_products_centos_stream8_sig_hyperscale_spin | default([]) if foreman_enable_centos_stream8_sig_hyperscale_spin else [] ) |
  union( foreman_products_centos_stream8_sig_hyperscale_experimental | default([]) if foreman_enable_centos_stream8_sig_hyperscale_experimental else [] )
  }}"

foreman_content_views_centos_stream8_sig_hyperscale_main:
  - name: cv_centos_stream8_hyperscale
    repositories:
      - name: CentOS Stream 8 - Hyperscale
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_hyperscale_hotfixes:
  - name: cv_centos_stream8_hyperscale_hotfixes
    repositories:
      - name: CentOS Stream 8 - Hyperscale Hotfixes
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_hyperscale_spin:
  - name: cv_centos_stream8_hyperscale_spin
    repositories:
      - name: CentOS Stream 8 - Hyperscale Spin
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_hyperscale_experimental:
  - name: cv_centos_stream8_hyperscale_experimental
    repositories:
      - name: CentOS Stream 8 - Hyperscale Experimental
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_virtualization: "{{ [] |
  union( foreman_content_views_centos_stream8_sig_hyperscale_main | default([]) if foreman_enable_centos_stream8_sig_hyperscale_main else [] ) |
  union( foreman_content_views_centos_stream8_sig_hyperscale_hotfixes | default([]) if foreman_enable_centos_stream8_sig_hyperscale_hotfixes else [] ) |
  union( foreman_content_views_centos_stream8_sig_hyperscale_spin | default([]) if foreman_enable_centos_stream8_sig_hyperscale_spin else [] ) |
  union( foreman_content_views_centos_stream8_sig_hyperscale_experimental | default([]) if foreman_enable_centos_stream8_sig_hyperscale_experimental else [] )
  }}"

