---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_centos_stream9_sig_virtualization_ovirt45:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream9_sig_virtualization_ovirt45 }}"
    repositories:
      - name: CentOS Stream 9 - oVirt 4.5
        label: centos-stream-9-ovirt45
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream9 }}/SIGs/9-stream/virt/x86_64/ovirt-45/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Virtualization
        organization: "{{ foreman_organization_centos_stream9_sig_virtualization_ovirt45 }}"
      - name: oVirt upstream for CentOS Stream 9 - oVirt 4.5
        label: centos-stream-9-ovirt-45-upstream
        <<: *foreman_products_defaults
        url: "https://{{ foreman_repo_baseurl_ovirt }}/pub/ovirt-4.5/rpm/el9/"
        gpg_key: RPM-GPG-KEY-oVirt-4.5
        organization: "{{ foreman_organization_centos_stream9_sig_virtualization_ovirt45 }}"

foreman_products_centos_stream9_sig_virtualization: "{{ [] |
  union( foreman_products_centos_stream9_sig_virtualization_ovirt45 | default([]) if foreman_enable_centos_stream9_sig_virtualization_ovirt45 else [] )
  }}"


foreman_content_views_centos_stream9_sig_virtualization_ovirt45:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream9_ovirt45"
    organization: "{{ foreman_organization_centos_stream9_sig_virtualization_ovirt45 }}"
    repositories:
      - name: CentOS Stream 9 - oVirt 4.5
        product: CentOS
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream9_ovirt_45_upstream"
    organization: "{{ foreman_organization_centos_stream9_sig_virtualization_ovirt45 }}"
    repositories:
      - name: oVirt upstream for CentOS Stream 9 - oVirt 4.5
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream9_sig_virtualization: "{{ [] |
  union( foreman_content_views_centos_stream9_sig_virtualization_ovirt45 | default([]) if foreman_enable_centos_stream9_sig_virtualization_ovirt45 else [] )
  }}"

