---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-7
  download_policy: "{{ foreman_products_defaults_download_policy_centos7 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos7 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos7 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos7 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos7 | bool }}"


foreman_products_defaults_centos7_dotnet: &foreman_products_defaults_centos7_dotnet
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos7_dotnet }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos7_dotnet }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos7_dotnet | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos7_dotnet }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos7_dotnet | bool }}"

foreman_products_defaults_centos7_sig_sclo: &foreman_products_defaults_centos7_sig_sclo
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos7_sig_sclo }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos7_sig_sclo }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos7_sig_sclo | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos7_sig_sclo }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos7_sig_sclo | bool }}"

foreman_products_defaults_centos7_sig_opstools: &foreman_products_defaults_centos7_sig_opstools
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos7_sig_opstools }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos7_sig_opstools }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos7_sig_opstools | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos7_sig_opstools }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos7_sig_opstools | bool }}"

foreman_products_defaults_centos7_sig_nfv: &foreman_products_defaults_centos7_sig_nfv
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_centos7_sig_nfv }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_centos7_sig_nfv }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_centos7_sig_nfv | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_centos7_sig_nfv }}"
  unprotected: "{{ foreman_products_defaults_unprotected_centos7_sig_nfv | bool }}"


foreman_products_centos7_dotnet:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos7_dotnet }}"
    repositories:
      - name: CentOS 7 - DotNet
        label: centos-7-dotnet
        <<: *foreman_products_defaults_centos7_dotnet
        url: "{{ foreman_repo_baseurl_centos7 }}/7/dotnet/x86_64/"
        gpg_key: RPM-GPG-KEY-CentOS-7
        organization: "{{ foreman_organization_centos7_dotnet }}"

foreman_content_views_centos7_dotnet:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos7_dotnet"
    organization: "{{ foreman_organization_centos7_dotnet }}"
    repositories:
      - name: CentOS 7 - DotNet
        product: CentOS
    allow_promote: False


foreman_products_centos7_sig_sclo:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos7_sig_sclo }}"
    repositories:
      - name: CentOS 7 - SCLo sclo
        label: centos-7-sclo-sclo
        <<: *foreman_products_defaults_centos7_sig_sclo
        url: "{{ foreman_repo_baseurl_centos7 }}/7/sclo/x86_64/sclo/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-SCLo
        organization: "{{ foreman_organization_centos7_sig_sclo }}"
      - name: CentOS 7 - SCLo rh
        label: centos-7-sclo-rh
        <<: *foreman_products_defaults_centos7_sig_sclo
        url: "{{ foreman_repo_baseurl_centos7 }}/7/sclo/x86_64/rh/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-SCLo
        organization: "{{ foreman_organization_centos7_sig_sclo }}"

foreman_content_views_centos7_sig_sclo:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos7_sclo_sclo"
    organization: "{{ foreman_organization_centos7_sig_sclo }}"
    repositories:
      - name: CentOS 7 - SCLo sclo
        product: CentOS
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos7_sclo_rh"
    organization: "{{ foreman_organization_centos7_sig_sclo }}"
    repositories:
      - name: CentOS 7 - SCLo rh
        product: CentOS
    allow_promote: False


foreman_products_centos7_sig_opstools:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos7_sig_opstools }}"
    repositories:
      - name: CentOS 7 - OpsTools - release
        label: centos-7-release-opstools
        <<: *foreman_products_defaults_centos7_sig_opstools
        url: "{{ foreman_repo_baseurl_centos7 }}/7/opstools/x86_64/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-OpsTools
        organization: "{{ foreman_organization_centos7_sig_opstools }}"

foreman_content_views_centos7_sig_opstools:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos7_release_opstools"
    organization: "{{ foreman_organization_centos7_sig_opstools }}"
    repositories:
      - name: CentOS 7 - OpsTools - release
        product: CentOS
    allow_promote: False


foreman_products_centos7_sig_nfv_common:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos7_sig_nfv_common }}"
    repositories:
      - name: CentOS 7 - nfv common
        label: centos-7-nfv-common
        <<: *foreman_products_defaults_centos7_sig_nfv
        url: "{{ foreman_repo_baseurl_centos7 }}/7/nfv/x86_64/common/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-NFV
        organization: "{{ foreman_organization_centos7_sig_nfv_common }}"

foreman_products_centos7_sig_nfv_fdio:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos7_sig_nfv_fdio }}"
    repositories:
      - name: CentOS 7 - fd.io
        label: centos-7-fdio
        <<: *foreman_products_defaults_centos7_sig_nfv
        url: "{{ foreman_repo_baseurl_centos7 }}/7/nfv/x86_64/fdio/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-NFV
        organization: "{{ foreman_organization_centos7_sig_nfv_fdio }}"

foreman_products_centos7_sig_nfv: "{{ [] |
  union( foreman_products_centos7_sig_nfv_common | default([]) if foreman_enable_centos7_sig_nfv_common else [] ) |
  union( foreman_products_centos7_sig_nfv_fdio | default([]) if foreman_enable_centos7_sig_nfv_fdio else [] )
  }}"

foreman_content_views_centos7_sig_nfv_common:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos7_nfv_common"
    organization: "{{ foreman_organization_centos7_sig_nfv_common }}"
    repositories:
      - name: CentOS 7 - nfv common
        product: CentOS
    allow_promote: False

foreman_content_views_centos7_sig_nfv_fdio:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos7_fdio"
    organization: "{{ foreman_organization_centos7_sig_nfv_fdio }}"
    repositories:
      - name: CentOS 7 - fd.io
        product: CentOS
    allow_promote: False

foreman_content_views_centos7_nfv: "{{ [] |
  union( foreman_content_views_centos7_sig_nfv_common | default([]) if foreman_enable_centos7_sig_nfv_common else [] ) |
  union( foreman_content_views_centos7_sig_nfv_fdio | default([]) if foreman_enable_centos7_sig_nfv_fdio else [] )
  }}"

