---

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-CentOS-Official
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy


foreman_products_centos_stream8_sig_virtualization_advanced_virtualization:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_advanced_virtualization }}"
    repositories:
      - name: CentOS Stream 8 - Advanced Virtualization
        label: centos-stream-8-advanced-virtualization
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/virt/x86_64/advancedvirt-common/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Virtualization
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_advanced_virtualization }}"

foreman_products_centos_stream8_sig_virtualization_ovirt44:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt44 }}"
    repositories:
      - name: CentOS 8 - oVirt 4.4
        label: centos-8-ovirt44
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos8 }}/8/virt/x86_64/ovirt-44/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Virtualization
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt44 }}"

foreman_products_centos_stream8_sig_virtualization_ovirt45:
  - name: CentOS
    label: CentOS
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
    repositories:
      - name: CentOS Stream 8 - oVirt 4.5
        label: centos-stream-8-ovirt45
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/virt/x86_64/ovirt-45/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Virtualization
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
      - name: CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository
        label: centos-stream-8-ovirt45-openstack-yoga
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_stream8 }}/8-stream/cloud/x86_64/openstack-yoga/"
        gpg_key: RPM-GPG-KEY-CentOS-SIG-Cloud
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
      - name: CentOS Stream 8 - oVirt 4.5 - upstream
        label: centos-stream-8-ovirt45-upstream
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_ovirt }}/pub/ovirt-4.5/rpm/el8/"
        gpg_key: RPM-GPG-KEY-oVirt-4.5
        organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"

foreman_products_centos_stream8_sig_virtualization: "{{ [] |
  union( foreman_products_centos_stream8_sig_virtualization_advanced_virtualization | default([]) if foreman_enable_centos_stream8_sig_virtualization_advanced_virtualization else [] ) |
  union( foreman_products_centos_stream8_sig_virtualization_ovirt44 | default([]) if foreman_enable_centos_stream8_sig_virtualization_ovirt44 else [] ) |
  union( foreman_products_centos_stream8_sig_virtualization_ovirt45 | default([]) if foreman_enable_centos_stream8_sig_virtualization_ovirt45 else [] )
  }}"


foreman_content_views_centos_stream8_sig_virtualization_advanced_virtualization:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_advanced_virtualization"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_advanced_virtualization }}"
    repositories:
      - name: CentOS Stream 8 - Advanced Virtualization
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_virtualization_ovirt44:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_ovirt44"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt44 }}"
    repositories:
      - name: CentOS 8 - oVirt 4.4
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_virtualization_ovirt45:
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_ovirt45"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
    repositories:
      - name: CentOS Stream 8 - oVirt 4.5
        product: CentOS
    allow_promote: False
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_ovirt45"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
    repositories:
      - name: CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository
        product: CentOS
    allow_promote: False
    filters:
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: ansible
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: ansible-test
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: openstack-ansible-core
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: python3-rdo-openvswitch
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: rdo-openvswitch
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: rdo-ovn
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: rdo-ovn-central
      - name: "CentOS Stream 8 - oVirt 4.5 - OpenStack Yoga Repository exclude filter"
        filter_type: "rpm"
        rule_name: rdo-ovn-host
  - name: "{{ foreman_cv_prefix | default('cv_') }}centos_stream8_ovirt45_upstream"
    organization: "{{ foreman_organization_centos_stream8_sig_virtualization_ovirt45 }}"
    repositories:
      - name: CentOS Stream 8 - oVirt 4.5 - upstream
        product: CentOS
    allow_promote: False

foreman_content_views_centos_stream8_sig_virtualization: "{{ [] |
  union( foreman_content_views_centos_stream8_sig_virtualization_advanced_virtualization | default([]) if foreman_enable_centos_stream8_sig_virtualization_advanced_virtualization else [] ) |
  union( foreman_content_views_centos_stream8_sig_virtualization_ovirt44 | default([]) if foreman_enable_centos_stream8_sig_virtualization_ovirt44 else [] ) |
  union( foreman_content_views_centos_stream8_sig_virtualization_ovirt45 | default([]) if foreman_enable_centos_stream8_sig_virtualization_ovirt45 else [] )
  }}"

