---
# centos content group vars file for foreman_content_centos

foreman_content_credentials_centos8: []

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-centosofficial
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_centos8:
  - name: CentOS
    label: CentOS
    repositories:
      - name: CentOS 8 - BaseOS
        label: centos-8-baseos
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/BaseOS/x86_64/os/"
      - name: CentOS 8 - AppStream
        label: centos-8-appstream
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/AppStream/x86_64/os/"
      - name: CentOS 8 - Extras
        label: centos-8-extras
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/extras/x86_64/os/"
      - name: CentOS 8 - Plus
        label: centos-8-plus
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/centosplus/x86_64/os/"
      - name: CentOS 8 - PowerTools
        label: centos-8-powertools
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/PowerTools/x86_64/os/"
      - name: CentOS 8 - HighAvailability
        label: centos-8-ha
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/HighAvailability/x86_64/os/"
      - name: CentOS 8 - ContinuousRelease
        label: centos-8-cr
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/cr/x86_64/os/"
      - name: CentOS 8 - FastTrack
        label: centos-8-fasttrack
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/fasttrack/x86_64/os/"

      - name: CentOS 8 - BaseOS Kickstart
        label: centos-8-baseos-kickstart
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/BaseOS/x86_64/kickstart/"
      - name: CentOS 8 - AppStream Kickstart
        label: centos-8-appstream-kickstart
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_centos_vault }}/8.5.2111/AppStream/x86_64/kickstart/"

foreman_content_views_centos8:
  - name: cv_centos8_baseos
    repositories:
      - name: CentOS 8 - BaseOS
        product: CentOS
    allow_promote: False
  - name: cv_centos8_appstream
    repositories:
      - name: CentOS 8 - AppStream
        product: CentOS
    allow_promote: False
  - name: cv_centos8_extras
    repositories:
      - name: CentOS 8 - Extras
        product: CentOS
    allow_promote: False
  - name: cv_centos8_plus
    repositories:
      - name: CentOS 8 - Plus
        product: CentOS
    allow_promote: False
  - name: cv_centos8_powertools
    repositories:
      - name: CentOS 8 - PowerTools
        product: CentOS
    allow_promote: False
  - name: cv_centos8_ha
    repositories:
      - name: CentOS 8 - HighAvailability
        product: CentOS
    allow_promote: False
  - name: cv_centos8_cr
    repositories:
      - name: CentOS 8 - ContinuousRelease
        product: CentOS
    allow_promote: False
  - name: cv_centos8_fasttrack
    repositories:
      - name: CentOS 8 - FastTrack
        product: CentOS
    allow_promote: False

  - name: ccv_centos8
    composite: True
    auto_publish: True
    components:
      - content_view: cv_centos8_baseos
        latest: true
      - content_view: cv_centos8_appstream
        latest: true
      - content_view: cv_centos8_extras
        latest: true
      - content_view: cv_centos8_plus
        latest: true
      - content_view: cv_centos8_powertools
        latest: true
      - content_view: cv_centos8_ha
        latest: true
      - content_view: cv_centos8_cr
        latest: true
      - content_view: cv_centos8_fasttrack
        latest: true
      - content_view: cv_epel8
        latest: true
      - content_view: cv_epel8_modular
        latest: true

foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_cloud_init | default( foreman_operatingsystems_centos_template_cloud_init | default( foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_finish | default( foreman_operatingsystems_centos_template_finish | default( foreman_operatingsystems_el_template_finish | default('Kickstart default finish') ) ) }}"
    - template_kind: "host_init_config"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_host_init_config | default( foreman_operatingsystems_centos_template_host_init_config | default( foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    - template_kind: "iPXE"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_ipxe | default( foreman_operatingsystems_centos_template_ipxe | default( foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_provision | default( foreman_operatingsystems_centos_template_provision | default( foreman_operatingsystems_el_template_provision | default('Kickstart default') ) ) }}"
    - template_kind: "PXEGrub"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_pxegrub | default( foreman_operatingsystems_centos_template_pxegrub | default( foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_pxegrub2 | default( foreman_operatingsystems_centos_template_pxegrub2 | default( foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_pxelinux | default( foreman_operatingsystems_centos_template_pxelinux | default( foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_centos8_template_user_data | default( foreman_operatingsystems_centos_template_user_data | default( foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') ) ) }}"

foreman_operatingsystems_centos8:
  - name: "CentOS"
    major: "8"
    minor: ""
    description: "CentOS 8"
    <<: *foreman_operatingsystems_defaults

foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"

foreman_installation_media_centos8:
  - name: CentOS 8 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-8-baseos-kickstart/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - CentOS 8
  - name: CentOS 8 AppStream
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/CentOS/centos-8-appstream-kickstart/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - CentOS 8

foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "CentOS"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  # release_version: 8
  # service_level: Standard

foreman_activation_keys_centos8:
  - name: ak_centos8
    content_view: ccv_centos8
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_CentOS_centos-8-baseos"
        override: default
      - label: "{{ foreman_organization }}_CentOS_centos-8-appstream"
        override: default
      - label: "{{ foreman_organization }}_CentOS_centos-8-extras"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-plus"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-powertools"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-ha"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-cr"
        override: disabled
      - label: "{{ foreman_organization }}_CentOS_centos-8-fasttrack"
        override: disabled
      - label: "{{ foreman_organization }}_EPEL_epel-8"
        override: disabled
      - label: "{{ foreman_organization }}_EPEL_epel-8-modular"
        override: disabled

foreman_sync_plan_products_centos8: []

