---

foreman_content_credentials_rocky8:
  - name: RPM-GPG-KEY-Rocky-8
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_rocky ~ '/RPM-GPG-KEY-Rocky-8', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-Rocky-8') }}"


foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-rockyofficial
  download_policy: "{{ foreman_products_defaults_download_policy_rocky8 }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_rocky8 }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_rocky8 | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_rocky8 }}"
  unprotected: "{{ foreman_products_defaults_unprotected_rocky8 | bool }}"


foreman_products_defaults_rocky8_kickstart: &foreman_products_defaults_rocky8_kickstart
  <<: *foreman_products_defaults
  download_policy: "{{ foreman_products_defaults_download_policy_rocky8_kickstart }}"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_rocky8_kickstart }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_rocky8_kickstart | bool }}"
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_rocky8_kickstart }}"
  unprotected: "{{ foreman_products_defaults_unprotected_rocky8_kickstart | bool }}"


foreman_products_rocky8:
  - name: Rocky Linux
    label: Rocky
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - BaseOS
        label: rocky-8-baseos
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/BaseOS/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"
      - name: Rocky Linux 8 - AppStream
        label: rocky-8-appstream
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/AppStream/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"

      - name: Rocky Linux 8 - Extras
        label: rocky-8-extras
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/extras/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"
      - name: Rocky Linux 8 - Plus
        label: rocky-8-plus
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/plus/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"
      - name: Rocky Linux 8 - PowerTools
        label: rocky-8-powertools
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/PowerTools/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"
      - name: Rocky Linux 8 - HighAvailability
        label: rocky-8-ha
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/HighAvailability/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"
      - name: Rocky Linux 8 - NFV
        label: rocky-8-nfv
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/nfv/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"
      - name: Rocky Linux 8 - ResilientStorage
        label: rocky-8-resilientstorage
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/ResilientStorage/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"
      - name: Rocky Linux 8 - Realtime
        label: rocky-8-rt
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/RT/x86_64/os/"
        organization: "{{ foreman_organization_rocky8 }}"

      - name: Rocky Linux 8 - BaseOS Kickstart
        label: rocky-8-baseos-kickstart
        <<: *foreman_products_defaults_rocky8_kickstart
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/BaseOS/x86_64/kickstart/"
        organization: "{{ foreman_organization_rocky8 }}"
      - name: Rocky Linux 8 - AppStream Kickstart
        label: rocky-8-appstream-kickstart
        <<: *foreman_products_defaults_rocky8_kickstart
        url: "{{ foreman_repo_baseurl_rocky8 }}/8/AppStream/x86_64/kickstart/"
        organization: "{{ foreman_organization_rocky8 }}"


foreman_content_views_rocky8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_baseos"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - BaseOS
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_appstream"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - AppStream
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_extras"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - Extras
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_plus"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - Plus
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_powertools"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - PowerTools
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_ha"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - HighAvailability
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_nfv"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - NFV
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_resilientstorage"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - ResilientStorage
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}rocky8_rt"
    organization: "{{ foreman_organization_rocky8 }}"
    repositories:
      - name: Rocky Linux 8 - Realtime
        product: Rocky Linux
    allow_promote: "{{ foreman_cv_allow_promote_rocky8 }}"

foreman_composite_content_views_rocky8:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}rocky8"
    organization: "{{ foreman_organization_rocky8 }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_rocky8 }}"
    auto_publish: "{{ foreman_ccv_auto_publish_rocky8 }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_baseos"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_appstream"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_extras"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_plus"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_powertools"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_ha"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_nfv"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_resilientstorage"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}rocky8_rt"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}epel8"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}epel8_modular"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"


foreman_operatingsystems_rocky8:
  - name: "Rocky"
    major: "8"
    minor: ""
    description: "Rocky Linux 8"
    default_templates: "{{ foreman_operatingsystems_rocky8_default_templates | default( foreman_operatingsystems_rocky_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"
  # operatingsystems:
  #   - Rocky Linux 8


foreman_installation_media_rocky8:
  - name: Rocky Linux 8 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Rocky_Linux/rocky-8-baseos-kickstart/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Rocky Linux 8
  - name: Rocky Linux 8 AppStream
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Rocky_Linux/rocky-8-appstream-kickstart/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Rocky Linux 8


foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Rocky Linux"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  # release_version: 8
  # service_level: Standard


foreman_activation_keys_rocky8:
  - name: ak_rocky8
    organization: "{{ foreman_organization_rocky8 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}rocky8"
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_Rocky_rocky-8-baseos"
        override: default
      - label: "{{ foreman_organization }}_Rocky_rocky-8-appstream"
        override: default
      - label: "{{ foreman_organization }}_Rocky_rocky-8-extras"
        override: disabled
      - label: "{{ foreman_organization }}_Rocky_rocky-8-plus"
        override: disabled
      - label: "{{ foreman_organization }}_Rocky_rocky-8-powertools"
        override: disabled
      - label: "{{ foreman_organization }}_Rocky_rocky-8-ha"
        override: disabled
      - label: "{{ foreman_organization }}_Rocky_rocky-8-nfv"
        override: disabled
      - label: "{{ foreman_organization }}_Rocky_rocky-8-resilientstorage"
        override: disabled
      - label: "{{ foreman_organization }}_Rocky_rocky-8-rt"
        override: disabled
      - label: "{{ foreman_organization }}_EPEL_epel-8"
        override: disabled
      - label: "{{ foreman_organization }}_EPEL_epel-8-modular"
        override: disabled


  # - name: ak_rocky8_foreman
  #   organization: "{{ foreman_organization_rocky8 }}"
  #   content_view: "{{ foreman_ccv_prefix | default('ccv_') }}rocky8_foreman"
  #   <<: *foreman_activation_keys_defaults
  #   content_overrides:
  #     - label: "{{ foreman_organization }}_Rocky_rocky-8-baseos"
  #       override: default
  #     - label: "{{ foreman_organization }}_Rocky_rocky-8-appstream"
  #       override: default
  #     - label: "{{ foreman_organization }}_Rocky_rocky-8-extras"
  #       override: disabled
  #     - label: "{{ foreman_organization }}_Rocky_rocky-8-powertools"
  #       override: disabled
  #     - label: "{{ foreman_organization }}_Foreman_foreman-{{ foreman_version_label }}-el8"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_foreman-plugins-{{ foreman_version_label }}-el8"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_puppet{{ foreman_puppet_version }}-el8"
  #       override: default


  # - name: ak_rocky8_katello
  #   organization: "{{ foreman_organization_rocky8 }}"
  #   content_view: "{{ foreman_ccv_prefix | default('ccv_') }}rocky8_katello"
  #   <<: *foreman_activation_keys_defaults
  #   content_overrides:
  #     - label: "{{ foreman_organization }}_Rocky_rocky-8-baseos"
  #       override: default
  #     - label: "{{ foreman_organization }}_Rocky_rocky-8-appstream"
  #       override: default
  #     - label: "{{ foreman_organization }}_Rocky_rocky-8-extras"
  #       override: disabled
  #     - label: "{{ foreman_organization }}_Rocky_rocky-8-powertools"
  #       override: disabled
  #     - label: "{{ foreman_organization }}_Foreman_foreman-{{ foreman_version_label }}-el8"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_foreman-plugins-{{ foreman_version_label }}-el8"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_katello-{{ foreman_katello_version_label }}-el8"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_katello-{{ foreman_katello_version_label }}-candlepin-el8"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_pulpcore-{{ foreman_pulpcore_version_label }}-el8"
  #       override: default
  #     - label: "{{ foreman_organization }}_Foreman_puppet{{ foreman_puppet_version }}-el8"
  #       override: default


foreman_sync_plan_products_rocky8: []

