---
# foreman rocky linux content vars file for foreman_content_rocky

foreman_content_credentials_rocky9:
  - name: RPM-GPG-KEY-Rocky-9
    content_type: gpg_key
    content: "{{ lookup('ansible.builtin.url', foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky) ~ '/RPM-GPG-KEY-Rocky-9', split_lines=False, validate_certs=False) }}"
    # content: "{{ lookup('ansible.builtin.file', role_path ~ '/files/RPM-GPG-KEY-Rocky-9') }}"

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: RPM-GPG-KEY-rockyofficial
  download_policy: on_demand
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  mirroring_policy: "mirror_complete"
  verify_ssl_on_sync: False
  # http_proxy: Default Proxy
  http_proxy_policy: global_default_http_proxy

foreman_products_rocky9:
  - name: Rocky Linux
    label: Rocky
    repositories:
      - name: Rocky Linux 9 - BaseOS
        label: rocky-9-baseos
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/BaseOS/x86_64/os/"
      - name: Rocky Linux 9 - AppStream
        label: rocky-9-appstream
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/AppStream/x86_64/os/"
      - name: Rocky Linux 9 - Extras
        label: rocky-9-extras
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/extras/x86_64/os/"
      - name: Rocky Linux 9 - Plus
        label: rocky-9-plus
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/plus/x86_64/os/"
      - name: Rocky Linux 9 - Code Ready Builder
        label: rocky-9-crb
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/CRB/x86_64/os/"
      - name: Rocky Linux 9 - HighAvailability
        label: rocky-9-ha
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/HighAvailability/x86_64/os/"
      - name: Rocky Linux 9 - NFV
        label: rocky-9-nfv
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/NFV/x86_64/os/"
      - name: Rocky Linux 9 - ResilientStorage
        label: rocky-9-resilientstorage
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/ResilientStorage/x86_64/os/"
      - name: Rocky Linux 9 - Realtime
        label: rocky-9-rt
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/RT/x86_64/os/"
      - name: Rocky Linux 9 - SAP
        label: rocky-9-sap
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/SAP/x86_64/os/"
      - name: Rocky Linux 9 - SAPHANA
        label: rocky-9-saphana
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9/SAPHANA/x86_64/os/"

      # - name: Rocky Linux 9 - BaseOS Kickstart 9.0
      #   label: rocky-9-baseos-kickstart-9_0
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky_vault) }}/9.0/BaseOS/x86_64/kickstart/"
      # - name: Rocky Linux 9 - AppStream Kickstart 9.0
      #   label: rocky-9-appstream-kickstart-9_0
      #   <<: *foreman_products_defaults
      #   url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky_vault) }}/9.0/AppStream/x86_64/kickstart/"
      - name: Rocky Linux 9 - BaseOS Kickstart 9.1
        label: rocky-9-baseos-kickstart-9_1
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky_vault) }}/9.1/BaseOS/x86_64/kickstart/"
      - name: Rocky Linux 9 - AppStream Kickstart 9.1
        label: rocky-9-appstream-kickstart-9_1
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky_vault) }}/9.1/AppStream/x86_64/kickstart/"
      - name: Rocky Linux 9 - BaseOS Kickstart 9.2
        label: rocky-9-baseos-kickstart-9_2
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9.2/BaseOS/x86_64/kickstart/"
      - name: Rocky Linux 9 - AppStream Kickstart 9.2
        label: rocky-9-appstream-kickstart-9_2
        <<: *foreman_products_defaults
        url: "{{ foreman_repo_baseurl_rocky | default(foreman_default_repo_baseurl_rocky9) }}/9.2/AppStream/x86_64/kickstart/"

foreman_content_views_rocky9:
  - name: cv_rocky9_baseos
    repositories:
      - name: Rocky Linux 9 - BaseOS
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_appstream
    repositories:
      - name: Rocky Linux 9 - AppStream
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_extras
    repositories:
      - name: Rocky Linux 9 - Extras
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_plus
    repositories:
      - name: Rocky Linux 9 - Plus
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_crb
    repositories:
      - name: Rocky Linux 9 - Code Ready Builder
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_ha
    repositories:
      - name: Rocky Linux 9 - HighAvailability
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_nfv
    repositories:
      - name: Rocky Linux 9 - NFV
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_resilientstorage
    repositories:
      - name: Rocky Linux 9 - ResilientStorage
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_rt
    repositories:
      - name: Rocky Linux 9 - Realtime
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_sap
    repositories:
      - name: Rocky Linux 9 - SAP
        product: Rocky Linux
    allow_promote: False
  - name: cv_rocky9_saphana
    repositories:
      - name: Rocky Linux 9 - SAPHANA
        product: Rocky Linux
    allow_promote: False

  - name: ccv_rocky9
    composite: True
    auto_publish: True
    components:
      - content_view: cv_rocky9_baseos
        latest: true
      - content_view: cv_rocky9_appstream
        latest: true
      - content_view: cv_rocky9_extras
        latest: true
      - content_view: cv_rocky9_plus
        latest: true
      - content_view: cv_rocky9_crb
        latest: true
      # - content_view: cv_rocky9_ha
      #   latest: true
      # - content_view: cv_rocky9_nfv
      #   latest: true
      # - content_view: cv_rocky9_resilientstorage
      #   latest: true
      # - content_view: cv_rocky9_rt
      #   latest: true
      - content_view: cv_epel9
        latest: true

foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"
  default_templates:
    - template_kind: "cloud-init"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_cloud_init | default( foreman_operatingsystems_rocky_template_cloud_init | default( foreman_operatingsystems_el_template_cloud_init | default('CloudInit default') ) ) }}"
    - template_kind: "finish"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_finish | default( foreman_operatingsystems_rocky_template_finish | default( foreman_operatingsystems_el_template_finish | default('Kickstart default finish') ) ) }}"
    - template_kind: "host_init_config"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_host_init_config | default( foreman_operatingsystems_rocky_template_host_init_config | default( foreman_operatingsystems_el_template_host_init_config | default('Linux host_init_config default') ) ) }}"
    - template_kind: "iPXE"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_ipxe | default( foreman_operatingsystems_rocky_template_ipxe | default( foreman_operatingsystems_el_template_ipxe | default('Kickstart default iPXE') ) ) }}"
    - template_kind: "provision"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_provision | default( foreman_operatingsystems_rocky_template_provision | default( foreman_operatingsystems_el_template_provision | default('Kickstart default') ) ) }}"
    - template_kind: "PXEGrub"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_pxegrub | default( foreman_operatingsystems_rocky_template_pxegrub | default( foreman_operatingsystems_el_template_pxegrub | default('Kickstart default PXEGrub') ) ) }}"
    - template_kind: "PXEGrub2"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_pxegrub2 | default( foreman_operatingsystems_rocky_template_pxegrub2 | default( foreman_operatingsystems_el_template_pxegrub2 | default('Kickstart default PXEGrub2') ) ) }}"
    - template_kind: "PXELinux"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_pxelinux | default( foreman_operatingsystems_rocky_template_pxelinux | default( foreman_operatingsystems_el_template_pxelinux | default('Kickstart default PXELinux') ) ) }}"
    - template_kind: "user_data"
      provisioning_template: "{{ foreman_operatingsystems_rocky9_template_user_data | default( foreman_operatingsystems_rocky_template_user_data | default( foreman_operatingsystems_el_template_user_data | default('Kickstart default user data') ) ) }}"

foreman_operatingsystems_rocky9:
  - name: "Rocky"
    major: "9"
    minor: ""
    description: "Rocky Linux 9"
    <<: *foreman_operatingsystems_defaults
  - name: "Rocky"
    major: "9"
    minor: "0"
    description: "Rocky Linux 9.0"
    <<: *foreman_operatingsystems_defaults
  - name: "Rocky"
    major: "9"
    minor: "1"
    description: "Rocky Linux 9.1"
    <<: *foreman_operatingsystems_defaults

foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"
  # operatingsystems:
  #   - Rocky Linux 8
  #   - Rocky Linux 9

foreman_installation_media_rocky9:
  # - name: Rocky Linux 9.0 BaseOS
  #   path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Rocky_Linux/rocky-9-baseos-kickstart-9_0/"
  #   <<: *foreman_installation_media_defaults
  #   operatingsystems:
  #     - Rocky Linux 9.0
  # - name: Rocky Linux 9.0 AppStream
  #   path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Rocky_Linux/rocky-9-appstream-kickstart-9_0/"
  #   <<: *foreman_installation_media_defaults
  #   operatingsystems:
  #     - Rocky Linux 9.0
  - name: Rocky Linux 9.1 BaseOS
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Rocky_Linux/rocky-9-baseos-kickstart-9_1/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Rocky Linux 9
      - Rocky Linux 9.1
  - name: Rocky Linux 9.1 AppStream
    path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/custom/Rocky_Linux/rocky-9-appstream-kickstart-9_1/"
    <<: *foreman_installation_media_defaults
    operatingsystems:
      - Rocky Linux 9
      - Rocky Linux 9.1

foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  organization: "{{ foreman_organization }}"
  # lifecycle_environment: "Library"
  # subscriptions:
  #   - name: "Rocky Linux"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  # release_version: 7Server
  # service_level: Standard

foreman_activation_keys_rocky9:
  - name: ak_rocky9
    content_view: ccv_rocky9
    <<: *foreman_activation_keys_defaults
    content_overrides:
      - label: "{{ foreman_organization }}_Rocky_rocky-9-baseos"
        override: default
      - label: "{{ foreman_organization }}_Rocky_rocky-9-appstream"
        override: default
      - label: "{{ foreman_organization }}_Rocky_rocky-9-extras"
        override: default
      - label: "{{ foreman_organization }}_Rocky_rocky-9-plus"
        override: disabled
      - label: "{{ foreman_organization }}_Rocky_rocky-9-crb"
        override: disabled
      # - label: "{{ foreman_organization }}_Rocky_rocky-9-ha"
      #   override: disabled
      # - label: "{{ foreman_organization }}_Rocky_rocky-9-nfv"
      #   override: disabled
      # - label: "{{ foreman_organization }}_Rocky_rocky-9-resilientstorage"
      #   override: disabled
      # - label: "{{ foreman_organization }}_Rocky_rocky-9-rt"
      #   override: disabled
      - label: "{{ foreman_organization }}_EPEL_epel-9"
        override: disabled

foreman_sync_plan_products_rocky9: []

